# Generated by Django 4.2.6 on 2026-07-10 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0002_alter_branch_options_alter_broilerbatch_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(help_text='Full name of the farmer', max_length=150)),
                ('phone_no', models.CharField(blank=True, help_text='Landline/phone number of the farmer', max_length=15, null=True)),
                ('mobile_no', models.CharField(blank=True, help_text='Primary mobile number of the farmer', max_length=15, null=True)),
                ('mobile_2', models.CharField(blank=True, help_text='Secondary mobile number of the farmer', max_length=15, null=True)),
                ('farmer_photo', models.ImageField(blank=True, help_text='Photograph of the farmer', null=True, upload_to='farmer/photos/')),
                ('pan_no', models.CharField(blank=True, help_text='PAN number of the farmer', max_length=10, null=True)),
                ('aadhar_no', models.CharField(blank=True, help_text='Aadhar number of the farmer', max_length=12, null=True)),
                ('national_id', models.CharField(blank=True, help_text='National ID of the farmer', max_length=50, null=True)),
                ('pan_upload', models.FileField(blank=True, help_text='Uploaded copy of PAN card', null=True, upload_to='farmer/pan/')),
                ('aadhar_upload_front', models.FileField(blank=True, help_text='Uploaded copy of Aadhar card (front)', null=True, upload_to='farmer/aadhar/')),
                ('aadhar_upload_back', models.FileField(blank=True, help_text='Uploaded copy of Aadhar card (back)', null=True, upload_to='farmer/aadhar/')),
                ('usc', models.CharField(blank=True, help_text='USC of the farmer', max_length=50, null=True)),
                ('service_no', models.CharField(blank=True, help_text='Service number of the farmer', max_length=50, null=True)),
                ('farmer_group', models.CharField(help_text='Group the farmer belongs to', max_length=100)),
                ('tds_percent', models.DecimalField(blank=True, decimal_places=2, help_text='TDS percentage applicable to the farmer', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('account_holder_name', models.CharField(blank=True, help_text='Name on the bank account', max_length=150, null=True)),
                ('acc_no', models.CharField(blank=True, help_text='Bank account number', max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='Bank IFSC code', max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Name of the bank', max_length=100, null=True)),
                ('bank_branch', models.CharField(blank=True, help_text='Bank branch', max_length=100, null=True)),
                ('address', models.TextField(blank=True, help_text='Residential address of the farmer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['farmer_name'],
            },
        ),
        migrations.RemoveField(
            model_name='broilerfarm',
            name='address',
        ),
        migrations.RemoveField(
            model_name='broilerfarm',
            name='block_name',
        ),
        migrations.RemoveField(
            model_name='broilerfarm',
            name='broiler_place',
        ),
        migrations.RemoveField(
            model_name='broilerfarm',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='agreement_copy',
            field=models.FileField(default='', help_text='Uploaded copy of the agreement', upload_to='farm/agreements/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='agreement_end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Agreement end date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='agreement_months',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the agreement in months', null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='agreement_start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Agreement start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='area',
            field=models.CharField(blank=True, help_text='Area where the farm is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_1_file',
            field=models.FileField(blank=True, help_text='Security cheque 1 scan', null=True, upload_to='farm/cheques/'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_1_no',
            field=models.CharField(blank=True, help_text='Security cheque 1 number', max_length=30),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_2_file',
            field=models.FileField(blank=True, help_text='Security cheque 2 scan', null=True, upload_to='farm/cheques/'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_2_no',
            field=models.CharField(blank=True, help_text='Security cheque 2 number', max_length=30),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_3_file',
            field=models.FileField(blank=True, help_text='Security cheque 3 scan', null=True, upload_to='farm/cheques/'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_3_no',
            field=models.CharField(blank=True, help_text='Security cheque 3 number', max_length=30),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_4_file',
            field=models.FileField(blank=True, help_text='Security cheque 4 scan', null=True, upload_to='farm/cheques/'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='cheque_4_no',
            field=models.CharField(blank=True, help_text='Security cheque 4 number', max_length=30),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='district',
            field=models.CharField(blank=True, help_text='District where the farm is located', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='farm_address',
            field=models.TextField(blank=True, help_text='Detailed address of the farm', null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='farm_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Bird capacity of the farm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='farm_pincode',
            field=models.CharField(blank=True, help_text='Pincode of the farm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='farm_sqft',
            field=models.CharField(blank=True, help_text='Farm area in square feet', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='line',
            field=models.CharField(default='', help_text='Line for this farm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Other supporting documents', null=True, upload_to='farm/documents/'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='region',
            field=models.CharField(default='', help_text='Region of the farm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks about the farm/shed information', null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='state',
            field=models.CharField(blank=True, help_text='State where the farm is located', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='farm_latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate of the farm', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='farm_longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate of the farm', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='farm_type',
            field=models.CharField(choices=[('own', 'Own'), ('ec_shed', 'Ec Shed'), ('integration', 'Integration')], default='own', help_text='Type of farm operation', max_length=50),
        ),
        migrations.CreateModel(
            name='BroilerFarmShed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_no', models.CharField(help_text='Shed number/identifier', max_length=50)),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions of the shed', max_length=100, null=True)),
                ('sq_feet', models.CharField(blank=True, help_text='Area of the shed in square feet', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(help_text='Farm this shed belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to='broiler.broilerfarm')),
            ],
            options={
                'verbose_name': 'Broiler Farm Shed',
                'verbose_name_plural': 'Broiler Farm Sheds',
                'ordering': ['shed_no'],
            },
        ),
        migrations.CreateModel(
            name='BroilerFarmImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Farm picture', upload_to='farm/pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(help_text='Farm this picture belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='broiler.broilerfarm')),
            ],
            options={
                'verbose_name': 'Broiler Farm Image',
                'verbose_name_plural': 'Broiler Farm Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='farmer',
            field=models.ForeignKey(default=1, help_text='Farmer who owns/operates this farm', on_delete=django.db.models.deletion.CASCADE, related_name='broiler_farms', to='broiler.farmer'),
            preserve_default=False,
        ),
    ]
