# Generated by Django 4.2.6 on 2026-07-11 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_schedule_options_alter_bankcode_phone_and_more'),
        ('broiler', '0003_farmer_remove_broilerfarm_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Auto-generated code for this farmer group', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Name of the farmer group', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive groups are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advance_account', models.ForeignKey(help_text='Advance account for this group', on_delete=django.db.models.deletion.PROTECT, related_name='farmer_group_advance_accounts', to='account.chartofaccount')),
                ('pay_account', models.ForeignKey(help_text='Payable account for this group', on_delete=django.db.models.deletion.PROTECT, related_name='farmer_group_pay_accounts', to='account.chartofaccount')),
            ],
            options={
                'verbose_name': 'Farmer Group',
                'verbose_name_plural': 'Farmer Groups',
                'ordering': ['code'],
            },
        ),
    ]
