# Generated by Django 4.2.6 on 2026-07-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0007_broilerline_restructure'),
    ]

    operations = [
        # farmer_group is switching from free-text (CharField) to a foreign
        # key referencing the new FarmerGroup table. No FarmerGroup rows
        # could have existed before this migration, so any pre-existing
        # farmer_group text is guaranteed to be old free-text data that
        # can't be cast to a valid FK id - clear it out before changing the
        # column type. The SQL is written in a backend-agnostic way so it
        # works in local SQLite and PostgreSQL.
        migrations.RunSQL(
            sql=(
                'UPDATE broiler_farmer SET farmer_group = NULL;'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmer_group',
            field=models.ForeignKey(help_text='Group the farmer belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='broiler.farmergroup'),
        ),
    ]
