# Generated by Django 4.2.6 on 2026-07-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0007_broilerline_restructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_group',
            field=models.ForeignKey(help_text='Group the farmer belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='broiler.farmergroup'),
        ),
    ]
