# Generated by Django 4.2.6 on 2026-07-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_warehouse_branch'),
        ('broiler', '0008_alter_farmer_farmer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Office/warehouse this branch is mapped to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='inventory.warehouse'),
        ),
    ]
