# Generated by Django 4.2.6 on 2026-07-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0009_branch_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='warehouse',
        ),
    ]
