# Generated by Django 4.2.6 on 2026-07-18 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_warehouse_code'),
        ('broiler', '0010_remove_branch_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. DE-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('age_days', models.PositiveIntegerField(default=0, editable=False, help_text="Days since the batch's start date")),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('culls', models.PositiveIntegerField(default=0)),
                ('feed_1_qty', models.DecimalField(decimal_places=2, default=0, help_text='Kgs fed', max_digits=10)),
                ('feed_1_stock', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Running closing stock after this entry', max_digits=12)),
                ('feed_2_qty', models.DecimalField(decimal_places=2, default=0, help_text='Kgs fed', max_digits=10)),
                ('feed_2_stock', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Running closing stock after this entry', max_digits=12)),
                ('avg_weight_gms', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text="Auto-set to the farm's active batch at the time of entry", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='broiler.broilerbatch')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_daily_entries', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='broiler.broilerfarm')),
                ('feed_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entry_feed_1', to='inventory.item')),
                ('feed_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_entry_feed_2', to='inventory.item')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_entries', to='broiler.supervisor')),
            ],
            options={
                'verbose_name': 'Daily Entry',
                'verbose_name_plural': 'Daily Entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
