# Generated by Django 4.2.6 on 2026-07-18 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_warehouse_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0011_dailyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineVaccineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. MV-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('age_days', models.PositiveIntegerField(default=0, editable=False, help_text="Days since the batch's start date")),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Running closing stock after this entry', max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text="Auto-set to the farm's active batch at the time of entry", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_entries', to='broiler.broilerbatch')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_medicine_entries', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_entries', to='broiler.broilerfarm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_entries', to='inventory.item')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_entries', to='broiler.supervisor')),
            ],
            options={
                'verbose_name': 'Medicine/Vaccine Entry',
                'verbose_name_plural': 'Medicine/Vaccine Entries',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
