# Generated by Django 4.2.6 on 2026-07-18 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customergroup_advance_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0012_medicinevaccineentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. BS-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('doc_no', models.CharField(blank=True, help_text='External/reference document number', max_length=100)),
                ('sale_type', models.CharField(choices=[('customer', 'Customer Sale'), ('farmer', 'Farmer Sale')], default='customer', max_length=10)),
                ('birds', models.PositiveIntegerField(default=0)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0, help_text='Net weight in Kgs', max_digits=10)),
                ('avg_weight', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Net weight / Birds', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, help_text='Rate per Kg', max_digits=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Net weight x Rate + RoundOff', max_digits=14)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, help_text="Auto-set to the farm's active batch at the time of sale", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_sales', to='broiler.broilerbatch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_sales', to='sales.customer')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_bird_sales', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_sales', to='broiler.broilerfarm')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_sales', to='broiler.farmer')),
                ('lifting_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bird_sales', to='broiler.supervisor')),
            ],
            options={
                'verbose_name': 'Bird Sale',
                'verbose_name_plural': 'Bird Sales',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
