# Generated by Django 4.2.6 on 2026-07-18 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0006_alter_customergroup_advance_account_and_more'),
        ('inventory', '0024_itemcategory_code'),
        ('account', '0012_backfill_expense_ledger_roles'),
        ('broiler', '0013_birdsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSaleReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. RC-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sale_type', models.CharField(choices=[('customer', 'Customer Sale'), ('farmer', 'Farmer Sale')], default='customer', max_length=10)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_sale_receipts', to='sales.customer')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_bird_sale_receipts', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bird_sale_receipts', to='broiler.farmer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_sale_receipts', to='inventory.warehouse')),
                ('receipt_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bird_sale_receipts', to='account.chartofaccount')),
            ],
            options={
                'verbose_name': 'Bird Sale Receipt',
                'verbose_name_plural': 'Bird Sale Receipts',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
