# Generated by Django 4.2.6 on 2026-07-19 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_delete_sector'),
        ('broiler', '0014_birdsalereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='HR employee record this supervisor is — name/phone/address are copied from here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_supervisor_roles', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address of the supervisor'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact number of the supervisor', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
