# Generated by Django 4.2.6 on 2026-07-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0015_supervisor_employee_alter_supervisor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerfarm',
            name='farm_code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. FRM/AKB-0203 — FRM/<branch prefix>-<branch code suffix><farm serial>', max_length=50, unique=True),
        ),
    ]
