# Generated by Django 4.2.6 on 2026-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0016_alter_broilerfarm_farm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerbatch',
            name='batch_name',
            field=models.CharField(blank=True, help_text='Auto-generated per farm, e.g. FRM/BAH-0201-BATCH 1', max_length=50),
        ),
    ]
