# Generated by Django 4.2.6 on 2026-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0017_alter_broilerbatch_batch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerbatch',
            name='book_number',
            field=models.CharField(blank=True, help_text='Grower book number for this batch', max_length=50),
        ),
        migrations.AddField(
            model_name='broilerbatch',
            name='lot_no',
            field=models.CharField(blank=True, help_text='Lot number for this batch', max_length=50),
        ),
    ]
