# Generated by Django 4.2.6 on 2026-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0018_broilerbatch_book_number_broilerbatch_lot_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerfarm',
            name='agreement_copy',
            field=models.FileField(blank=True, help_text='Uploaded copy of the agreement', null=True, upload_to='farm/agreements/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='agreement_end_date',
            field=models.DateField(blank=True, help_text='Agreement end date', null=True),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='agreement_start_date',
            field=models.DateField(blank=True, help_text='Agreement start date', null=True),
        ),
    ]
