# Generated by Django 4.2.6 on 2026-07-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0019_alter_broilerfarm_agreement_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerbatch',
            name='batch_name',
            field=models.CharField(blank=True, help_text='Auto-generated per farm, e.g. BAH-0201-1', max_length=50),
        ),
    ]
