# Generated by Django 4.2.6 on 2026-07-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0020_alter_broilerbatch_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerfarm',
            name='farm_code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. AKB-0203 — <branch prefix>-<branch code suffix><farm serial>', max_length=50, unique=True),
        ),
    ]
