# Generated by Django 4.2.6 on 2026-07-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0021_alter_broilerfarm_farm_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowingChargeScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. GCS-0001', max_length=20, unique=True)),
                ('from_date', models.DateField(help_text='Applicable from date')),
                ('to_date', models.DateField(help_text='Applicable to date')),
                ('schema_name', models.CharField(help_text='Scheme / schema name', max_length=150)),
                ('chick_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine_cost_basis', models.CharField(choices=[('actual', 'Actual'), ('master', 'Master'), ('fixed', 'Fixed')], default='actual', max_length=10)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0, help_text='Fixed medicine cost value (used when basis = Fixed)', max_digits=12)),
                ('farmer_admin_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('management_admin_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('std_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_gc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_gc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_fcr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('standard_mortality', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unloading_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_prod_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maximum_rate_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mort_dec_first_week_exceeds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mort_dec_overall_above', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mort_dec_first_week_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shortage_basis', models.CharField(choices=[('std_production_cost', 'Std Production Cost'), ('production_cost', 'Production Cost'), ('avg_sale_rate', 'Avg. Sale Rate'), ('max_sale_rate', 'Max. Sale Rate'), ('which_is_higher', 'Which is Higher')], default='which_is_higher', help_text='Which value is used for shortage recovery', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch; blank = all branches', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='growing_charge_schemes', to='broiler.branch')),
                ('region', models.ForeignKey(help_text='Region this scheme applies to', on_delete=django.db.models.deletion.PROTECT, related_name='growing_charge_schemes', to='broiler.region')),
            ],
            options={
                'verbose_name': 'Growing Charge Scheme',
                'verbose_name_plural': 'Growing Charge Schemes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GCSummerIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentive_on', models.CharField(choices=[('sold_birds', 'Sold Birds'), ('placed_birds', 'Placed Birds'), ('live_birds', 'Live Birds')], default='sold_birds', max_length=15)),
                ('from_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('to_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentive_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_incentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCSalesIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_rate_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_rate_to', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sales_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_incentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCProductionCostIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('to_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cost_incentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCProductionCostDecentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('to_production_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_cost_decentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCMortalityIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mortality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('to_mortality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incentive_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_incentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCMortalityDecentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mortality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('to_mortality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decentive_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_decentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCFCRRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfcr_limit', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('production_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcr_recoveries', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCFCRIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfcr_limit', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('body_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('incentive_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcr_incentives', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCFarmerClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_cost_from', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('production_to', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_classifications', to='broiler.growingchargescheme')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
