# Generated by Django 4.2.6 on 2026-07-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0022_growingchargescheme_gcsummerincentive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Auto-generated code for this breed', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Name of the breed', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive breeds are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'ordering': ['code'],
            },
        ),
    ]
