# Generated by Django 4.2.6 on 2026-07-22 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0023_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Auto-generated code for this breed standard row', max_length=20, unique=True)),
                ('age', models.PositiveIntegerField(help_text='Age (day) of the standard row')),
                ('body_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feed_intake', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_daily_gain', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcr', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cum_feed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive rows are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(help_text='Breed this standard row belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='broiler.breed')),
            ],
            options={
                'verbose_name': 'Breed Standard',
                'verbose_name_plural': 'Breed Standards',
                'ordering': ['breed__code', 'age'],
                'unique_together': {('breed', 'age')},
            },
        ),
    ]
