# Generated by Django 4.2.6 on 2026-07-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0025_broilerbatch_closed_on_broilerbatch_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingchargesettlement',
            name='gc_incentive_decentive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
