# Generated by Django 4.2.6 on 2026-07-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0026_growingchargesettlement_gc_incentive_decentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerbatch',
            name='breed',
            field=models.ForeignKey(blank=True, help_text='Breed of this flock — used for standard performance comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='broiler.breed'),
        ),
    ]
