# Generated by Django 4.2.6 on 2026-07-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0027_broilerbatch_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='cull_image',
            field=models.ImageField(blank=True, help_text="Photo evidence of the day's culls", null=True, upload_to='daily_entry/cull/'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='entry_latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude where the entry was recorded', null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='entry_longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude where the entry was recorded', null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_image',
            field=models.ImageField(blank=True, help_text='Photo of feed stock/consumption', null=True, upload_to='daily_entry/feed/'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='mort_image',
            field=models.ImageField(blank=True, help_text="Photo evidence of the day's mortality", null=True, upload_to='daily_entry/mort/'),
        ),
    ]
