# Generated by Django 4.2.6 on 2026-07-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
        ('broiler', '0028_dailyentry_cull_image_dailyentry_entry_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broilerfarmshed',
            options={'ordering': ['farm__farm_code', 'unit_no', 'shed_no'], 'verbose_name': 'Broiler Farm Shed', 'verbose_name_plural': 'Broiler Farm Sheds'},
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='organization_centre',
            field=models.ForeignKey(blank=True, help_text="Cost/Organization Centre — auto-set from the farm's branch", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_sheds', to='account.organizationcentre'),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='shed_code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. SHED-0001', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='shed_name',
            field=models.CharField(blank=True, help_text='Descriptive name of the shed', max_length=100),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='shed_type',
            field=models.CharField(choices=[('broiler', 'Broiler'), ('breeder', 'Breeder'), ('layer', 'Layer'), ('grower', 'Grower'), ('quarantine', 'Quarantine')], default='broiler', help_text='Type of shed', max_length=20),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='unit_no',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Auto-assigned running unit number within the farm (1,2,3…)'),
        ),
        migrations.AlterField(
            model_name='broilerfarmshed',
            name='shed_no',
            field=models.CharField(blank=True, help_text='Legacy shed number/identifier', max_length=50),
        ),
    ]
