# Generated by Django 4.2.6 on 2026-07-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0029_alter_broilerfarmshed_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerfarmshed',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Bird holding capacity of the shed'),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='occupied',
            field=models.PositiveIntegerField(default=0, help_text='Birds currently housed in the shed'),
        ),
    ]
