# Generated by Django 4.2.6 on 2026-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0030_broilerfarmshed_capacity_broilerfarmshed_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerfarmshed',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shed length in feet', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarmshed',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Shed width in feet', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='broilerfarmshed',
            name='dimensions',
            field=models.CharField(blank=True, help_text="Auto-composed 'L x W ft' from length & width", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broilerfarmshed',
            name='sq_feet',
            field=models.CharField(blank=True, help_text='Auto-calculated area (length x width) in square feet', max_length=20, null=True),
        ),
    ]
