# Generated by Django 4.2.6 on 2026-07-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0031_broilerfarmshed_length_broilerfarmshed_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerbatch',
            name='shed',
            field=models.ForeignKey(blank=True, help_text='Shed / unit within the farm this batch is housed in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_batches', to='broiler.broilerfarmshed'),
        ),
    ]
