# Generated by Django 4.2.6 on 2026-07-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_group_warehouse'),
        ('broiler', '0032_broilerbatch_shed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsale',
            name='lifting_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifting_bird_sales', to='hr.employee'),
        ),
    ]
