# Generated by Django 4.2.6 on 2026-07-26 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0033_alter_birdsale_lifting_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPhaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(help_text='Feeding program name, e.g. Cobb 430 Standard', max_length=100)),
                ('bird_type', models.CharField(choices=[('broiler', 'Broiler'), ('layer', 'Layer'), ('breeder', 'Breeder')], default='broiler', max_length=15)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_phase_masters', to='broiler.breed')),
            ],
            options={
                'verbose_name': 'Feed Phase Master',
                'verbose_name_plural': 'Feed Phase Masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedPhaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.PositiveIntegerField(default=1)),
                ('from_age', models.PositiveIntegerField(default=0, help_text='From age in days')),
                ('to_age', models.PositiveIntegerField(default=0, help_text='To age in days')),
                ('feed_phase', models.CharField(help_text='e.g. Pre-Starter, Starter, Grower', max_length=50)),
                ('phase_code', models.CharField(blank=True, help_text='e.g. PS, ST, GR, FN1', max_length=20)),
                ('max_feed_qty', models.DecimalField(decimal_places=3, default=0, help_text='Max feed quantity in Kg', max_digits=12)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='broiler.feedphasemaster')),
            ],
            options={
                'verbose_name': 'Feed Phase Line',
                'verbose_name_plural': 'Feed Phase Lines',
                'ordering': ['seq_no', 'id'],
            },
        ),
    ]
