# Generated by Django 4.2.6 on 2026-07-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('broiler', '0034_feedphasemaster_feedphaseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedphaseline',
            name='feed_phase',
        ),
        migrations.AddField(
            model_name='feedphaseline',
            name='feed_item',
            field=models.ForeignKey(blank=True, help_text='Feed-category item for this phase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_phase_lines', to='inventory.item'),
        ),
    ]
