# Generated by Django 4.2.6 on 2026-07-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('broiler', '0035_remove_feedphaseline_feed_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedphaseline',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Item category — filters the feed item choices', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_phase_lines', to='inventory.itemcategory'),
        ),
        migrations.AlterField(
            model_name='feedphaseline',
            name='feed_item',
            field=models.ForeignKey(blank=True, help_text='Item (of the selected category) for this phase', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feed_phase_lines', to='inventory.item'),
        ),
    ]
