# Generated by Django 4.2.6 on 2026-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0036_feedphaseline_category_alter_feedphaseline_feed_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedphaseline',
            name='to_age',
            field=models.PositiveIntegerField(blank=True, help_text="To age in days — leave blank for 'and above' (open-ended)", null=True),
        ),
    ]
