# Generated by Django 4.2.6 on 2026-07-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0037_alter_feedphaseline_to_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedphaseline',
            name='max_feed_qty',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Max feed per bird for this phase, in Kg', max_digits=12),
        ),
    ]
