# Generated by Django 4.2.6 on 2026-07-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0038_alter_feedphaseline_max_feed_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name, e.g. Broiler', max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bird Category',
                'verbose_name_plural': 'Bird Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
