# Generated by Django 4.2.6 on 2026-07-26 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0040_seed_bird_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='bird_category',
            field=models.ForeignKey(blank=True, help_text='Bird category this breed belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to='broiler.birdcategory'),
        ),
    ]
