# Generated by Django 4.2.6 on 2026-07-26 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0041_breed_bird_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedphasemaster',
            name='bird_category',
            field=models.ForeignKey(blank=True, help_text='Bird category this program is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_phase_masters', to='broiler.birdcategory'),
        ),
    ]
