# Generated by Django 4.2.6 on 2026-07-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0043_feedphase_birdtype_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedphasemaster',
            name='bird_type',
        ),
    ]
