# Generated by Django 4.2.6 on 2026-07-28 15:08

from django.db import migrations, models
import django.db.models.deletion


def dedupe_employee(apps, schema_editor):
    """No employee may map to more than one supervisor once the one-to-one
    constraint is added — keep the earliest supervisor's employee, null the
    duplicates so the AlterField can't fail on existing data."""
    Supervisor = apps.get_model("broiler", "Supervisor")
    seen = set()
    for sup in Supervisor.objects.exclude(employee__isnull=True).order_by("id"):
        if sup.employee_id in seen:
            sup.employee = None
            sup.save(update_fields=["employee"])
        else:
            seen.add(sup.employee_id)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_group_warehouse'),
        ('broiler', '0044_remove_feedphasemaster_bird_type'),
    ]

    operations = [
        migrations.RunPython(dedupe_employee, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='supervisor',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='HR employee record this supervisor is (one-to-one) — name/phone/address are copied from here', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broiler_supervisor_role', to='hr.employee'),
        ),
    ]
