# Generated by Django 4.2.6 on 2026-07-30 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0045_alter_supervisor_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmLocationCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. FLC-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(blank=True, help_text='Decimal degrees, -90 to 90', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, help_text='Decimal degrees, -180 to 180', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.TextField(blank=True, help_text='Address as found on the visit')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_location_captures', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(help_text='Farm this capture belongs to; the farmer comes from it', on_delete=django.db.models.deletion.CASCADE, related_name='location_captures', to='broiler.broilerfarm')),
            ],
            options={
                'verbose_name': 'Farm Location Capture',
                'verbose_name_plural': 'Farm Location Captures',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FarmCaptureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], default='photo', max_length=10)),
                ('file', models.FileField(upload_to='farm/captures/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='broiler.farmlocationcapture')),
                ('farm_image', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_file', to='broiler.broilerfarmimage')),
            ],
            options={
                'verbose_name': 'Farm Capture File',
                'verbose_name_plural': 'Farm Capture Files',
                'ordering': ['id'],
            },
        ),
    ]
