# Generated by Django 4.2.6 on 2026-07-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0046_farmlocationcapture_farmcapturefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcapturefile',
            name='kind',
            field=models.CharField(choices=[('photo', 'Farm Picture'), ('farmer_photo', 'Farmer Photo'), ('pan', 'PAN Card'), ('aadhar_front', 'Aadhar (Front)'), ('aadhar_back', 'Aadhar (Back)'), ('agreement', 'Agreement Copy'), ('cheque_1', 'Security Cheque 1'), ('cheque_2', 'Security Cheque 2'), ('cheque_3', 'Security Cheque 3'), ('cheque_4', 'Security Cheque 4'), ('document', 'Other Document')], default='photo', max_length=20),
        ),
    ]
