# Generated by Django 4.2.6 on 2026-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0047_alter_farmcapturefile_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmlocationcapture',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmlocationcapture',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmlocationcapture',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
