# Generated by Django 4.2.6 on 2026-08-01 20:09

import Hitech_BIMS.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0048_farmlocationcapture_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broilerfarm',
            name='agreement_copy',
            field=models.FileField(blank=True, help_text='Uploaded copy of the agreement', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/agreements/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='cheque_1_file',
            field=models.FileField(blank=True, help_text='Security cheque 1 scan', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/cheques/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='cheque_2_file',
            field=models.FileField(blank=True, help_text='Security cheque 2 scan', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/cheques/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='cheque_3_file',
            field=models.FileField(blank=True, help_text='Security cheque 3 scan', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/cheques/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='cheque_4_file',
            field=models.FileField(blank=True, help_text='Security cheque 4 scan', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/cheques/'),
        ),
        migrations.AlterField(
            model_name='broilerfarm',
            name='other_documents',
            field=models.FileField(blank=True, help_text='Other supporting documents', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/documents/'),
        ),
        migrations.AlterField(
            model_name='farmcapturefile',
            name='file',
            field=models.FileField(storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farm/captures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_upload_back',
            field=models.FileField(blank=True, help_text='Uploaded copy of Aadhar card (back)', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer/aadhar/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_upload_front',
            field=models.FileField(blank=True, help_text='Uploaded copy of Aadhar card (front)', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer/aadhar/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pan_upload',
            field=models.FileField(blank=True, help_text='Uploaded copy of PAN card', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer/pan/'),
        ),
    ]
