# Generated by Django 4.2.6 on 2026-08-04 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0049_alter_broilerfarm_agreement_copy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mortality', 'Mortality'), ('culls', 'Culls'), ('feed', 'Feed')], help_text='What the photo is evidence of', max_length=20)),
                ('image', models.ImageField(help_text='The photograph', upload_to='daily_entry/photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(help_text='Daily Entry this photo evidences', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='broiler.dailyentry')),
            ],
            options={
                'verbose_name': 'Daily Entry Photo',
                'verbose_name_plural': 'Daily Entry Photos',
                'ordering': ['kind', 'id'],
                'indexes': [models.Index(fields=['entry', 'kind'], name='broiler_dai_entry_i_9d527c_idx')],
            },
        ),
    ]
