# Generated by Django 4.2.6 on 2026-08-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0050_dailyentryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerfarm',
            name='farm_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed')], default='active', help_text='Whether the farm is currently in use', max_length=12),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='own_or_lease',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('lease', 'Lease')], help_text='Whether the farmer owns the land or leases it', max_length=10),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='water_ph',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Water pH from the last test', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='water_tds',
            field=models.PositiveIntegerField(blank=True, help_text='Water TDS in ppm from the last test', null=True),
        ),
    ]
