# Generated by Django 4.2.6 on 2026-08-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0051_broilerfarm_farm_status_broilerfarm_own_or_lease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Whether this farmer is currently dealt with', max_length=12),
        ),
    ]
