# Generated by Django 4.2.6 on 2026-08-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0052_farmer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdsale',
            name='lift_latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude where the lifting was recorded', null=True),
        ),
        migrations.AddField(
            model_name='birdsale',
            name='lift_longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude where the lifting was recorded', null=True),
        ),
        migrations.AddField(
            model_name='birdsale',
            name='lift_place',
            field=models.CharField(blank=True, help_text='Human-readable place for the GPS pin', max_length=200),
        ),
        migrations.CreateModel(
            name='BirdSalePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('truck', 'Truck Photo'), ('birds', 'Birds Photo'), ('weighbridge', 'Weighbridge Slip'), ('other', 'Other')], default='other', help_text='What the photo shows', max_length=20)),
                ('image', models.ImageField(help_text='The photograph', upload_to='bird_sale/photos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(help_text='Bird Sale this photo evidences', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='broiler.birdsale')),
            ],
            options={
                'verbose_name': 'Bird Sale Photo',
                'verbose_name_plural': 'Bird Sale Photos',
                'ordering': ['kind', 'id'],
                'indexes': [models.Index(fields=['sale', 'kind'], name='broiler_bir_sale_id_c1401d_idx')],
            },
        ),
    ]
