# Generated by Django 4.2.6 on 2026-08-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0053_birdsale_lift_latitude_birdsale_lift_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsale',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Net weight x Rate, rounded to the rupee', max_digits=14),
        ),
        migrations.AlterField(
            model_name='birdsale',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='What rounding the total to the rupee added or took off', max_digits=8),
        ),
    ]
