# Generated by Django 4.2.6 on 2026-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0054_alter_birdsale_amount_alter_birdsale_round_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentryphoto',
            name='kind',
            field=models.CharField(choices=[('mortality', 'Mortality'), ('culls', 'Culls'), ('feed', 'Feed'), ('feed_2', 'Feed 2')], help_text='What the photo is evidence of', max_length=20),
        ),
    ]
