# Generated by Django 4.2.6 on 2026-08-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0056_batchotherentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingchargescheme',
            name='standard_medicine_cost',
            field=models.DecimalField(decimal_places=2, default=3, help_text="Standard medicine cost per bird shown on the GC Realization Report's Standard column — read regardless of Medicine Cost Basis.", max_digits=12),
        ),
    ]
