# Generated by Django 4.2.6 on 2026-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0057_growingchargescheme_standard_medicine_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingchargescheme',
            name='standard_avg_weight',
            field=models.DecimalField(decimal_places=2, default=2, help_text="Standard avg. live weight per bird (kg) shown on the GC Realization Report's Standard column.", max_digits=12),
        ),
    ]
