# Generated by Django 4.2.6 on 2026-08-10 17:38

import Hitech_BIMS.storage_backends
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0058_growingchargescheme_standard_avg_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerFarmSetupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. FFR-2627-0001', max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Set when the request moves from Draft to Pending', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('gps_accuracy_m', models.FloatField(blank=True, null=True)),
                ('gps_captured_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village_area', models.CharField(blank=True, max_length=100)),
                ('line', models.CharField(blank=True, max_length=100)),
                ('full_address', models.TextField(blank=True)),
                ('farmer_name', models.CharField(blank=True, max_length=150)),
                ('father_spouse_name', models.CharField(blank=True, max_length=150)),
                ('primary_mobile', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('farmer_photo', models.ImageField(blank=True, null=True, upload_to='farmer_farm_requests/photos/')),
                ('farm_name', models.CharField(blank=True, max_length=100)),
                ('farm_type', models.CharField(choices=[('own', 'Own'), ('ec_shed', 'Ec Shed'), ('integration', 'Integration')], default='own', max_length=50)),
                ('capacity_birds', models.PositiveIntegerField(blank=True, null=True)),
                ('shed_type', models.CharField(choices=[('open', 'Open Shed'), ('closed', 'Closed Shed'), ('ec', 'Environmental Controlled')], default='open', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_card', models.CharField(blank=True, max_length=10)),
                ('aadhaar_front', models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer_farm_requests/kyc/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer_farm_requests/kyc/')),
                ('agreement_copy', models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer_farm_requests/kyc/')),
                ('security_cheque', models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer_farm_requests/kyc/')),
                ('physically_verified', models.BooleanField(default=False, help_text='Field supervisor confirms the farmer, farm location and basic farm details have been physically verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch this request was raised for; drives numbering and who can review it', on_delete=django.db.models.deletion.PROTECT, related_name='farmer_farm_setup_requests', to='broiler.branch')),
                ('created_farm', models.ForeignKey(blank=True, help_text='Set on approval — the real BroilerFarm this request became', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setup_requests', to='broiler.broilerfarm')),
                ('created_farmer', models.ForeignKey(blank=True, help_text='Set on approval — the real Farmer this request became', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='setup_requests', to='broiler.farmer')),
                ('farmer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmer_farm_setup_requests', to='broiler.farmergroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmer_farm_setup_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_farm_setup_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer & Farm Setup Request',
                'verbose_name_plural': 'Farmer & Farm Setup Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerFarmSetupRequestShed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to='broiler.farmerfarmsetuprequest')),
            ],
            options={
                'verbose_name': 'Farmer & Farm Setup Request Shed',
                'verbose_name_plural': 'Farmer & Farm Setup Request Sheds',
                'ordering': ['id'],
            },
        ),
    ]
