# Generated by Django 4.2.6 on 2026-08-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0059_farmerfarmsetuprequest_farmerfarmsetuprequestshed'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Who takes ownership of the farm on approval; required to submit, not to draft', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmer_farm_setup_requests', to='broiler.supervisor'),
        ),
    ]
