# Generated by Django 4.2.6 on 2026-08-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0060_farmerfarmsetuprequest_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='acc_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
