# Generated by Django 4.2.6 on 2026-08-11 04:22

import Hitech_BIMS.storage_backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0061_farmerfarmsetuprequest_acc_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='pan_upload',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='farmer_farm_requests/kyc/'),
        ),
        migrations.CreateModel(
            name='FarmerFarmSetupRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='farmer_farm_requests/photos/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='broiler.farmerfarmsetuprequest')),
            ],
            options={
                'verbose_name': 'Farmer & Farm Setup Request Photo',
                'verbose_name_plural': 'Farmer & Farm Setup Request Photos',
                'ordering': ['id'],
            },
        ),
    ]
