# Generated by Django 4.2.6 on 2026-08-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0062_farmerfarmsetuprequest_pan_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfarmsetuprequest',
            name='farmer_address',
            field=models.TextField(blank=True),
        ),
    ]
