# Generated by Django 4.2.6 on 2026-08-11 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0063_farmerfarmsetuprequest_farmer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerfarmsetuprequest',
            name='created_farm',
            field=models.ForeignKey(blank=True, help_text='Set on approval — the real BroilerFarm this request became', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_requests', to='broiler.broilerfarm'),
        ),
        migrations.AlterField(
            model_name='farmerfarmsetuprequest',
            name='created_farmer',
            field=models.ForeignKey(blank=True, help_text='Set on approval — the real Farmer this request became', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_requests', to='broiler.farmer'),
        ),
    ]
