# Generated by Django 4.2.6 on 2026-08-19 15:05

import broiler.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0030_employeevehicle_supervisortrip_supervisortripvisit_and_more'),
        ('broiler', '0064_alter_farmerfarmsetuprequest_created_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(blank=True, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('date', models.DateField(default=broiler.models._route_today)),
                ('start_label', models.CharField(blank=True, max_length=150)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('end_label', models.CharField(blank=True, max_length=150)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('returns_to_start', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('distance', 'Shortest Distance'), ('time', 'Shortest Travel Time'), ('priority', 'Priority Route'), ('supervisor', 'Supervisor Daily Route')], default='distance', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=12)),
                ('distance_basis', models.CharField(choices=[('road', 'Road network'), ('straight', 'Straight line (estimate)')], default='road', max_length=10)),
                ('provider', models.CharField(blank=True, help_text='Routing provider that answered', max_length=40)),
                ('planned_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_minutes', models.PositiveIntegerField(default=0)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_routes', to='broiler.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_routes', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farm_routes', to='broiler.supervisor')),
                ('trip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_route', to='hr.supervisortrip')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy of the GPS reading, in metres', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='location_captured_at',
            field=models.DateField(blank=True, help_text='Date of the location capture this pin came from', null=True),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='location_verified',
            field=models.BooleanField(default=False, help_text='Somebody has confirmed this pin is where the farm is'),
        ),
        migrations.AddField(
            model_name='broilerfarm',
            name='visit_priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', help_text='How urgently this farm needs to be visited', max_length=10),
        ),
        migrations.AddField(
            model_name='farmlocationcapture',
            name='gps_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy of the reading in metres, as the phone reported it', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='FarmRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('start', 'Start'), ('farm', 'Farm'), ('end', 'End')], default='farm', max_length=6)),
                ('label', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('leg_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('leg_minutes', models.PositiveIntegerField(default=0)),
                ('cumulative_distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_minutes', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(blank=True, max_length=10)),
                ('visited_at', models.DateTimeField(blank=True, null=True)),
                ('actual_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='broiler.broilerfarm')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='broiler.farmroute')),
            ],
            options={
                'ordering': ['route_id', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='farmroutestop',
            constraint=models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_route_stop_sequence'),
        ),
        migrations.AddIndex(
            model_name='farmroute',
            index=models.Index(fields=['date', 'supervisor'], name='broiler_far_date_fc5109_idx'),
        ),
    ]
