# Generated by Django 4.2.6 on 2026-08-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0064_alter_farmerfarmsetuprequest_created_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(choices=[('Office Expense Allocation', 'Office Expense Allocation'), ('Accounting Charges', 'Accounting Charges'), ('Depreciation', 'Depreciation'), ('Interest Allocation', 'Interest Allocation'), ('Insurance', 'Insurance')], max_length=64)),
                ('rate_per_bird', models.DecimalField(decimal_places=4, default=0, help_text='Rupees per bird placed', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, help_text='Overrides the branch rate for one flock', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_cost_rates', to='broiler.broilerbatch')),
                ('branch', models.ForeignKey(blank=True, help_text='Applies to every flock of this branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_cost_rates', to='broiler.branch')),
            ],
            options={
                'verbose_name': 'Admin Cost Rate',
                'verbose_name_plural': 'Admin Cost Rates',
            },
        ),
        migrations.AddConstraint(
            model_name='admincostrate',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', True)), fields=('head', 'branch'), name='uniq_admin_rate_branch'),
        ),
        migrations.AddConstraint(
            model_name='admincostrate',
            constraint=models.UniqueConstraint(condition=models.Q(('batch__isnull', False)), fields=('head', 'batch'), name='uniq_admin_rate_batch'),
        ),
    ]
