# Generated by Django 4.2.6 on 2026-08-28 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
        ('broiler', '0066_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerGCPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. FGP-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer GC Payment',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FarmerGCPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('GC Pay', 'GC Pay'), ('Advance', 'Advance'), ('Final Settlement', 'Final Settlement')], default='GC Pay', max_length=20)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('gc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gc_payment_lines', to='broiler.broilerbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gc_payment_lines', to='broiler.broilerfarm')),
                ('pay_account', models.ForeignKey(help_text='The cash or bank account the money leaves', on_delete=django.db.models.deletion.PROTECT, related_name='farmer_gc_payment_lines', to='account.chartofaccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='broiler.farmergcpayment')),
            ],
            options={
                'verbose_name': 'Farmer GC Payment Line',
                'ordering': ['id'],
            },
        ),
    ]
