# Generated by Django 4.2.6 on 2026-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0067_farmergcpayment_farmergcpaymentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmergcpaymentline',
            name='pay_type',
            field=models.CharField(choices=[('GC Pay', 'GC Pay'), ('Advance Pay', 'Advance Pay'), ('Additional Pay', 'Additional Pay')], default='GC Pay', max_length=20),
        ),
    ]
