# Generated by Django 4.2.6 on 2026-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0068_alter_farmergcpaymentline_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPostingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Post growing charges and farmer payments to the ledger')),
                ('cutoff_date', models.DateField(blank=True, help_text='Only documents dated on or after this post. Leave empty to post everything.', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GC Posting Settings',
                'verbose_name_plural': 'GC Posting Settings',
            },
        ),
    ]
