# Generated by Django 4.2.6 on 2026-08-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0069_gcpostingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='growingchargesettlement',
            name='tds_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
