# Generated by Django 4.2.6 on 2026-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0070_growingchargesettlement_tds_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpostingsettings',
            name='cutoff_date',
            field=models.DateField(blank=True, help_text='Only documents dated on or after this post. Settlements from before this system existed are left alone — many sit in financial years that are closed, and posting refuses those by design; bring them in as one reviewed opening journal per farmer. Leaving this empty posts everything, including that history.', null=True),
        ),
        migrations.AlterField(
            model_name='gcpostingsettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Post growing charges and farmer payments to the ledger. While this is off they are recorded but never reach the Chart of Accounts. After switching it on, check Broiler > Reports > Farmer Reconciliation: every farmer should read Agrees.'),
        ),
    ]
