# Generated by Django 4.2.6 on 2026-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0072_broilerfarmshed_unique_shed_unit_no_per_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsalereceipt',
            name='mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmergcpaymentline',
            name='mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
