# Generated by Django 4.2.6 on 2026-09-13 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0073_alter_birdsalereceipt_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdsale',
            name='lifting_supervisor_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
