# Generated by Django 4.2.6 on 2026-09-14 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0074_birdsale_lifting_supervisor_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCSettlementRecalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, help_text='Why it was re-run.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='Null once the account is removed; the entry stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gc_recalculations', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalculations', to='broiler.growingchargesettlement')),
            ],
            options={
                'verbose_name': 'GC settlement recalculation',
                'verbose_name_plural': 'GC settlement recalculations',
                'ordering': ('-created_at',),
            },
        ),
    ]
