# Generated by Django 4.2.6 on 2026-09-21 05:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0078_backfill_location_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='broilerfarmshed',
            name='space_per_bird',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Floor area allowed per bird, in square feet', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
