# Generated by Django 4.2.6 on 2025-01-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the financial year"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of the financial year"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is this the active financial year?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last record update time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the account",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the schedule", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Details about the schedule", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last updated at"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for the account",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the account", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Asset", "Asset"),
                            ("Liability", "Liability"),
                            ("Equity", "Equity"),
                            ("Revenue", "Revenue"),
                            ("Expense", "Expense"),
                        ],
                        help_text="Type of the account",
                        max_length=20,
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        help_text="Control type for the account",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        help_text="Status of the account",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last updated at"),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated schedule",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chart of Account",
                "verbose_name_plural": "Chart of Accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BankCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        help_text="Unique code for the bank", max_length=20, unique=True
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(help_text="Name of the bank", max_length=255),
                ),
                (
                    "micr",
                    models.CharField(
                        blank=True,
                        help_text="MICR code of the bank",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("address", models.TextField(help_text="Address of the bank")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the bank",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the bank",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        help_text="Fax number of the bank",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Contact person at the bank",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last updated at"),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sector of the bank",
                        max_length=20,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Code",
                "verbose_name_plural": "Bank Codes",
                "ordering": ["bank_name"],
            },
        ),
    ]
