# Generated by Django 4.2.6 on 2025-04-03 08:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['code'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterField(
            model_name='bankcode',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the bank', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='bankcode',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector of the bank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banks', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Associated schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='account.schedule'),
        ),
        migrations.AddIndex(
            model_name='bankcode',
            index=models.Index(fields=['bank_code'], name='account_ban_bank_co_8fc8b7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankcode',
            index=models.Index(fields=['bank_name'], name='account_ban_bank_na_74a23a_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['code'], name='account_cha_code_b14595_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['type'], name='account_cha_type_72e4db_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['status'], name='account_cha_status_a07b14_idx'),
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['is_active'], name='account_fin_is_acti_fd53ae_idx'),
        ),
        migrations.AddIndex(
            model_name='financialyear',
            index=models.Index(fields=['start_date', 'end_date'], name='account_fin_start_d_2551a4_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['code'], name='account_sch_code_fa25bd_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['name'], name='account_sch_name_a5f584_idx'),
        ),
    ]
