# Generated by Django 4.2.6 on 2026-07-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_schedule_options_alter_bankcode_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Auto-generated code for this category', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Asset', 'Asset'), ('Capital', 'Capital'), ('Expense', 'Expense'), ('Liability', 'Liability'), ('Revenue', 'Revenue')], help_text='Sector this category belongs to', max_length=20)),
                ('description', models.CharField(help_text='Name of the category', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive categories are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated at')),
            ],
            options={
                'verbose_name': 'CoA Category',
                'verbose_name_plural': 'CoA Categories',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='account_coa_code_6bbdc0_idx'), models.Index(fields=['type'], name='account_coa_type_837dcb_idx')],
            },
        ),
    ]
