# Generated by Django 4.2.6 on 2026-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('party_type', models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer')], default='Customer', max_length=20)),
                ('condition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
