# Generated by Django 4.2.6 on 2026-07-15 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_termsconditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('generate', 'Generate'), ('import', 'Import'), ('opening_balance', 'Opening Balance')], max_length=20)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Account Audit Log',
                'verbose_name_plural': 'Account Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='Seeded groups referenced by templates')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Group',
                'verbose_name_plural': 'Account Groups',
                'ordering': ['account_type__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier, e.g. ASSET', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. Asset', max_length=100, unique=True)),
                ('normal_balance', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=10)),
                ('report', models.CharField(choices=[('BS', 'Balance Sheet'), ('PL', 'Profit & Loss')], help_text='Financial statement this type reports on', max_length=2)),
                ('code_range_start', models.PositiveIntegerField(help_text='Inclusive start of the auto-generated account code range')),
                ('code_range_end', models.PositiveIntegerField(help_text='Inclusive end of the auto-generated account code range')),
                ('is_system', models.BooleanField(default=True, help_text='System types cannot be deleted or renamed')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Account Type',
                'verbose_name_plural': 'Account Types',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CoAGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Running', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Per-step counts of created/skipped accounts')),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CoA Generation Log',
                'verbose_name_plural': 'CoA Generation Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150, unique=True)),
                ('industry', models.CharField(choices=[('General', 'General'), ('Trading', 'Trading'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Distribution', 'Distribution'), ('Poultry', 'Poultry'), ('Hatchery', 'Hatchery'), ('Agriculture', 'Agriculture'), ('Service', 'Service'), ('Hospital', 'Hospital'), ('Construction', 'Construction')], max_length=30)),
                ('country', models.CharField(default='IN', help_text='ISO country code driving tax account generation', max_length=2)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CoA Template',
                'verbose_name_plural': 'CoA Templates',
                'ordering': ['industry', 'template_name'],
            },
        ),
        migrations.CreateModel(
            name='CoATemplateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_group', models.BooleanField(default=False)),
                ('is_postable', models.BooleanField(default=True)),
                ('system_role', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('system_generated', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
            options={
                'verbose_name': 'CoA Template Account',
                'verbose_name_plural': 'CoA Template Accounts',
                'ordering': ['template', 'sort_order', 'account_code'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('Department', 'Department'), ('Warehouse', 'Warehouse'), ('Farm', 'Farm'), ('Project', 'Project'), ('Branch', 'Branch'), ('Vehicle', 'Vehicle'), ('ProductionUnit', 'Production Unit')], default='Department', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_manual_entry',
            field=models.BooleanField(default=True, help_text='Disallow to restrict posting to system modules'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Owning company; every generated account belongs to one company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Group nodes hold children and cannot be posted to'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="Locked records can't be edited or deleted"),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_postable',
            field=models.BooleanField(default=True, help_text='Only postable leaf accounts accept journal lines'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='opening_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=10),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent group account in the tree', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='account.chartofaccount'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='path',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Materialized path of codes from root, e.g. 100000/110000/111000', max_length=255),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='source_content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_accounts', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='system_generated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='system_role',
            field=models.CharField(blank=True, db_index=True, help_text='Machine anchor (e.g. ACCOUNTS_RECEIVABLE) used by auto-ledger and tax engines', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Locked', 'Locked')], default='Open', help_text='Open: postable. Closed: year-end run, reopenable. Locked: no changes allowed.', max_length=10),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='code',
            field=models.CharField(blank=True, help_text='Account code, unique per company; auto-generated when blank', max_length=20),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='description',
            field=models.CharField(help_text='Account name', max_length=255),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Income', 'Income'), ('Expense', 'Expense'), ('COGS', 'Cost Of Goods Sold')], help_text='Legacy flat type; kept in sync with account_type', max_length=20),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['company', 'parent'], name='account_cha_company_bb50ba_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['company', 'system_role'], name='account_cha_company_3ea22d_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['company', 'is_group', 'status'], name='account_cha_company_b61314_idx'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_coa_company_code'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='account.costcenter'),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='account_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_accounts', to='account.accountgroup'),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_accounts', to='account.accounttype'),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.coatemplateaccount'),
        ),
        migrations.AddField(
            model_name='coatemplateaccount',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.coatemplate'),
        ),
        migrations.AddField(
            model_name='coatemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coagenerationlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coa_generation_logs', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='coagenerationlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coagenerationlog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_logs', to='account.coatemplate'),
        ),
        migrations.AddField(
            model_name='accountgroup',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='account.accounttype'),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='account.chartofaccount'),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_audit_logs', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='accountauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='account_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='account.accountgroup'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='account.accounttype'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_costcenter_company_code'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'parent'], name='account_coa_templat_405ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='coatemplateaccount',
            index=models.Index(fields=['template', 'level', 'sort_order'], name='account_coa_templat_9fddd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='coatemplateaccount',
            constraint=models.UniqueConstraint(fields=('template', 'account_code'), name='uniq_template_account_code'),
        ),
        migrations.AddIndex(
            model_name='coatemplate',
            index=models.Index(fields=['industry', 'country', 'status'], name='account_coa_industr_d51bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauditlog',
            index=models.Index(fields=['company', 'timestamp'], name='account_acc_company_e92180_idx'),
        ),
        migrations.AddIndex(
            model_name='accountauditlog',
            index=models.Index(fields=['account', 'timestamp'], name='account_acc_account_38aee5_idx'),
        ),
    ]
