# Generated by Django 4.2.6 on 2026-07-16 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_seed_coa_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('Journal', 'Journal'), ('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Contra', 'Contra'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Opening', 'Opening'), ('Closing', 'Closing')], default='Journal', max_length=10)),
                ('voucher_no', models.CharField(blank=True, editable=False, help_text='Assigned when posted, e.g. JV/2026-27/0001', max_length=30, null=True)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='External document/bill reference', max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=10)),
                ('system_generated', models.BooleanField(default=False, editable=False)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='account.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='account.financialyear')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField(db_index=True, editable=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='account.chartofaccount')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='account.costcenter')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='account.voucher')),
            ],
            options={
                'verbose_name': 'Voucher Line',
                'verbose_name_plural': 'Voucher Lines',
                'ordering': ['voucher', 'line_no'],
                'indexes': [models.Index(fields=['account', 'date'], name='account_vou_account_8dda73_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'date'], name='account_vou_company_f44698_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'voucher_type', 'status'], name='account_vou_company_ccffc3_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['company', 'status', 'date'], name='account_vou_company_d734f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('company', 'financial_year', 'voucher_type', 'voucher_no'), name='uniq_voucher_number'),
        ),
    ]
