# Generated by Django 4.2.6 on 2026-07-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('account', '0008_voucher_voucherline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Office / branch this voucher belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='inventory.warehouse'),
        ),
    ]
