# Generated by Django 4.2.6 on 2026-07-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0009_voucher_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='source_content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='account_vou_source__a15ac4_idx'),
        ),
    ]
