# Generated by Django 4.2.6 on 2026-07-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_voucher_source_content_type_voucher_source_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='auto_narration',
            field=models.TextField(blank=True, help_text='Last narration the auto-narration engine computed, kept even after manual edits'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='narration_edited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='narration_edited_by',
            field=models.ForeignKey(blank=True, editable=False, help_text='User who last overrode the auto-generated narration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='narration_source',
            field=models.CharField(choices=[('AUTO', 'Auto-generated'), ('MANUAL', 'Manually edited')], default='MANUAL', help_text="Whether the saved narration is the engine's text as-is or was hand-edited", max_length=10),
        ),
        migrations.CreateModel(
            name='NarrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master on/off switch for auto narration')),
                ('include_amount', models.BooleanField(default=True, help_text='Mention the amount in generated narration')),
                ('include_reference', models.BooleanField(default=True, help_text='Mention the reference/bill number when present')),
                ('include_party', models.BooleanField(default=True, help_text='Mention the customer/supplier/party ledger name')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Narration Settings',
                'verbose_name_plural': 'Narration Settings',
            },
        ),
    ]
