# Generated by Django 4.2.6 on 2026-07-20 06:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_mapping_remove_warehouse_branch_and_more'),
        ('account', '0012_backfill_expense_ledger_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_code', models.CharField(help_text='Unique code for this cash location', max_length=20, unique=True)),
                ('cash_name', models.CharField(help_text='Name of the cash location', max_length=255)),
                ('address', models.TextField(help_text='Address of the cash location')),
                ('phone', models.CharField(blank=True, help_text='Phone number for this cash location', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_person', models.CharField(blank=True, help_text='Person responsible for this cash location', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated at')),
                ('sector', models.ForeignKey(blank=True, help_text='Sector of the cash location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_locations', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Cash Code',
                'verbose_name_plural': 'Cash Codes',
                'ordering': ['cash_name'],
                'indexes': [models.Index(fields=['cash_code'], name='account_cas_cash_co_ee96b3_idx'), models.Index(fields=['cash_name'], name='account_cas_cash_na_67836a_idx')],
            },
        ),
    ]
