# Generated by Django 4.2.6 on 2026-07-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_bankcashmaster_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. DEPT-0001 / VEH-0001', max_length=20),
        ),
    ]
