# Generated by Django 4.2.6 on 2026-07-20 08:18

import re

from django.db import migrations, models
import django.db.models.deletion


def backfill_branch_cost_centers(apps, schema_editor):
    """Retroactively create a Branch-kind CostCenter for every Branch that
    already existed before this migration — the post_save signal only
    covers Branch saves from here on."""
    Branch = apps.get_model("broiler", "Branch")
    CostCenter = apps.get_model("account", "CostCenter")
    CompanyProfile = apps.get_model("account", "CompanyProfile")

    company = CompanyProfile.objects.filter(pk=1).first()
    if company is None:
        return

    prefix = "BRN-"
    serials = []
    for code in CostCenter.objects.filter(
        company=company, code__startswith=prefix
    ).values_list("code", flat=True):
        match = re.match(rf"^{prefix}(\d+)$", code or "")
        if match:
            serials.append(int(match.group(1)))
    next_serial = max(serials, default=0) + 1

    for branch in Branch.objects.all():
        if CostCenter.objects.filter(branch=branch).exists():
            continue
        CostCenter.objects.create(
            company=company, branch=branch, name=branch.branch_name,
            kind="Branch", is_active=branch.is_active,
            code=f"{prefix}{next_serial:04d}",
        )
        next_serial += 1


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0021_alter_broilerfarm_farm_code'),
        ('account', '0017_alter_costcenter_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='branch',
            field=models.OneToOneField(blank=True, help_text="Broiler Branch this cost center represents — auto-created and kept in sync with the branch's name/active status; see account.signals.branch_cost_center", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center', to='broiler.branch'),
        ),
        migrations.RunPython(backfill_branch_cost_centers, noop),
    ]
