# Generated by Django 4.2.6 on 2026-07-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_levels(apps, schema_editor):
    """AddField defaults every existing row's level to 0 — recompute the
    real depth for rows that already have a parent."""
    CostCenter = apps.get_model("account", "CostCenter")
    parent_of = dict(CostCenter.objects.values_list("id", "parent_id"))

    def depth(cc_id, seen=None):
        seen = seen or set()
        if cc_id in seen or cc_id not in parent_of:
            return 0
        seen.add(cc_id)
        parent_id = parent_of[cc_id]
        return 0 if parent_id is None else depth(parent_id, seen) + 1

    for cc in CostCenter.objects.all():
        level = depth(cc.id)
        if level != cc.level:
            cc.level = level
            cc.save(update_fields=["level"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0021_alter_broilerfarm_farm_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_costcenter_kind_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='approval_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=10),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_locked',
            field=models.BooleanField(default=False, help_text="Locked records can't be edited or deleted"),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Depth in the parent/child hierarchy — 0 for a top-level cost center'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='branch',
            field=models.OneToOneField(blank=True, help_text='Broiler Branch this cost center represents — auto-created the first time the branch is saved; see account.signals.branch_cost_center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center', to='broiler.branch'),
        ),
        migrations.RunPython(backfill_levels, noop),
    ]
