# Generated by Django 4.2.6 on 2026-07-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0020_costcenter_approval_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='allow_children_only',
            field=models.BooleanField(default=False, help_text='Grouping node — only its child cost centers can be selected on a transaction, not this one itself'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='allow_manual_selection',
            field=models.BooleanField(default=True, help_text='Whether users can pick this cost center directly when entering a voucher line'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Fallback cost center auto-applied to a voucher line when Accounting Controls requires one and the line didn't specify one — only one per company"),
        ),
        migrations.CreateModel(
            name='AccountingControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_cost_center', models.BooleanField(default=False, help_text="Every voucher line must carry a cost center — falls back to the Default Cost Centre (see CostCenter.is_default) if a line doesn't specify one, and is rejected at posting if neither is present")),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Control Settings',
                'verbose_name_plural': 'Accounting Control Settings',
            },
        ),
    ]
