# Generated by Django 4.2.6 on 2026-07-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_costcenter_to_organizationcentre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcentre',
            name='allow_children_only',
            field=models.BooleanField(default=False, help_text='Grouping node — only its child centres can be selected on a transaction, not this one itself'),
        ),
        migrations.AlterField(
            model_name='organizationcentre',
            name='allow_manual_selection',
            field=models.BooleanField(default=True, help_text='Whether users can pick this centre directly when entering a voucher line'),
        ),
        migrations.AlterField(
            model_name='organizationcentre',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Fallback centre auto-applied to a voucher line when Accounting Controls requires one and the line didn't specify one — only one per company"),
        ),
        migrations.AlterField(
            model_name='organizationcentre',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Depth in the parent/child hierarchy — 0 for a top-level centre'),
        ),
    ]
