# Generated by Django 4.2.6 on 2026-07-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Auto-generated code, e.g. PM-0001', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Mode name shown in payment/receipt dropdowns', max_length=100, unique=True)),
                ('method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], help_text='Underlying instrument type (optional)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_cash', models.ForeignKey(blank=True, help_text='Bank/Cash Master account this mode maps to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modes', to='account.bankcashmaster')),
            ],
            options={
                'verbose_name': 'Payment Mode',
                'verbose_name_plural': 'Payment Modes',
                'ordering': ['name'],
            },
        ),
    ]
