# Generated by Django 4.2.6 on 2026-07-28 09:56

from django.db import migrations


def seed_modes(apps, schema_editor):
    """Seed the previously-hardcoded instrument modes so existing dropdowns and
    saved rows (mode='Cash', etc.) keep working. No bank/cash mapping yet — the
    user maps them (or adds new ones) from the Payment Mode master."""
    PaymentMode = apps.get_model("account", "PaymentMode")
    for i, name in enumerate(["Cash", "Bank Transfer", "Cheque", "UPI", "Card"], start=1):
        PaymentMode.objects.get_or_create(
            name=name, defaults={"code": f"PM-{i:04d}", "method": name, "is_active": True},
        )


def unseed(apps, schema_editor):
    PaymentMode = apps.get_model("account", "PaymentMode")
    PaymentMode.objects.filter(name__in=["Cash", "Bank Transfer", "Cheque", "UPI", "Card"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_paymentmode'),
    ]

    operations = [
        migrations.RunPython(seed_modes, unseed),
    ]
