# Generated by Django 4.2.6 on 2026-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_seed_payment_modes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmode',
            name='method',
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='bank_cash',
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='bank_cash',
            field=models.ManyToManyField(blank=True, help_text='Bank/Cash Master accounts this mode maps to', related_name='payment_modes', to='account.bankcashmaster'),
        ),
    ]
