# Generated by Django 4.2.6 on 2026-07-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_paymentmode_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmode',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Payment Mode', 'verbose_name_plural': 'Payment Modes'},
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='applicable_for',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Both', 'Both')], default='Both', help_text='Where this mode can be used', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='category',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Bank', help_text='Cash or Bank — filters the Payment Method options', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Preselect this mode on new payments/receipts'),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='bank_cash',
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='bank_cash',
            field=models.ForeignKey(blank=True, help_text='Payment Method — the Bank/Cash Master account this mode maps to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_modes', to='account.bankcashmaster'),
        ),
    ]
