# Generated by Django 4.2.6 on 2026-07-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_paymentmode_options_paymentmode_applicable_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmode',
            name='bank_cash',
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='bank_cash',
            field=models.ManyToManyField(blank=True, help_text='Payment Method — the Bank/Cash Master accounts this mode maps to', related_name='payment_modes', to='account.bankcashmaster'),
        ),
    ]
