# Generated by Django 4.2.6 on 2026-07-28 14:01

from django.db import migrations


def fix_categories(apps, schema_editor):
    """The five seeded modes all defaulted to Category 'Bank' when the field was
    added; a Cash mode should be Category 'Cash' so its Payment Method lists the
    cash accounts."""
    PaymentMode = apps.get_model("account", "PaymentMode")
    PaymentMode.objects.filter(name__iexact="Cash").update(category="Cash")


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_remove_paymentmode_bank_cash_paymentmode_bank_cash'),
    ]

    operations = [
        migrations.RunPython(fix_categories, migrations.RunPython.noop),
    ]
