# Generated by Django 4.2.6 on 2026-07-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_fix_payment_mode_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chartofaccount',
            name='uniq_coa_company_code',
        ),
        migrations.AddConstraint(
            model_name='chartofaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('company', 'code'), name='uniq_coa_company_code'),
        ),
    ]
