# Generated by Django 4.2.6 on 2026-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='category',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Digital Wallet', 'Digital Wallet')], default='Bank', help_text='Cash, Bank or Digital Wallet — filters the Payment Method options (Digital Wallet uses the Bank accounts, same as Bank)', max_length=14),
        ),
    ]
