# Generated by Django 4.2.6 on 2026-09-26 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0038_item_updated_at'),
        ('broiler', '0079_broilerfarmshed_space_per_bird'),
        ('account', '0031_alter_paymentmode_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated, e.g. PE-2026-00001', max_length=30)),
                ('expense_date', models.DateField()),
                ('paid_to_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_to_name', models.CharField(help_text='Who the money went to, as it should read on the voucher', max_length=150)),
                ('reference', models.CharField(blank=True, help_text='Bill or voucher number, where there is one', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Discount or rounding, taken off the total', max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('narration', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Operational labels for searching, comma separated -- never an account', max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='broiler.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_expenses', to='account.companyprofile')),
                ('cost_centre', models.ForeignKey(blank=True, help_text="Defaults to the branch's own centre; carried onto every journal line", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='account.organizationcentre')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='broiler.broilerfarm')),
                ('journal', models.ForeignKey(blank=True, editable=False, help_text='The voucher this expense posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_expenses', to='account.voucher')),
                ('paid_from', models.ForeignKey(help_text='The petty cash or bank account the money left', on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='account.bankcashmaster')),
                ('paid_to_content_type', models.ForeignKey(blank=True, help_text='The master the payee came from, when it came from one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_expense_payees', to='contenttypes.contenttype')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='account.paymentmode')),
                ('posted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='broiler.broilerfarmshed')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Expense',
                'verbose_name_plural': 'Petty Expenses',
                'ordering': ['-expense_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PettyExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(help_text='The expense ledger this line is classified as', on_delete=django.db.models.deletion.PROTECT, related_name='petty_expense_items', to='account.chartofaccount')),
                ('petty_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.pettyexpense')),
                ('uom', models.ForeignKey(blank=True, help_text="Litres, numbers, kilograms -- the ERP's own unit master", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_expense_items', to='inventory.unitofmeasurement')),
            ],
            options={
                'verbose_name': 'Petty Expense Item',
                'verbose_name_plural': 'Petty Expense Items',
                'ordering': ['petty_expense', 'line_no'],
            },
        ),
        migrations.CreateModel(
            name='PettyExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='petty_expenses/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('petty_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.pettyexpense')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Expense Attachment',
                'verbose_name_plural': 'Petty Expense Attachments',
                'ordering': ['petty_expense', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='pettyexpense',
            index=models.Index(fields=['company', 'expense_date'], name='account_pet_company_70f7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='pettyexpense',
            index=models.Index(fields=['company', 'status', 'expense_date'], name='account_pet_company_abb386_idx'),
        ),
        migrations.AddIndex(
            model_name='pettyexpense',
            index=models.Index(fields=['branch', 'expense_date'], name='account_pet_branch__e6010f_idx'),
        ),
        migrations.AddIndex(
            model_name='pettyexpense',
            index=models.Index(fields=['paid_from', 'expense_date'], name='account_pet_paid_fr_8ca584_idx'),
        ),
        migrations.AddConstraint(
            model_name='pettyexpense',
            constraint=models.UniqueConstraint(fields=('company', 'expense_no'), name='uniq_petty_expense_no'),
        ),
    ]
