# Generated by Django 4.2.6 on 2026-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_pettyexpense_pettyexpenseitem_pettyexpenseattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_amount', models.DecimalField(decimal_places=2, default=0, help_text='The float each cash box is meant to hold. Replenishing offers the difference between this and the balance.', max_digits=14)),
                ('low_balance_at', models.DecimalField(decimal_places=2, default=0, help_text='Warn when a cash box falls below this. Zero warns only when the box is empty or overdrawn.', max_digits=14)),
                ('bill_required_above', models.DecimalField(decimal_places=2, default=0, help_text='Refuse to post an expense above this amount with no bill attached. Zero asks for a bill on nothing.', max_digits=14)),
                ('warn_on_duplicates', models.BooleanField(default=True, help_text='Warn when the same payee, date and amount is already on file — the usual sign of one bill entered twice.')),
            ],
            options={
                'verbose_name': 'Petty Cash Policy',
                'verbose_name_plural': 'Petty Cash Policy',
            },
        ),
    ]
