# Generated by Django 4.2.6 on 2026-09-27 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0079_broilerfarmshed_space_per_bird'),
        ('account', '0034_voucher_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettyexpense',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The flock this spend belongs to, where it belongs to one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_expenses', to='broiler.broilerbatch'),
        ),
    ]
