from django.urls import path
from . import views

urlpatterns = [
    path("general-purchase/", views.general_purchase_list, name="general_purchase_list"),
    path("general-purchase/add/", views.create_general_purchase, name="general_purchase_add"),
    path("general-purchase/<int:id>/edit/", views.edit_general_purchase, name="general_purchase_edit"),
    path("general-purchase/<int:id>/delete/", views.delete_general_purchase, name="general_purchase_delete"),
    path("general_purchase_api/", views.general_purchase_api_list, name="general_purchase_api_list"),
    path("chicks-purchase/", views.chicks_purchase_list, name="chicks_purchase_list"),
    path("chicks-purchase/add/", views.create_chicks_purchase, name="chicks_purchase_add"),
    path("chicks-purchase/<int:id>/edit/", views.edit_chicks_purchase, name="chicks_purchase_edit"),
    path("chicks-purchase/<int:id>/delete/", views.delete_chicks_purchase, name="chicks_purchase_delete"),
    path("chicks_purchase_api/", views.chicks_purchase_api_list, name="chicks_purchase_api_list"),
    path("payment/", views.payment_list, name="payment_list"),
    path("payment/add/", views.create_payment, name="payment_add"),
    path("payment/<int:id>/edit/", views.edit_payment, name="payment_edit"),
    path("payment/<int:id>/delete/", views.delete_payment, name="payment_delete"),
    path("payment_api/", views.payment_api_list, name="payment_api_list"),
    path("supplier/", views.supplier, name="supplier"),
    path('supplier/add/', views.create_supplier, name='supplier_add'),
    path('supplier/<int:id>/edit/', views.edit_supplier, name='supplier_edit'),
    path('supplier/<int:id>/delete/', views.delete_supplier, name='supplier_delete'),
    path('supplier/<int:supplier_id>/shipping-addresses/', views.SupplierShippingAddressAPI.as_view(), name='supplier_shipping_address_list'),
    path('supplier/<int:supplier_id>/shipping-addresses/<int:id>/', views.SupplierShippingAddressAPI.as_view(), name='supplier_shipping_address_detail'),
    path("vendor_groups/", views.vendor_groups, name="vendor_groups"),
    path('vendor_group/', views.VendorGroupAPI.as_view(), name='vendor_group_list'),
    path('vendor_group/create/', views.VendorGroupAPI.as_view(), name='vendor_group_create'),
    path('vendor_group/<int:id>/', views.VendorGroupAPI.as_view(), name='vendor_group_update'),
    path('vendor_group/<int:id>/delete/', views.VendorGroupAPI.as_view(), name='vendor_group_delete'),
    path("tax_master/", views.tax_master, name="tax_master"),
    path('tax_masters/', views.TaxMasterAPI.as_view(), name='tax_master_list'),
    path('tax_master/create/', views.TaxMasterAPI.as_view(), name='tax_master_create'),
    path('tax_master/<int:id>/', views.TaxMasterAPI.as_view(), name='tax_master_update'),
    path('tax_master/delete/<int:id>/delete/', views.TaxMasterAPI.as_view(), name='tax_master_delete'),
]
