"""Django admin for alerts + audit logs.

Uses ``django-import-export`` (already a project dependency) for CSV/XLSX
export straight from the changelist. The audit log is registered read-only to
preserve its append-only contract in the UI as well as the model layer.
"""
from __future__ import annotations

from django.contrib import admin
from import_export.admin import ExportMixin
from import_export.resources import ModelResource

from .models import Alert, AuditLog


class AlertResource(ModelResource):
    class Meta:
        model = Alert
        fields = (
            "id",
            "created_at",
            "severity",
            "event_type",
            "action",
            "model_name",
            "object_id",
            "object_display",
            "title",
            "actor_label",
            "ip_address",
            "is_read",
        )


class AuditLogResource(ModelResource):
    class Meta:
        model = AuditLog
        fields = (
            "id",
            "created_at",
            "action",
            "event_type",
            "model_name",
            "object_id",
            "object_display",
            "actor_label",
            "reason",
            "ip_address",
        )


@admin.register(Alert)
class AlertAdmin(ExportMixin, admin.ModelAdmin):
    resource_classes = [AlertResource]
    date_hierarchy = "created_at"
    list_display = (
        "created_at",
        "severity",
        "event_type",
        "action",
        "model_name",
        "object_display",
        "actor_label",
        "is_read",
    )
    list_filter = ("severity", "action", "event_type", "is_read", "created_at")
    search_fields = ("title", "message", "object_display", "actor_label", "object_id")
    readonly_fields = tuple(f.name for f in Alert._meta.fields)
    list_select_related = ("performed_by",)
    actions = ("mark_selected_read",)

    @admin.action(description="Mark selected alerts as read")
    def mark_selected_read(self, request, queryset):
        from django.utils import timezone

        updated = queryset.update(is_read=True, read_at=timezone.now())
        self.message_user(request, f"{updated} alert(s) marked read.")

    def has_add_permission(self, request):
        return False  # alerts are generated by the system, never hand-authored


@admin.register(AuditLog)
class AuditLogAdmin(ExportMixin, admin.ModelAdmin):
    resource_classes = [AuditLogResource]
    date_hierarchy = "created_at"
    list_display = (
        "created_at",
        "action",
        "event_type",
        "model_name",
        "object_display",
        "actor_label",
        "reason",
    )
    list_filter = ("action", "event_type", "model_name", "created_at")
    search_fields = ("object_display", "actor_label", "reason", "object_id")
    readonly_fields = tuple(f.name for f in AuditLog._meta.fields)
    list_select_related = ("performed_by",)

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False  # immutable

    def has_delete_permission(self, request, obj=None):
        return False  # immutable
