# Generated by Django 4.2.6 on 2026-07-31 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0048_farmlocationcapture_area_and_more'),
        ('inventory', '0035_stocktransfer_source_supplier'),
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this watch is called in the config list, e.g. 'High mortality — broiler supervisors'.", max_length=150)),
                ('rule_key', models.CharField(choices=[('Production', [('production.high_mortality', 'High Mortality'), ('production.cumulative_mortality', 'Cumulative Mortality Exceeds %'), ('production.low_body_weight', 'Low Body Weight'), ('production.poor_fcr', 'Poor FCR'), ('production.poor_cfcr', 'Poor CFCR'), ('production.low_eef', 'Low EEF'), ('production.placement_pending', 'Placement Pending'), ('production.dispatch_pending', 'Dispatch Pending'), ('production.bird_age', 'Bird Age Alert'), ('production.harvest_due', 'Harvest Due')]), ('Feed', [('feed.low_feed_stock', 'Low Feed Stock'), ('feed.consumption_above_standard', 'Feed Consumption exceeds Standard'), ('feed.transfer_pending', 'Feed Transfer Pending (needs data source)'), ('feed.production_pending', 'Feed Production Pending (needs data source)'), ('feed.dispatch_delayed', 'Feed Dispatch Delayed (needs data source)'), ('feed.purchase_pending', 'Feed Purchase Pending (needs data source)')]), ('Hatchery', [('hatchery.egg_setting_due', 'Egg Setting Due'), ('hatchery.candling_due', 'Candling Due (needs data source)'), ('hatchery.transfer_due', 'Transfer Due'), ('hatchery.hatching_due', 'Hatching Due'), ('hatchery.poor_hatchability', 'Poor Hatchability'), ('hatchery.low_chick_output', 'Low Chick Output'), ('hatchery.high_reject', 'High Reject %')]), ('Health', [('health.vaccination_due', 'Vaccination Due (needs data source)'), ('health.vaccination_overdue', 'Vaccination Overdue (needs data source)'), ('health.medicine_stock_low', 'Medicine Stock Low'), ('health.medicine_expired', 'Medicine Expired'), ('health.medicine_expiring', 'Medicine Expiring Soon'), ('health.disease_alert', 'Disease Alert'), ('health.lab_report_pending', 'Lab Report Pending (needs data source)'), ('health.vet_visit_due', 'Vet Visit Due (needs data source)')]), ('Inventory', [('inventory.low_stock', 'Low Stock'), ('inventory.negative_stock', 'Negative Stock'), ('inventory.reorder_level', 'Reorder Level Crossed (needs data source)'), ('inventory.verification_due', 'Stock Verification Due (needs data source)'), ('inventory.item_expired', 'Item Expired'), ('inventory.item_near_expiry', 'Item Near Expiry'), ('inventory.transfer_pending', 'Warehouse Transfer Pending (needs data source)')]), ('Purchase', [('purchase.order_pending', 'Purchase Order Pending (needs data source)'), ('purchase.grn_pending', 'GRN Pending (needs data source)'), ('purchase.supplier_invoice_pending', 'Supplier Invoice Pending (needs data source)'), ('purchase.approval_pending', 'Purchase Approval Pending (needs data source)'), ('purchase.rate_difference', 'Rate Difference'), ('purchase.duplicate_invoice', 'Duplicate Invoice')]), ('Sales', [('sales.order_pending', 'Sales Order Pending (needs data source)'), ('sales.dispatch_pending', 'Dispatch Pending (needs data source)'), ('sales.invoice_pending', 'Invoice Pending (needs data source)'), ('sales.payment_pending', 'Payment Pending'), ('sales.credit_limit_exceeded', 'Credit Limit Exceeded'), ('sales.overdue_customer', 'Overdue Customer')]), ('Finance', [('finance.payment_due', 'Payment Due'), ('finance.receivable_overdue', 'Receivable Overdue'), ('finance.cheque_bounce', 'Cheque Bounce (needs data source)'), ('finance.journal_approval_pending', 'Journal Approval Pending'), ('finance.bank_reconciliation_pending', 'Bank Reconciliation Pending (needs data source)'), ('finance.cash_balance_low', 'Cash Balance Low (needs data source)'), ('finance.budget_exceeded', 'Cost Centre Budget Exceeded (needs data source)')]), ('HR', [('hr.attendance_missing', 'Attendance Missing'), ('hr.leave_approval_pending', 'Leave Approval Pending'), ('hr.salary_processing_due', 'Salary Processing Due'), ('hr.document_expired', 'Employee Document Expired (needs data source)'), ('hr.contract_renewal', 'Contract Renewal (needs data source)')]), ('System', [('system.backup_failed', 'Backup Failed (needs data source)'), ('system.license_expiry', 'License Expiry (needs data source)'), ('system.storage_low', 'Database Storage Low'), ('system.login_failed', 'Login Failed'), ('system.unauthorized_login', 'Unauthorized Login'), ('system.server_offline', 'Server Offline (needs data source)'), ('system.api_failure', 'API Failure (needs data source)')])], db_index=True, help_text='Which catalogued alert this configures.', max_length=64)),
                ('module', models.CharField(blank=True, choices=[('production', 'Production'), ('feed', 'Feed'), ('hatchery', 'Hatchery'), ('health', 'Health'), ('inventory', 'Inventory'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'HR'), ('system', 'System')], db_index=True, help_text='Derived from the rule key on save; stored so the list can filter and group without loading the catalogue.', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('threshold', models.DecimalField(blank=True, decimal_places=3, help_text='The number the measured value is compared against. Leave blank for rules that have no threshold (e.g. Negative Stock).', max_digits=14, null=True)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('eq', 'Equal to')], default='gte', help_text='How the measured value is compared with the threshold.', max_length=4)),
                ('via_in_app', models.BooleanField(default=True, verbose_name='In-App')),
                ('via_email', models.BooleanField(default=False, verbose_name='Email')),
                ('via_sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('via_whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Disabled rules are kept and simply never evaluated.')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, help_text='Do not raise the same alert for the same subject again within this many hours. 0 raises it on every scan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules_created', to=settings.AUTH_USER_MODEL)),
                ('notify_branches', models.ManyToManyField(blank=True, help_text='Restrict this rule to these branches. Empty means all.', related_name='alert_rules', to='broiler.branch')),
                ('notify_farms', models.ManyToManyField(blank=True, help_text='Restrict to these farms. Empty means all.', related_name='alert_rules', to='broiler.broilerfarm')),
                ('notify_groups', models.ManyToManyField(blank=True, help_text='User Access Groups to notify. Empty means every group whose data scope overlaps the alert.', related_name='alert_rules', to='auth.group')),
                ('notify_org_centres', models.ManyToManyField(blank=True, help_text='Restrict to these organization / cost centres. Empty = all.', related_name='alert_rules', to='account.organizationcentre')),
                ('notify_warehouses', models.ManyToManyField(blank=True, help_text='Restrict to these warehouses / offices. Empty means all.', related_name='alert_rules', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Alert Configuration',
                'verbose_name_plural': 'Alert Configuration',
                'ordering': ('module', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(db_index=True, max_length=64)),
                ('module', models.CharField(choices=[('production', 'Production'), ('feed', 'Feed'), ('hatchery', 'Hatchery'), ('health', 'Health'), ('inventory', 'Inventory'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'HR'), ('system', 'System')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('object_label', models.CharField(blank=True, db_index=True, help_text="app_label.ModelName of the subject, e.g. 'broiler.BroilerBatch'.", max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_display', models.CharField(blank=True, max_length=255)),
                ('voucher_no', models.CharField(blank=True, max_length=60)),
                ('action_url', models.CharField(blank=True, help_text='Where the View button goes. Blank hides the button.', max_length=300)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='broiler.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='Null for scanner-raised alerts, which is most of them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_raised', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='broiler.broilerfarm')),
                ('org_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='account.organizationcentre')),
                ('rule', models.ForeignKey(blank=True, help_text='The configuration that raised this. Null once that rule is deleted — the alert itself stays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alerthub.alertrule')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_in_app', models.BooleanField(default=True, help_text='Show alerts in the bell and notification centre.', verbose_name='Receive In-App')),
                ('receive_email', models.BooleanField(default=False, verbose_name='Receive Email')),
                ('receive_sms', models.BooleanField(default=False, verbose_name='Receive SMS')),
                ('receive_whatsapp', models.BooleanField(default=False, verbose_name='Receive WhatsApp')),
                ('sound_notification', models.BooleanField(default=False, help_text='Play a short tone when a new alert arrives.', verbose_name='Sound Notification')),
                ('desktop_notification', models.BooleanField(default=False, help_text="Use the browser's notification popup. Needs permission.", verbose_name='Desktop Notification')),
                ('auto_mark_read', models.BooleanField(default=False, help_text='Mark alerts read as soon as they are shown in the bell.', verbose_name='Auto Mark Read')),
                ('min_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', help_text='Hide anything less urgent than this. Low shows everything.', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_channels', models.JSONField(blank=True, default=list, help_text='Channels this actually went out on.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='alerthub.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification recipient',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='alerthub_no_user_id_58578b_idx')],
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['rule_key', '-created_at'], name='alerthub_no_rule_ke_df93f1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='alerthub_no_priorit_1817bf_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['dedupe_key', '-created_at'], name='alerthub_no_dedupe__63c98e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['module', '-created_at'], name='alerthub_no_module_d66d42_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['is_active', 'rule_key'], name='alerthub_al_is_acti_c8c8ff_idx'),
        ),
    ]
