# Generated by Django 4.2.6 on 2026-08-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerthub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='receive_push',
            field=models.BooleanField(default=True, help_text="Send alerts to this user's phone when the app is closed.", verbose_name='Receive Mobile Push'),
        ),
    ]
