# Generated by Django 4.2.6 on 2026-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerthub', '0002_notificationpreference_receive_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='via_push',
            field=models.BooleanField(default=False, help_text="Send to the recipients' phones through the Hitech BIMS app.", verbose_name='Mobile Push'),
        ),
    ]
