# Generated by Django 4.2.6 on 2026-08-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerthub', '0003_alertrule_via_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='is_dismissed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
