# Generated by Django 4.2.6 on 2026-08-09 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
        ('hr', '0030_employeevehicle_supervisortrip_supervisortripvisit_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0035_stocktransfer_source_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0055_alter_dailyentryphoto_kind'),
        ('alerthub', '0004_notificationrecipient_dismissed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional PDF/image/document sent with the message.', null=True, upload_to='alerthub/attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, choices=[('mortality', 'Mortality'), ('feed', 'Feed'), ('medicine', 'Medicine'), ('vaccination', 'Vaccination'), ('weight', 'Weight & FCR'), ('stock', 'Stock'), ('dispatch', 'Dispatch'), ('payment', 'Payment'), ('approval', 'Approval'), ('attendance', 'Attendance'), ('maintenance', 'Maintenance'), ('announcement', 'Announcement'), ('general', 'General')], db_index=True, help_text='What it is about, one level below module. Set on messages composed by hand; blank on rule-raised alerts, which are already identified by their rule key.', max_length=20),
        ),
        migrations.CreateModel(
            name='OutgoingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('general', 'General Notification'), ('production', 'Production Alert'), ('mortality', 'Mortality Alert'), ('feed', 'Feed Alert'), ('medicine', 'Medicine / Veterinary'), ('vaccination', 'Vaccination'), ('hatchery', 'Hatchery'), ('inventory', 'Inventory'), ('purchase', 'Purchase'), ('sales', 'Sales / Dispatch'), ('finance', 'Finance'), ('hr', 'HR'), ('attendance', 'Attendance'), ('system', 'System')], default='general', help_text='What kind of message this is. Module and category are derived from it on save.', max_length=20)),
                ('module', models.CharField(choices=[('production', 'Production'), ('feed', 'Feed'), ('hatchery', 'Hatchery'), ('health', 'Health'), ('inventory', 'Inventory'), ('purchase', 'Purchase'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'HR'), ('system', 'System')], default='system', help_text='Derived from the type; stored so the history can filter without re-deriving.', max_length=20)),
                ('category', models.CharField(choices=[('mortality', 'Mortality'), ('feed', 'Feed'), ('medicine', 'Medicine'), ('vaccination', 'Vaccination'), ('weight', 'Weight & FCR'), ('stock', 'Stock'), ('dispatch', 'Dispatch'), ('payment', 'Payment'), ('approval', 'Approval'), ('attendance', 'Attendance'), ('maintenance', 'Maintenance'), ('announcement', 'Announcement'), ('general', 'General')], default='general', help_text='Suggested by the type and editable — a production alert may legitimately be about weights rather than mortality.', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='alerthub/attachments/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=10)),
                ('send_at', models.DateTimeField(blank=True, db_index=True, help_text='When a scheduled message is due. Null means send now.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='broiler.branch')),
                ('companies', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='account.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_notifications_created', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='hr.department')),
                ('designations', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='hr.designation')),
                ('farms', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='broiler.broilerfarm')),
                ('groups', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='auth.group')),
                ('notification', models.OneToOneField(blank=True, help_text='What this became once it went out.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing', to='alerthub.notification')),
                ('users', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(blank=True, related_name='outgoing_notifications', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Outgoing notification',
                'verbose_name_plural': 'Outgoing notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'send_at'], name='alerthub_ou_status_86edc6_idx'), models.Index(fields=['created_by', '-created_at'], name='alerthub_ou_created_41427e_idx')],
            },
        ),
    ]
