# Generated by Django 4.2.6 on 2026-09-12 17:25

from django.db import migrations, models


def turn_them_on(apps, schema_editor):
    """Switch the two on for the rows that already exist.

    A changed default only reaches rows created after it, so without this the
    people already using the system stay silent — which is the whole of the
    problem being fixed. Rows carry no record of having been visited, so this
    cannot tell a deliberate "off" from an untouched default; on the database
    this was written against every row but one held the untouched default, and
    anyone who does want silence can set it again on the settings page.
    """
    (apps.get_model("alerthub", "NotificationPreference").objects
     .filter(models.Q(sound_notification=False) | models.Q(desktop_notification=False))
     .update(sound_notification=True, desktop_notification=True))


def leave_them(apps, schema_editor):
    """Nothing to undo: the column defaults go back on their own, and turning
    everyone's notifications off again would be a change of its own."""


class Migration(migrations.Migration):

    dependencies = [
        ('alerthub', '0005_notification_attachment_notification_category_and_more'),
    ]

    operations = [
        migrations.RunPython(turn_them_on, leave_them),
        migrations.AlterField(
            model_name='notificationpreference',
            name='desktop_notification',
            field=models.BooleanField(default=True, help_text="Use the browser's notification popup. Needs permission.", verbose_name='Desktop Notification'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='sound_notification',
            field=models.BooleanField(default=True, help_text='Play a short tone when a new alert arrives.', verbose_name='Sound Notification'),
        ),
    ]
