# Generated by Django 4.2.6 on 2026-09-12 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerthub', '0006_alter_notificationpreference_desktop_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('started', 'Work started'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('reopened', 'Reopened'), ('notified', 'Supervisor notified')], db_index=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=14)),
                ('to_status', models.CharField(blank=True, max_length=14)),
                ('notified', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Alert action',
                'verbose_name_plural': 'Alert actions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='dismiss_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=14),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_actioned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='rule_key',
            field=models.CharField(choices=[('Production', [('production.high_mortality', 'High Mortality'), ('production.cumulative_mortality', 'Cumulative Mortality Exceeds %'), ('production.low_body_weight', 'Low Body Weight'), ('production.poor_fcr', 'Poor FCR'), ('production.poor_cfcr', 'Poor CFCR'), ('production.low_eef', 'Low EEF'), ('production.daily_entry_missing', 'Daily Entry Missing'), ('production.batch_not_started', 'Batch Not Started'), ('production.placement_pending', 'Placement Pending'), ('production.dispatch_pending', 'Dispatch Pending'), ('production.bird_age', 'Bird Age Alert'), ('production.harvest_due', 'Harvest Due')]), ('Feed', [('feed.stock_coverage_days', 'Feed Stock Coverage Low'), ('feed.low_feed_stock', 'Low Feed Stock'), ('feed.consumption_above_standard', 'Feed Consumption exceeds Standard'), ('feed.transfer_pending', 'Feed Transfer Pending (needs data source)'), ('feed.production_pending', 'Feed Production Pending (needs data source)'), ('feed.dispatch_delayed', 'Feed Dispatch Delayed (needs data source)'), ('feed.purchase_pending', 'Feed Purchase Pending (needs data source)')]), ('Hatchery', [('hatchery.egg_setting_due', 'Egg Setting Due'), ('hatchery.candling_due', 'Candling Due (needs data source)'), ('hatchery.transfer_due', 'Transfer Due'), ('hatchery.hatching_due', 'Hatching Due'), ('hatchery.poor_hatchability', 'Poor Hatchability'), ('hatchery.low_chick_output', 'Low Chick Output'), ('hatchery.high_reject', 'High Reject %')]), ('Health', [('health.vaccination_due', 'Vaccination Due (needs data source)'), ('health.vaccination_overdue', 'Vaccination Overdue (needs data source)'), ('health.medicine_stock_low', 'Medicine Stock Low'), ('health.medicine_expired', 'Medicine Expired'), ('health.medicine_expiring', 'Medicine Expiring Soon'), ('health.disease_alert', 'Disease Alert'), ('health.lab_report_pending', 'Lab Report Pending (needs data source)'), ('health.vet_visit_due', 'Vet Visit Due (needs data source)')]), ('Inventory', [('inventory.low_stock', 'Low Stock'), ('inventory.negative_stock', 'Negative Stock'), ('inventory.reorder_level', 'Reorder Level Crossed (needs data source)'), ('inventory.verification_due', 'Stock Verification Due (needs data source)'), ('inventory.item_expired', 'Item Expired'), ('inventory.item_near_expiry', 'Item Near Expiry'), ('inventory.transfer_pending', 'Warehouse Transfer Pending (needs data source)')]), ('Purchase', [('purchase.order_pending', 'Purchase Order Pending (needs data source)'), ('purchase.grn_pending', 'GRN Pending (needs data source)'), ('purchase.supplier_invoice_pending', 'Supplier Invoice Pending (needs data source)'), ('purchase.approval_pending', 'Purchase Approval Pending (needs data source)'), ('purchase.rate_difference', 'Rate Difference'), ('purchase.duplicate_invoice', 'Duplicate Invoice')]), ('Sales', [('sales.order_pending', 'Sales Order Pending (needs data source)'), ('sales.dispatch_pending', 'Dispatch Pending (needs data source)'), ('sales.invoice_pending', 'Invoice Pending (needs data source)'), ('sales.payment_pending', 'Payment Pending'), ('sales.credit_limit_exceeded', 'Credit Limit Exceeded'), ('sales.overdue_customer', 'Overdue Customer')]), ('Finance', [('finance.payment_due', 'Payment Due'), ('finance.receivable_overdue', 'Receivable Overdue'), ('finance.cheque_bounce', 'Cheque Bounce (needs data source)'), ('finance.journal_approval_pending', 'Journal Approval Pending'), ('finance.bank_reconciliation_pending', 'Bank Reconciliation Pending (needs data source)'), ('finance.cash_balance_low', 'Cash Balance Low (needs data source)'), ('finance.budget_exceeded', 'Cost Centre Budget Exceeded (needs data source)')]), ('HR', [('hr.attendance_missing', 'Attendance Missing'), ('hr.leave_approval_pending', 'Leave Approval Pending'), ('hr.salary_processing_due', 'Salary Processing Due'), ('hr.document_expired', 'Employee Document Expired (needs data source)'), ('hr.contract_renewal', 'Contract Renewal (needs data source)')]), ('System', [('system.backup_failed', 'Backup Failed (needs data source)'), ('system.license_expiry', 'License Expiry (needs data source)'), ('system.storage_low', 'Database Storage Low'), ('system.login_failed', 'Login Failed'), ('system.unauthorized_login', 'Unauthorized Login'), ('system.server_offline', 'Server Offline (needs data source)'), ('system.api_failure', 'API Failure (needs data source)')])], db_index=True, help_text='Which catalogued alert this configures.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', '-created_at'], name='alerthub_no_status_9d2017_idx'),
        ),
        migrations.AddField(
            model_name='alertaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertaction',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='alerthub.notification'),
        ),
        migrations.AddIndex(
            model_name='alertaction',
            index=models.Index(fields=['notification', '-created_at'], name='alerthub_al_notific_e258e3_idx'),
        ),
    ]
