# Generated by Django 4.2.6 on 2026-09-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerthub', '0007_alertaction_notification_dismiss_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_handed_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertaction',
            name='action',
            field=models.CharField(choices=[('acknowledged', 'Acknowledged'), ('started', 'Work started'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('reopened', 'Reopened'), ('notified', 'Supervisor notified'), ('assigned', 'Assigned'), ('unassigned', 'Assignment cleared')], db_index=True, max_length=16),
        ),
    ]
