# Generated by Django 4.2.6 on 2026-09-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerthub', '0008_notification_assigned_at_notification_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertaction',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Alert action', 'verbose_name_plural': 'Alert actions'},
        ),
    ]
