# Generated by Django 4.2.6 on 2026-07-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier used in code, e.g. 'user.otp'.", max_length=100, unique=True)),
                ('module', models.CharField(choices=[('user', 'User'), ('broiler', 'Broiler'), ('hatchery', 'Hatchery'), ('hr', 'HR'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('account', 'Account'), ('inventory', 'Inventory')], db_index=True, help_text='Application module this template belongs to.', max_length=30)),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=150)),
                ('body', models.TextField(help_text="Message text. Use {placeholder} tokens, e.g. 'Your OTP is {otp}'.")),
                ('description', models.CharField(blank=True, help_text='What this template is used for.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates fall back to the built-in default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS template',
                'verbose_name_plural': 'SMS templates',
                'ordering': ('module', 'key'),
            },
        ),
    ]
