# Generated by Django 4.2.6 on 2026-07-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='dlt_template_id',
            field=models.CharField(blank=True, help_text='DLT content template ID for this exact text (Indian traffic). Overrides the global SMS_GATEWAYHUB_DLT_TEMPLATE_ID when set.', max_length=64),
        ),
    ]
