# Generated by Django 4.2.6 on 2026-07-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_smstemplate_dlt_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='category',
            field=models.CharField(db_index=True, default='general', help_text='Business category (invoice, dispatch, payment reminder, ...).', max_length=30),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sms_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_sms_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='sender_id',
            field=models.CharField(blank=True, help_text='Overrides the global sender ID when set.', max_length=10),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='sms_type',
            field=models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional')], default='transactional', max_length=15),
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('module', models.CharField(blank=True, help_text="Document source key, e.g. 'sales'.", max_length=30)),
                ('document_no', models.CharField(blank=True, max_length=50)),
                ('template_name', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('sms_parts', models.PositiveIntegerField(default=1)),
                ('is_unicode', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('accepted', 'Accepted'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('disabled', 'Disabled'), ('mocked', 'Mocked'), ('unknown', 'Unknown')], db_index=True, default='queued', max_length=10)),
                ('gateway_message_id', models.CharField(blank=True, max_length=100)),
                ('gateway_status', models.CharField(blank=True, max_length=50)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('api_request', models.JSONField(blank=True, help_text='Sanitized request context (no secrets).', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='notification.smsmessage')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notification.smstemplate')),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['mobile', 'created_at'], name='notificatio_mobile_15aa23_idx'), models.Index(fields=['module', 'document_no'], name='notificatio_module_b560a7_idx')],
            },
        ),
    ]
