# Generated by Django 4.2.6 on 2026-07-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0003_smstemplate_category_smstemplate_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for all SMS sending.')),
                ('mock', models.BooleanField(default=True, help_text='Mock mode: log sends without hitting the gateway.')),
                ('sender_id', models.CharField(blank=True, help_text='DLT-approved sender/header, e.g. HTFARM.', max_length=10)),
                ('api_key', models.CharField(blank=True, help_text='SMSGatewayHub API key (blank = use .env).', max_length=200)),
                ('entity_id', models.CharField(blank=True, help_text='DLT principal entity ID.', max_length=30)),
                ('default_country_code', models.CharField(default='91', max_length=5)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Settings',
                'verbose_name_plural': 'SMS Settings',
            },
        ),
    ]
