# Generated by Django 4.2.6 on 2026-07-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_smssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='transaction',
            field=models.CharField(blank=True, db_index=True, help_text='Sub-transaction within the module (see SMS_MODULE_TRANSACTIONS); blank = generic template for the whole module.', max_length=50),
        ),
    ]
