# Generated by Django 4.2.6 on 2026-08-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='party_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('farmer', 'Farmer'), ('employee', 'Employee')], max_length=10),
        ),
    ]
