# Generated by Django 4.2.6 on 2026-10-07 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0007_alter_smsmessage_party_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Stable identifier used in code, e.g. 'sales.payment_receipt'.", max_length=100, unique=True)),
                ('module', models.CharField(choices=[('user', 'User'), ('broiler', 'Broiler'), ('hatchery', 'Hatchery'), ('hr', 'HR'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('account', 'Account'), ('inventory', 'Inventory')], db_index=True, help_text='Application module this template belongs to.', max_length=30)),
                ('transaction', models.CharField(blank=True, db_index=True, help_text='Sub-transaction within the module (see SMS_MODULE_TRANSACTIONS); blank = generic template for the whole module.', max_length=50)),
                ('name', models.CharField(help_text='Human-readable template name.', max_length=150)),
                ('template_name', models.CharField(help_text="The exact, Meta-approved template name (lowercase/digits/underscores), e.g. 'order_confirmation'.", max_length=512)),
                ('language', models.CharField(default='en_US', help_text='Template language code, e.g. en_US, en, hi.', max_length=10)),
                ('parameter_map', models.JSONField(blank=True, default=list, help_text='Ordered list of ERP variable names, one per {{1}}, {{2}}... body position, e.g. ["CustomerName", "InvoiceNo", "Amount"].')),
                ('header_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='none', help_text="Media type of the template's header component, if any.", max_length=10)),
                ('header_media_url', models.URLField(blank=True, help_text='Publicly accessible URL for an image/video/document header (must match what the template was approved with).')),
                ('description', models.CharField(blank=True, help_text='What this template is used for.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates cannot be sent.')),
                ('category', models.CharField(db_index=True, default='general', help_text='Business category (invoice, dispatch, payment reminder, ...).', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whatsapp_templates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_whatsapp_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp template',
                'verbose_name_plural': 'WhatsApp templates',
                'ordering': ('module', 'key'),
            },
        ),
        migrations.CreateModel(
            name='WhatsappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch for all WhatsApp sending.')),
                ('mock', models.BooleanField(default=True, help_text='Mock mode: log sends without hitting the gateway.')),
                ('api_key', models.CharField(blank=True, help_text='LemIn AI API key (blank = use .env).', max_length=200)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Settings',
                'verbose_name_plural': 'WhatsApp Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('farmer', 'Farmer'), ('employee', 'Employee')], max_length=10)),
                ('party_id', models.PositiveIntegerField(blank=True, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('module', models.CharField(blank=True, help_text="Document source key, e.g. 'sales'.", max_length=30)),
                ('document_no', models.CharField(blank=True, max_length=50)),
                ('template_name', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('invalid', 'Invalid'), ('disabled', 'Disabled'), ('mocked', 'Mocked'), ('unknown', 'Unknown')], db_index=True, default='queued', max_length=10)),
                ('wamid', models.CharField(blank=True, help_text='WhatsApp message ID.', max_length=128)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('api_request', models.JSONField(blank=True, help_text='Sanitized request context (no secrets).', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='notification.whatsappmessage')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='notification.whatsapptemplate')),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['mobile', 'created_at'], name='notificatio_mobile_7aa111_idx'), models.Index(fields=['module', 'document_no'], name='notificatio_module_4c5f5a_idx')],
            },
        ),
    ]
