# Generated by Django 4.2.6 on 2026-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='device_created_at',
            field=models.DateTimeField(blank=True, help_text='When the user filed it on the device', null=True),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='device_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='offline_no',
            field=models.CharField(blank=True, help_text="The phone's own number, e.g. OFF-20260808-000124", max_length=32),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='server_received_at',
            field=models.DateTimeField(blank=True, help_text='When it reached the ERP', null=True),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['device_id'], name='api_idempot_device__1cbaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['offline_no'], name='api_idempot_offline_59adc6_idx'),
        ),
    ]
