# Generated by Django 4.2.6 on 2026-08-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_idempotencyrecord_device_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('pending', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('conflicts', models.PositiveIntegerField(default=0)),
                ('synced', models.PositiveIntegerField(default=0, help_text='Entries this device has confirmed, as it counts them')),
                ('oldest_pending_at', models.DateTimeField(blank=True, help_text='When the longest-waiting entry was filed on the device', null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sync_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Sync State',
                'verbose_name_plural': 'Device Sync States',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='devicesyncstate',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_device_sync_user_device'),
        ),
    ]
