# Generated by Django 4.2.6 on 2026-09-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicesyncstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='location',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
