"""Remove the notifications the Web-Access audit table generated about itself.

The alerts app auto-registers every model and picked up WebAccessAudit when
that table was added, so each audit write raised a notification. Opening the
alert centre made it self-sustaining: that page hits alert-list, which was
unmapped, which recorded an audit row, which raised another notification into
the page being read.

Both causes are fixed — the model is excluded from alert tracking and the alert
endpoints are no longer unmapped — but the rows already written stay until they
are removed. This removes them, and nothing else: it matches on the model name
the alerts app recorded, so a real notification cannot be caught by it.

    python manage.py purge_audit_alerts --dry-run
    python manage.py purge_audit_alerts
"""
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Delete alerts and audit-log rows generated by the Web-Access audit table."

    def model_name(self):
        """The label the alerts app records, taken from its own helper.

        It stores "app_label.ModelName", not the bare class name. Hardcoding
        the short form matched nothing, and the test that was supposed to catch
        that had created its fixture with the same wrong value — it checked the
        assumption instead of the behaviour.
        """
        from alerts.utils import model_label

        from user.models import WebAccessAudit

        return model_label(WebAccessAudit)

    def add_arguments(self, parser):
        parser.add_argument("--dry-run", action="store_true",
                            help="Report what would go, delete nothing.")

    def handle(self, *args, **options):
        from alerts.models import Alert, AuditLog

        name = self.model_name()
        targets = []
        for model, label in ((Alert, "notification"), (AuditLog, "audit-log")):
            qs = model.objects.filter(model_name__iexact=name)
            targets.append((qs, label, qs.count()))

        total = sum(count for _qs, _label, count in targets)
        if not total:
            self.stdout.write("Nothing to remove — no rows reference the "
                              "Web-Access audit table.")
            return

        for _qs, label, count in targets:
            self.stdout.write(f"  {count:>7} {label} row(s)")

        if options["dry_run"]:
            self.stdout.write(self.style.WARNING(
                f"\nDry run: {total} row(s) would be removed."))
            return

        for qs, label, count in targets:
            if count:
                qs.delete()
        self.stdout.write(self.style.SUCCESS(f"\nRemoved {total} row(s)."))
