# Generated by Django 4.2.6 on 2026-07-11 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hatchery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatchery_name', models.CharField(help_text='Name of the hatchery', max_length=150, unique=True)),
                ('operation_type', models.CharField(choices=[('own', 'Own'), ('contract', 'Contract'), ('lease', 'Lease')], help_text='Type of operation', max_length=20)),
                ('owner_name', models.CharField(blank=True, help_text="Owner's name", max_length=150)),
                ('contact', models.CharField(blank=True, help_text='Contact number', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], help_text='State where the hatchery is located', max_length=100)),
                ('agreement_months', models.PositiveIntegerField(blank=True, help_text='Duration of the agreement in months', null=True)),
                ('document', models.FileField(blank=True, help_text='Supporting document (agreement copy, etc.)', null=True, upload_to='hatchery_master/documents/')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive hatcheries are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hatchery',
                'verbose_name_plural': 'Hatcheries',
                'ordering': ['hatchery_name'],
            },
        ),
    ]
