# Generated by Django 4.2.6 on 2026-07-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setter_no', models.CharField(help_text='Setter machine number', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Egg capacity of this setter')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive setters are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hatchery', models.ForeignKey(help_text='Hatchery this setter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='setters', to='hatchery_master.hatchery')),
            ],
            options={
                'verbose_name': 'Setter',
                'verbose_name_plural': 'Setters',
                'ordering': ['hatchery__hatchery_name', 'setter_no'],
                'unique_together': {('hatchery', 'setter_no')},
            },
        ),
    ]
