# Generated by Django 4.2.6 on 2026-07-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0002_setter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatcher_no', models.CharField(help_text='Hatcher machine number', max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Egg capacity of this hatcher')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive hatchers are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hatchery', models.ForeignKey(help_text='Hatchery this hatcher belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='hatchers', to='hatchery_master.hatchery')),
            ],
            options={
                'verbose_name': 'Hatcher',
                'verbose_name_plural': 'Hatchers',
                'ordering': ['hatchery__hatchery_name', 'hatcher_no'],
                'unique_together': {('hatchery', 'hatcher_no')},
            },
        ),
    ]
