# Generated by Django 4.2.6 on 2026-07-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0003_hatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the expense type', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive expense types are hidden from selection elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Type',
                'verbose_name_plural': 'Expense Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HatcheryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the expense')),
                ('stage', models.CharField(choices=[('eggs', 'On Eggs'), ('chicks', 'On Chicks')], default='eggs', help_text='Whether this expense was incurred on eggs or chicks', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive expenses are excluded from totals elsewhere')),
                ('is_locked', models.BooleanField(default=False, help_text="Locked records can't be edited or deleted")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.ForeignKey(help_text='Category of this expense', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hatchery_master.expensetype')),
                ('hatchery', models.ForeignKey(help_text='Hatchery this expense belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='hatchery_master.hatchery')),
            ],
            options={
                'verbose_name': 'Hatchery Expense',
                'verbose_name_plural': 'Hatchery Expenses',
                'ordering': ['-date', 'hatchery__hatchery_name'],
            },
        ),
    ]
