# Generated by Django 4.2.6 on 2026-07-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_warehouse_linked_warehouses_warehouse_branch'),
        ('hatchery_master', '0004_expensetype_hatcheryexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchery',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Office/warehouse this hatchery is mapped to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatcheries', to='inventory.warehouse'),
        ),
    ]
