# Generated by Django 4.2.6 on 2026-07-20 05:58

from django.db import migrations


def backfill_hatchery_office_mappings(apps, schema_editor):
    Hatchery = apps.get_model("hatchery_master", "Hatchery")
    Mapping = apps.get_model("inventory", "Mapping")
    Mapping.objects.bulk_create([
        Mapping(type="hatchery_office", from_id=hatchery_id, to_id=warehouse_id)
        for hatchery_id, warehouse_id in Hatchery.objects.filter(
            warehouse__isnull=False
        ).values_list("id", "warehouse_id")
    ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0005_hatchery_warehouse'),
        ('inventory', '0028_mapping_remove_warehouse_branch_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_hatchery_office_mappings, noop),
        migrations.RemoveField(
            model_name='hatchery',
            name='warehouse',
        ),
    ]
