# Generated by Django 4.2.6 on 2026-08-01 20:09

import Hitech_BIMS.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0006_remove_hatchery_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatchery',
            name='document',
            field=models.FileField(blank=True, help_text='Supporting document (agreement copy, etc.)', null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='hatchery_master/documents/'),
        ),
    ]
