# Generated by Django 4.2.6 on 2025-01-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                ("mobile", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "contact_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pan", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "supplier_group",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gstin", models.CharField(blank=True, max_length=15, null=True)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("credit_term", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaxMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tax_code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("tax_percentage", models.FloatField(blank=True, null=True)),
                ("rule", models.CharField(blank=True, max_length=50, null=True)),
                ("coa", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermsConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("condition", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VendorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "control_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "prepayment_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
