# Generated by Django 4.2.6 on 2025-01-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_creditterm_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name=' Item Category')),
                ('code', models.CharField(max_length=100, verbose_name='Item Code')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('units', models.CharField(blank=True, max_length=100, null=True, verbose_name='Units')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price / Unit')),
                ('qty_sent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qty Sent')),
                ('qty_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qty Received')),
                ('qty_free', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qty Free')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('bags_or_boxes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bags / Boxes')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='VAT (%)')),
                ('warehouse', models.CharField(max_length=100, verbose_name='Warehouse')),
                ('flock', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flock')),
                ('sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sqft')),
                ('sqft_per_chick', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sqft / Chicks')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='purchase.purchaseorder', verbose_name='Purchase Order')),
            ],
        ),
    ]
