# Generated by Django 4.2.6 on 2025-01-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_category_itemcategory"),
        ("purchase", "0003_purchaseorderlineitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="code",
        ),
        migrations.RemoveField(
            model_name="purchaseorderlineitem",
            name="description",
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                help_text="Item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderlineitem",
            name="item_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Item category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.itemcategory",
            ),
        ),
    ]
