# Generated by Django 4.2.6 on 2026-07-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchaseorderlineitem_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TermsConditions',
        ),
    ]
