# Generated by Django 4.2.6 on 2026-07-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_delete_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text='Short supplier code', max_length=50, null=True),
        ),
    ]
