# Generated by Django 4.2.6 on 2026-07-17 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_supplier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='aadhar',
            field=models.CharField(blank=True, help_text='Aadhar number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_no',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/agreements/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agreement_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='agreement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='as_on_date',
            field=models.DateField(blank=True, help_text='Opening balance as-on date', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Credit limit in currency', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='mobile_2',
            field=models.CharField(blank=True, help_text='Secondary mobile number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opening balance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='supplier_documents/other/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='party_category',
            field=models.CharField(blank=True, choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor'), ('Farmer', 'Farmer'), ('Other', 'Other')], help_text='Party category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='to_pay_to_receive',
            field=models.CharField(blank=True, choices=[('To Pay', 'To Pay'), ('To Receive', 'To Receive')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SupplierShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-is_default', 'label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='suppliershippingaddress',
            constraint=models.UniqueConstraint(fields=('supplier', 'label'), name='unique_supplier_shipping_address_label'),
        ),
    ]
