# Generated by Django 4.2.6 on 2026-07-17 04:26
# Converts the free-text control/prepayment account columns into FKs to the
# chart of accounts. Old text values cannot be mapped automatically, so the
# columns are dropped and recreated (values reset to NULL).

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_voucher_source_content_type_voucher_source_object_id_and_more'),
        ('purchase', '0007_supplier_aadhar_supplier_account_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorgroup',
            name='control_account',
        ),
        migrations.RemoveField(
            model_name='vendorgroup',
            name='prepayment_account',
        ),
        migrations.AddField(
            model_name='vendorgroup',
            name='control_account',
            field=models.ForeignKey(blank=True, help_text='Control account from the chart of accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_group_control_accounts', to='account.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vendorgroup',
            name='prepayment_account',
            field=models.ForeignKey(blank=True, help_text='Prepayment account from the chart of accounts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_group_prepayment_accounts', to='account.chartofaccount'),
        ),
    ]
