# Generated by Django 4.2.6 on 2026-07-17 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_backfill_expense_ledger_roles'),
        ('inventory', '0002_rename_category_itemcategory'),
        ('purchase', '0008_alter_vendorgroup_control_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. PIN-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(blank=True, max_length=100)),
                ('dc_no', models.CharField(blank=True, max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_mobile', models.CharField(blank=True, max_length=20)),
                ('calculation_based_on', models.CharField(choices=[('Sent Quantity', 'Sent Quantity'), ('Received Quantity', 'Received Quantity')], default='Sent Quantity', max_length=20)),
                ('payment_terms', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=20)),
                ('freight_type', models.CharField(choices=[('Included in Bill', 'Included in Bill'), ('Extra', 'Extra')], default='Extra', max_length=20)),
                ('payment_mode', models.CharField(choices=[('pay_later', 'Pay Later'), ('pay_in_bill', 'Pay In Bill')], default='pay_later', max_length=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bag_type', models.CharField(blank=True, choices=[('Jute Bag', 'Jute Bag'), ('HDPE Bag', 'HDPE Bag'), ('Loose', 'Loose')], max_length=20)),
                ('no_of_bags', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tds_code', models.CharField(blank=True, max_length=50)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges_type', models.CharField(choices=[('Add', 'Add'), ('Deduct', 'Deduct')], default='Add', max_length=10)),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off_type', models.CharField(choices=[('Add', 'Add'), ('Deduct', 'Deduct')], default='Add', max_length=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('reference_document_1', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('reference_document_2', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('reference_document_3', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_purchase_freight_accounts', to='account.chartofaccount')),
                ('other_charges_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_purchase_other_charges_accounts', to='account.chartofaccount')),
                ('pay_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_purchase_pay_accounts', to='account.chartofaccount')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_purchases', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('sent_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rcv_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('farm_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_items', to='inventory.warehouse')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_items', to='inventory.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.generalpurchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderLineItem',
        ),
    ]
