# Generated by Django 4.2.6 on 2026-07-18 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_backfill_expense_ledger_roles'),
        ('hatchery_master', '0004_expensetype_hatcheryexpense'),
        ('inventory', '0002_rename_category_itemcategory'),
        ('purchase', '0009_generalpurchase_generalpurchaseitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChicksPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. CPR-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(blank=True, max_length=100)),
                ('dc_no', models.CharField(blank=True, max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('freight_type', models.CharField(choices=[('Included in Bill', 'Included in Bill'), ('Extra', 'Extra')], default='Extra', max_length=20)),
                ('payment_mode', models.CharField(choices=[('pay_later', 'Pay Later'), ('pay_in_bill', 'Pay In Bill')], default='pay_later', max_length=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bag_type', models.CharField(blank=True, choices=[('Jute Bag', 'Jute Bag'), ('HDPE Bag', 'HDPE Bag'), ('Loose', 'Loose')], max_length=20)),
                ('no_of_bags', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('tds_code', models.CharField(blank=True, max_length=50)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges_type', models.CharField(choices=[('Add', 'Add'), ('Deduct', 'Deduct')], default='Add', max_length=10)),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off_type', models.CharField(choices=[('Add', 'Add'), ('Deduct', 'Deduct')], default='Add', max_length=10)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('reference_document_1', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('reference_document_2', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('reference_document_3', models.FileField(blank=True, null=True, upload_to='purchase/references/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_purchase_freight_accounts', to='account.chartofaccount')),
                ('hatchery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_purchases', to='hatchery_master.hatchery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchases', to='inventory.item')),
                ('other_charges_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_purchase_other_charges_accounts', to='account.chartofaccount')),
                ('pay_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_purchase_pay_accounts', to='account.chartofaccount')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchases', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChicksPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_qty_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('mortality', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shortage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weaks', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excess_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rcv_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('farm_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchase_items', to='inventory.warehouse')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.chickspurchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
