# Generated by Django 4.2.6 on 2026-07-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_chickspurchase_chickspurchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickspurchaseitem',
            name='billed_qty',
        ),
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='sent_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chickspurchaseitem',
            name='rcv_qty',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
