# Generated by Django 4.2.6 on 2026-07-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_remove_chickspurchaseitem_billed_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickspurchaseitem',
            name='free_qty_percent',
        ),
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='rcv_free_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free % backed out of Rcv Qty to get the chargeable Total Qty', max_digits=5),
        ),
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='sent_free_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free % applied to Sent Qty when deriving Rcv Qty', max_digits=5),
        ),
    ]
