# Generated by Django 4.2.6 on 2026-07-18 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('account', '0012_backfill_expense_ledger_roles'),
        ('purchase', '0012_remove_chickspurchaseitem_free_qty_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. PAY-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='inventory.warehouse')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('pay_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payment_lines', to='account.chartofaccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.supplierpayment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
