# Generated by Django 4.2.6 on 2026-07-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_supplierpayment_supplierpaymentline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpayment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='supplierpaymentline',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_lines', to='purchase.supplier'),
            preserve_default=False,
        ),
    ]
