# Generated by Django 4.2.6 on 2026-07-24 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
        ('purchase', '0014_remove_supplierpayment_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. DN-2627-0001 / CN-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('against_bill', models.CharField(blank=True, help_text='Related purchase bill/invoice no.', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.chartofaccount')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. DN-2627-0001 / CN-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('against_bill', models.CharField(blank=True, help_text='Related purchase bill/invoice no.', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.chartofaccount')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='purchase.supplier')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
    ]
