# Generated by Django 4.2.6 on 2026-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_debitnote_creditnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='party_category',
            field=models.CharField(blank=True, help_text='Party category', max_length=50, null=True),
        ),
    ]
