# Generated by Django 4.2.6 on 2026-07-30 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('purchase', '0016_alter_supplier_party_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='reason',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Office / branch this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Office / branch this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='against_bill',
            field=models.CharField(blank=True, help_text='Related purchase bill / DC no.', max_length=50),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='against_bill',
            field=models.CharField(blank=True, help_text='Related purchase bill / DC no.', max_length=50),
        ),
    ]
