# Generated by Django 4.2.6 on 2026-08-01 20:09

import Hitech_BIMS.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_chicks_purchase_single_free_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickspurchase',
            name='reference_document_1',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='chickspurchase',
            name='reference_document_2',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='chickspurchase',
            name='reference_document_3',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='reference_document_1',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='reference_document_2',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='reference_document_3',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='purchase/references/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='supplier_documents/agreements/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='other_documents',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='supplier_documents/other/'),
        ),
    ]
