# Generated by Django 4.2.6 on 2026-08-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0055_alter_dailyentryphoto_kind'),
        ('inventory', '0035_stocktransfer_source_supplier'),
        ('purchase', '0019_alter_chickspurchase_reference_document_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpurchaseitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The flock the delivery is for, when it goes to a farm', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_items', to='broiler.broilerbatch'),
        ),
        migrations.AddField(
            model_name='generalpurchaseitem',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Destination when the goods go straight to a farm', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_items', to='broiler.broilerfarm'),
        ),
        migrations.AlterField(
            model_name='generalpurchaseitem',
            name='farm_warehouse',
            field=models.ForeignKey(blank=True, help_text='Destination when the goods go to a warehouse', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_items', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='generalpurchaseitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('farm__isnull', True), ('farm_warehouse__isnull', False)), models.Q(('farm__isnull', False), ('farm_warehouse__isnull', True)), _connector='OR'), name='purchase_item_one_destination'),
        ),
        migrations.AddConstraint(
            model_name='generalpurchaseitem',
            constraint=models.CheckConstraint(check=models.Q(('batch__isnull', True), ('farm__isnull', False), _connector='OR'), name='purchase_item_batch_needs_farm'),
        ),
    ]
