# Generated by Django 4.2.6 on 2026-08-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_generalpurchaseitem_batch_generalpurchaseitem_farm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickspurchase',
            name='freight_type',
            field=models.CharField(choices=[('No Freight', 'No Freight'), ('Freight Included', 'Freight Included'), ('Freight Extra', 'Freight Extra')], default='Extra', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='freight_type',
            field=models.CharField(choices=[('No Freight', 'No Freight'), ('Freight Included', 'Freight Included'), ('Freight Extra', 'Freight Extra')], default='Extra', max_length=20),
        ),
    ]
