# Generated by Django 4.2.6 on 2026-08-15 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_freight_type_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickspurchase',
            name='freight_settlement',
            field=models.CharField(choices=[('In Purchase Bill', 'Included in Purchase Bill'), ('Separate Bill', 'Separate Freight Bill')], default='In Purchase Bill', max_length=20),
        ),
        migrations.AddField(
            model_name='chickspurchase',
            name='freight_supplier',
            field=models.ForeignKey(blank=True, help_text='The transporter, when freight is billed separately', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchase_freights', to='purchase.supplier'),
        ),
        migrations.AddField(
            model_name='generalpurchase',
            name='freight_settlement',
            field=models.CharField(choices=[('In Purchase Bill', 'Included in Purchase Bill'), ('Separate Bill', 'Separate Freight Bill')], default='In Purchase Bill', max_length=20),
        ),
        migrations.AddField(
            model_name='generalpurchase',
            name='freight_supplier',
            field=models.ForeignKey(blank=True, help_text='The transporter, when freight is billed separately', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_purchase_freights', to='purchase.supplier'),
        ),
        migrations.AlterField(
            model_name='chickspurchase',
            name='payment_mode',
            field=models.CharField(choices=[('pay_later', 'Credit / Pay Later'), ('pay_in_bill', 'Paid')], default='pay_later', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='payment_mode',
            field=models.CharField(choices=[('pay_later', 'Credit / Pay Later'), ('pay_in_bill', 'Paid')], default='pay_later', max_length=15),
        ),
    ]
