# Generated by Django 4.2.6 on 2026-08-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0023_chickspurchase_freight_settlement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickspurchase',
            name='freight_supplier',
        ),
        migrations.RemoveField(
            model_name='generalpurchase',
            name='freight_supplier',
        ),
        migrations.AddField(
            model_name='chickspurchase',
            name='freight_transporter',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='generalpurchase',
            name='freight_transporter',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
