# Generated by Django 4.2.6 on 2026-08-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_remove_chickspurchase_freight_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chickspurchase',
            name='freight_type',
            field=models.CharField(choices=[('No Freight', 'No Freight'), ('Freight Included', 'Freight Included'), ('Freight Extra', 'Freight Extra')], default='No Freight', max_length=20),
        ),
        migrations.AlterField(
            model_name='generalpurchase',
            name='freight_type',
            field=models.CharField(choices=[('No Freight', 'No Freight'), ('Freight Included', 'Freight Included'), ('Freight Extra', 'Freight Extra')], default='No Freight', max_length=20),
        ),
    ]
