# Generated by Django 4.2.6 on 2026-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_alter_chickspurchase_freight_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpurchase',
            name='calculation_based_on',
            field=models.CharField(choices=[('Sent Quantity', 'Sent Quantity'), ('Received Quantity', 'Received Quantity')], default='Received Quantity', max_length=20),
        ),
    ]
