# Generated by Django 4.2.6 on 2026-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0027_supplier_unique_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpaymentline',
            name='mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
