# Generated by Django 4.2.6 on 2026-09-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_item_updated_at'),
        ('broiler', '0077_farm_capacity_optional'),
        ('purchase', '0028_alter_supplierpaymentline_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='farm',
            field=models.ForeignKey(blank=True, help_text='Farm the chicks were placed at, when bought straight onto one', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchase_items', to='broiler.broilerfarm'),
        ),
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='farm_batch',
            field=models.ForeignKey(blank=True, help_text='The flock at that farm the chicks were placed into', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chicks_purchase_items', to='broiler.broilerbatch'),
        ),
        migrations.AddField(
            model_name='chickspurchaseitem',
            name='placement',
            field=models.OneToOneField(blank=True, help_text='The Chicks Placement this line created', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_purchase_line', to='inventory.stocktransfer'),
        ),
    ]
