# Generated by Django 4.2.6 on 2024-12-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_employee_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="relieve",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
