# Generated by Django 4.2.6 on 2025-01-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0005_remove_employee_user_employee_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="loan_account",
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="branch_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
