# Generated by Django 4.2.6 on 2025-01-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_remove_employee_loan_account_employee_bank_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="emergency_contact_1",
            new_name="emergency_contact",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_contact_2",
        ),
    ]
