# Generated by Django 4.2.6 on 2025-01-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_employeeleave_employeeleaveselecteddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeleave",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="EmployeeLeaveSelectedDate",
        ),
    ]
