# Generated by Django 4.2.6 on 2025-01-16 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_employeeleave_created_date_employeeleave_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeleave",
            name="date",
        ),
        migrations.CreateModel(
            name="LeaveSelectedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "leave_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_dates",
                        to="hr.employeeleave",
                    ),
                ),
            ],
        ),
    ]
