# Generated by Django 4.2.6 on 2025-01-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0011_remove_employeeleave_date_leaveselecteddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
