# Generated by Django 4.2.6 on 2025-01-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employeeleave_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
