# Generated by Django 4.2.6 on 2025-01-17 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
