# Generated by Django 4.2.6 on 2025-01-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Full Day", "Full Day"),
                    ("First Half", "First Half"),
                    ("Second Half", "Second Half"),
                ],
                default="Full Day",
                max_length=15,
            ),
        ),
    ]
