# Generated by Django 4.2.6 on 2025-01-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_group_sector_alter_employee_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
