# Generated by Django 4.2.6 on 2025-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_payroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="total_working_days",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
