# Generated by Django 4.2.6 on 2025-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0020_payroll_total_working_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="payable_salary",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
