# Generated by Django 4.2.6 on 2025-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0022_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
    ]
