# Generated by Django 4.2.6 on 2025-01-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0024_remove_employee_sector_employee_warehouse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Sector",
        ),
    ]
