# Generated by Django 4.2.6 on 2026-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_designation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='driving_license_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
