# Generated by Django 4.2.6 on 2026-07-24 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('hr', '0028_department_shift_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Branch this group belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_groups', to='inventory.warehouse'),
        ),
    ]
