# Generated by Django 4.2.6 on 2026-08-05 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0050_dailyentryphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0029_group_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(default='Two Wheeler', max_length=30)),
                ('registration', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, help_text='What the driver calls it, when a number is not enough', max_length=40)),
                ('is_default', models.BooleanField(default=False, help_text='Chosen for a new trip unless another is picked')),
                ('is_retired', models.BooleanField(default=False, help_text='Tick when sold or off the road; past trips stay readable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee Vehicle',
                'verbose_name_plural': 'Employee Vehicles',
                'ordering': ['is_retired', '-is_default', 'registration'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. TRP-2026-0412', max_length=30, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('vehicle_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Public Transport', 'Public Transport'), ('Other', 'Other')], default='Two Wheeler', max_length=30)),
                ('registration', models.CharField(blank=True, help_text='Registration as it stood on the day', max_length=30)),
                ('start_odometer', models.PositiveIntegerField(blank=True, help_text='Km at the start', null=True)),
                ('end_odometer', models.PositiveIntegerField(blank=True, help_text='Km at the end', null=True)),
                ('distance_km', models.PositiveIntegerField(default=0, editable=False, help_text='End minus start; stored so reports can total it in the database')),
                ('start_photo', models.ImageField(blank=True, null=True, upload_to='trips/start/')),
                ('end_photo', models.ImageField(blank=True, null=True, upload_to='trips/end/')),
                ('start_photo_at', models.DateTimeField(blank=True, null=True)),
                ('end_photo_at', models.DateTimeField(blank=True, null=True)),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('end_address', models.CharField(blank=True, max_length=255)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_trips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Whose day this is; taken from the login where it maps to one', on_delete=django.db.models.deletion.PROTECT, related_name='daily_trips', to='hr.employee')),
                ('vehicle', models.ForeignKey(blank=True, help_text="Picked from the driver's registered vehicles", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='hr.employeevehicle')),
            ],
            options={
                'verbose_name': 'Supervisor Daily Trip',
                'verbose_name_plural': 'Supervisor Daily Trips',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorTripVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, help_text='Why the farm was called at', max_length=120)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False, help_text='Derived from check-in/check-out')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_visits', to='broiler.broilerfarm')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='hr.supervisortrip')),
            ],
            options={
                'verbose_name': 'Trip Farm Visit',
                'verbose_name_plural': 'Trip Farm Visits',
                'ordering': ['checked_in_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='supervisortrip',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='one_trip_per_employee_per_day'),
        ),
        migrations.AddConstraint(
            model_name='employeevehicle',
            constraint=models.UniqueConstraint(fields=('employee', 'registration'), name='one_registration_per_employee'),
        ),
    ]
