"""
Django settings for Hitech_BIMS project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file
load_dotenv()


def env_bool(name: str, default: bool) -> bool:
    """Parse a boolean-ish environment variable."""
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def env_list(name: str, default: str = "") -> list:
    """Parse a comma-separated environment variable into a list."""
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Define the path for the log files
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. Define it in your .env file "
        "(see .env.example)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", False)
DEVELOPMENT_MODE = env_bool("DEVELOPMENT_MODE", DEBUG)

# Configure allowed hosts based on environment.
# No insecure "*" fallback: production must set ALLOWED_HOSTS explicitly.
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS")
if not ALLOWED_HOSTS:
    if DEBUG:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
    else:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS environment variable is not set. Define it in your .env "
            "file (e.g. ALLOWED_HOSTS=yourdomain.com,your.droplet.ip)."
        )

# Origins allowed to submit cross-origin POSTs (required behind HTTPS with Django 4+).
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "import_export",
    # Custom apps
    "user",
    "broiler",
    "hatchery",
    "hatchery_master",
    "inventory",
    "hr",
    "sales",
    "purchase",
    "account",
    "notification",
    "environmental_monitoring",
    "tracking",
    "picklist",
    "alerts",
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves STATIC_ROOT directly from Django/Gunicorn - required on platforms
    # with no separate web server in front (e.g. DigitalOcean App Platform).
    # On the Nginx/Droplet path, Nginx intercepts /static/ first (see
    # deploy/nginx.conf) so this is simply never reached there.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Publishes the active request/user into thread-local context so the alerts
    # module can attribute model-signal events without threading the request
    # through every call site. Must sit AFTER AuthenticationMiddleware so
    # request.user is populated. See alerts/middleware.py.
    "alerts.middleware.AlertContextMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Enforces the per-group Web-Access matrix server-side (see user/access.py).
    "user.middleware.WebAccessMiddleware",
]

ROOT_URLCONF = "Hitech_BIMS.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Exposes allowed_nav/allowed_tabs/allowed_sections/section_url/
                # page_perms for nav-hiding and per-page button-hiding.
                "user.context_processors.web_access",
            ],
        },
    },
]

WSGI_APPLICATION = "Hitech_BIMS.wsgi.application"

# Database configuration.
# CONN_MAX_AGE keeps connections open between requests (persistent connections)
# instead of reconnecting to PostgreSQL on every request; CONN_HEALTH_CHECKS
# verifies a pooled connection is still alive before reuse.
DB_CONN_MAX_AGE = int(os.getenv("DB_CONN_MAX_AGE", "60"))
DB_CONNECT_TIMEOUT = int(os.getenv("DB_CONNECT_TIMEOUT", "10"))


def db_options_for_engine(engine: str) -> dict:
    """Return backend-specific connection options for the selected engine."""
    if "postgresql" in engine:
        return {"connect_timeout": DB_CONNECT_TIMEOUT}
    return {}


if DEVELOPMENT_MODE:
    db_engine = os.getenv("DB_ENGINE", "django.db.backends.postgresql")
    DATABASES = {
        "default": {
            "ENGINE": db_engine,
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": DB_CONN_MAX_AGE,
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": db_options_for_engine(db_engine),
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=DB_CONN_MAX_AGE,
            conn_health_checks=True,
        )
    }
    DATABASES["default"].setdefault("OPTIONS", {})
    if "postgresql" in DATABASES["default"].get("ENGINE", ""):
        DATABASES["default"]["OPTIONS"]["connect_timeout"] = DB_CONNECT_TIMEOUT
    # Managed Postgres (DigitalOcean, etc.) rejects non-SSL connections.
    # dj_database_url already picks up ?sslmode=... if present in DATABASE_URL;
    # this only fills in a default when the URL itself doesn't specify one.
    if "postgresql" in DATABASES["default"].get("ENGINE", ""):
        DATABASES["default"]["OPTIONS"].setdefault("sslmode", os.getenv("DB_SSLMODE", "require"))

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session security
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(8 * 60 * 60)))  # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = env_bool("SESSION_EXPIRE_AT_BROWSER_CLOSE", True)
SESSION_SAVE_EVERY_REQUEST = True
CSRF_COOKIE_HTTPONLY = True

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Gzip-compresses static files at collectstatic time (served by WhiteNoise
# above). Deliberately not CompressedManifestStaticFilesStorage: verified
# directly that staticfiles_storage.url() keeps returning un-hashed paths
# even though the hash manifest is generated correctly, so the hashed/
# cache-busting variant provides no benefit here and was reverted.
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Email configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_USE_TLS = True
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# SMS / Notification configuration.
# All values are read here (see notification/conf.py) so the notification app
# never touches settings directly. SMS is opt-in: it stays disabled until
# SMS_ENABLED is set, and runs in mock mode automatically during local
# development so no real messages are sent.
SMS_ENABLED = env_bool("SMS_ENABLED", False)
SMS_MOCK = env_bool("SMS_MOCK", DEBUG)
SMS_PROVIDER = os.getenv("SMS_PROVIDER", "smsgatewayhub")
SMS_TIMEOUT = int(os.getenv("SMS_TIMEOUT", "10"))
SMS_MAX_RETRIES = int(os.getenv("SMS_MAX_RETRIES", "2"))
SMS_RETRY_BACKOFF = float(os.getenv("SMS_RETRY_BACKOFF", "0.5"))
SMS_DEFAULT_COUNTRY_CODE = os.getenv("SMS_DEFAULT_COUNTRY_CODE", "91")
SMS_MAX_LENGTH = int(os.getenv("SMS_MAX_LENGTH", "1000"))

# SMSGatewayHub provider credentials/routing.
SMS_GATEWAYHUB_BASE_URL = os.getenv("SMS_GATEWAYHUB_BASE_URL", "https://www.smsgatewayhub.com")
SMS_GATEWAYHUB_API_KEY = os.getenv("SMS_GATEWAYHUB_API_KEY", "")
SMS_GATEWAYHUB_SENDER_ID = os.getenv("SMS_GATEWAYHUB_SENDER_ID", "")
SMS_GATEWAYHUB_ROUTE = os.getenv("SMS_GATEWAYHUB_ROUTE", "1")
SMS_GATEWAYHUB_CHANNEL = os.getenv("SMS_GATEWAYHUB_CHANNEL", "2")

# Calendarific holiday lookup (HR > Attendance > Leave Placed calendar).
CALENDARIFIC_API_KEY = os.getenv("CALENDARIFIC_API_KEY", "")
CALENDARIFIC_COUNTRY = os.getenv("CALENDARIFIC_COUNTRY", "IN")
SMS_GATEWAYHUB_DCS = os.getenv("SMS_GATEWAYHUB_DCS", "0")
# DLT registration fields (required for Indian traffic when provisioned).
SMS_GATEWAYHUB_ENTITY_ID = os.getenv("SMS_GATEWAYHUB_ENTITY_ID", "")
SMS_GATEWAYHUB_DLT_TEMPLATE_ID = os.getenv("SMS_GATEWAYHUB_DLT_TEMPLATE_ID", "")

# Employee Tracking configuration.
# Provider credentials (TrackWick/TrackoLap API keys etc.) are DB-backed
# master records encrypted at rest (see tracking/crypto.py) and edited from
# the Tracking Settings page — never environment variables. This key is the
# only tracking-related env var: a urlsafe-base64 32-byte Fernet key.
# Generate: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# When unset, a key derived from SECRET_KEY is used (fine for development;
# production should set it so credentials survive a SECRET_KEY rotation).
TRACKING_ENCRYPTION_KEY = os.getenv("TRACKING_ENCRYPTION_KEY", "")

# Environmental Monitoring (Tapo H100 / T310) configuration.
# Operational tuning is read here (see environmental_monitoring/conf.py); the
# Tapo account credentials and default alert thresholds are both DB-backed
# master records, editable from the ERP UI under Environmental Monitoring,
# not environment variables.
ENV_MONITORING_POLL_INTERVAL_SECONDS = int(os.getenv("ENV_MONITORING_POLL_INTERVAL_SECONDS", "60"))
ENV_MONITORING_OFFLINE_AFTER_MINUTES = int(os.getenv("ENV_MONITORING_OFFLINE_AFTER_MINUTES", "15"))

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cache configuration.
# Local-memory cache - process-local, so entries aren't shared across
# Gunicorn workers. Fine for the current single-worker deployment; revisit
# if the app scales to multiple workers/processes and needs a shared cache.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "TIMEOUT": 300,
    }
}

# Logging configuration.
# Django (info) and errors are split into separate rotating log files so an
# operator can tail errors.log without wading through routine request logs.
# Gunicorn's own access/error logs are configured independently in
# gunicorn.conf.py. Console logging is kept quiet in production since
# systemd/journald already captures it and duplicate verbose console output
# is just noise there.
CONSOLE_LOG_LEVEL = "INFO" if DEBUG else "WARNING"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s:%(lineno)d: %(message)s",
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "console": {
            "level": CONSOLE_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "info_file_handler": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "info.log",
            "maxBytes": 1048576,  # 1 MB
            "backupCount": 10,
            "formatter": "verbose",
        },
        "error_file_handler": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "error.log",
            "maxBytes": 1048576,  # 1 MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "info_file_handler", "error_file_handler"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Security settings.
# SECURE_PROXY_SSL_HEADER lets Django trust the "X-Forwarded-Proto" header set
# by Nginx (see nginx.conf) so SECURE_SSL_REDIRECT/HSTS work correctly with
# Gunicorn running as a plain HTTP upstream behind the TLS-terminating proxy.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Configurable so SSL redirect can be disabled right after a fresh deploy,
# before TLS certificates are issued, without touching code.
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", str(31536000)))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", True)
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", True)

# Clickjacking protection - safe to apply in both DEBUG and production.
X_FRAME_OPTIONS = "DENY"

# Django REST Framework — session-auth by default so the alerts API reuses the
# existing login. Kept minimal; the alerts viewsets set their own permissions.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# Alert & Audit module configuration (see alerts/conf.py for all keys/defaults).
# Everything below is optional — the module ships working defaults. Values here
# only override those defaults. Toggle channels via the ENABLE_* flags; email/
# websocket/slack/teams stay dormant until their infra is configured.
ALERT_SETTINGS = {
    "TRACK_ALL_MODELS": env_bool("ALERTS_TRACK_ALL_MODELS", True),
    "ENABLE_AUDIT": env_bool("ALERTS_ENABLE_AUDIT", True),
    "ENABLE_ALERTS": env_bool("ALERTS_ENABLE_ALERTS", True),
    "ENABLE_BULK_EVENTS": env_bool("ALERTS_ENABLE_BULK_EVENTS", True),
    "ENABLE_AUTH_EVENTS": env_bool("ALERTS_ENABLE_AUTH_EVENTS", True),
    "ENABLE_EMAIL": env_bool("ALERTS_ENABLE_EMAIL", False),
    "ENABLE_WEBSOCKET": env_bool("ALERTS_ENABLE_WEBSOCKET", False),
    "ENABLE_SLACK": env_bool("ALERTS_ENABLE_SLACK", False),
    "SLACK_WEBHOOK_URL": os.getenv("ALERTS_SLACK_WEBHOOK_URL", ""),
    # High-churn detail/line-item tables that would flood the feed. Add freely;
    # these are audited in the DB but excluded from noisy alerting if desired.
    "IGNORE_MODELS": env_list("ALERTS_IGNORE_MODELS"),
}
