from django.urls import path
from . import views

urlpatterns = [
    path('coa/', views.coa, name='coa'),
    path('coa-category/', views.coa_category, name='coa_category'),
    path('coa_category_list/', views.CoACategoryAPI.as_view(), name='coa_category_list'),
    path('coa_category/<int:id>/', views.CoACategoryAPI.as_view(), name='coa_category_detail'),
    path('coa_category/<int:id>/delete/', views.CoACategoryAPI.as_view(), name='coa_category_delete'),
    path('coa_category/<int:id>/toggle-active/', views.toggle_coa_category_active, name='coa_category_toggle_active'),
    path('coa_category/<int:id>/toggle-lock/', views.toggle_coa_category_lock, name='coa_category_toggle_lock'),
    path('coa_category/bulk-upload/', views.coa_category_bulk_upload, name='coa_category_bulk_upload'),
    path('chart-of-accounts/', views.ChartOfAccountsAPI.as_view(), name='chart_of_accounts_list'),
    path('chart-of-accounts/create/', views.ChartOfAccountsAPI.as_view(), name='chart_of_accounts_create'),
    path('chart-of-accounts/<int:id>/', views.ChartOfAccountsAPI.as_view(), name='chart-of-accounts_update'),
    path('chart-of-accounts/<int:id>/delete/', views.ChartOfAccountsAPI.as_view(), name='chart-of-accounts_delete'),
    path('fin_year/', views.fin_year, name='fin_year'),
    path('financial_year/', views.FinancialYearAPI.as_view(), name='financial_year_list'),
    path('financial-year/create/', views.FinancialYearAPI.as_view(), name='financial_year_create'),
    path('financial-year/<int:id>/', views.FinancialYearAPI.as_view(), name='financial_year_update'),
    path('financial-year/<int:id>/delete/', views.FinancialYearAPI.as_view(), name='financial_year_delete'),
    path('bank_cash/', views.bank_cash, name='bank_cash'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule_list/', views.ScheduleAPI.as_view(), name='schedule_list'),
    path('schedule/create/', views.ScheduleAPI.as_view(), name='schedule_create'),
    path('schedule/<int:id>/', views.ScheduleAPI.as_view(), name='schedule_update'),
    path('schedule/<int:id>/delete/', views.ScheduleAPI.as_view(), name='schedule_delete'),
    path('company-profile/', views.company_profile, name='company_profile'),
    path('terms/', views.terms, name='terms'),
    path('terms_conditions/', views.TermsConditionsAPI.as_view(), name='terms_conditions_list'),
    path('terms_conditions/create/', views.TermsConditionsAPI.as_view(), name='terms_conditions_create'),
    path('terms_conditions/<int:id>/', views.TermsConditionsAPI.as_view(), name='terms_conditions_update'),
    path('terms_conditions/<int:id>/delete', views.TermsConditionsAPI.as_view(), name='terms_conditions_delete'),

]
