# Generated by Django 4.2.6 on 2025-01-20 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('valuation_method', models.CharField(choices=[('Weighted Average', 'Weighted Average'), ('Standard Costing', 'Standard Costing')], max_length=50)),
                ('standard_cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_uom', models.CharField(max_length=100)),
                ('consumption_uom', models.CharField(max_length=100)),
                ('usage', models.CharField(choices=[('Produced', 'Produced'), ('Sales', 'Sales')], max_length=50)),
                ('source', models.CharField(choices=[('Produced', 'Produced'), ('Purchased', 'Purchased')], max_length=50)),
                ('type', models.CharField(choices=[('Raw Material', 'Raw Material'), ('Finished Goods', 'Finished Goods'), ('Semi-finished Goods', 'Semi-finished Goods')], max_length=50)),
                ('item_account', models.CharField(choices=[('Asset', 'Asset'), ('Expense', 'Expense')], max_length=50)),
                ('lot_serial_control', models.CharField(choices=[('None', 'None'), ('Lot', 'Lot'), ('Serial', 'Serial')], default='None', max_length=50)),
                ('kg_per_bag', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hsn_code', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehouse')),
            ],
        ),
    ]
