# Generated by Django 4.2.6 on 2025-01-22 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="ItemCategory",
        ),
    ]
