# Generated by Django 4.2.6 on 2026-07-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('sector_type', models.CharField(choices=[('Branch Office', 'Branch Office'), ('Feedmill', 'Feedmill'), ('Hatchery', 'Hatchery'), ('Head Office', 'Head Office'), ('Warehouse', 'Warehouse')], max_length=30)),
            ],
        ),
    ]
