# Generated by Django 4.2.6 on 2026-07-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sector_type',
        ),
    ]
