# Generated by Django 4.2.6 on 2026-07-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_address_warehouse_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='linked_warehouses',
            field=models.ManyToManyField(blank=True, to='inventory.warehouse'),
        ),
    ]
