# Generated by Django 4.2.6 on 2026-07-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_linked_warehouses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='linked_warehouses',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_offices', to='inventory.warehouse'),
        ),
    ]
