# Generated by Django 4.2.6 on 2026-07-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_warehouse_linked_warehouses_warehouse_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='branch',
        ),
    ]
