# Generated by Django 4.2.6 on 2026-07-18 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0010_remove_branch_warehouse'),
        ('inventory', '0008_remove_warehouse_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='broiler.branch'),
        ),
    ]
