# Generated by Django 4.2.6 on 2026-07-18 07:49

import re

from django.db import migrations, models


def backfill_warehouse_codes(apps, schema_editor):
    Warehouse = apps.get_model('inventory', 'Warehouse')
    prefix = "SEH-"
    serials = []
    for code in Warehouse.objects.exclude(code='').values_list('code', flat=True):
        match = re.match(r"^SEH-(\d+)$", code or "")
        if match:
            serials.append(int(match.group(1)))
    next_serial = max(serials, default=0) + 1
    for warehouse in Warehouse.objects.filter(code='').order_by('pk'):
        warehouse.code = f"{prefix}{next_serial:04d}"
        warehouse.save(update_fields=['code'])
        next_serial += 1


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code for this office, e.g. SEH-0001', max_length=20, default=''),
        ),
        migrations.RunPython(backfill_warehouse_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code for this office, e.g. SEH-0001', max_length=20, unique=True),
        ),
    ]
