# Generated by Django 4.2.6 on 2026-07-18 07:49
#
# NOTE: adding `code` with unique=True in a single AddField fails on a table
# that already has Warehouse rows — every existing row gets code='' and the
# unique index then trips on the duplicated empty string. Split into the
# standard three steps: add the column non-unique, backfill a unique code for
# each existing row, then enforce uniqueness.

import re

from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    """Give every existing Warehouse a unique SEH-#### code (mirrors
    Warehouse.next_code / save() so codes stay in the same series)."""
    Warehouse = apps.get_model('inventory', 'Warehouse')
    prefix = 'SEH-'
    serials = []
    for existing in Warehouse.objects.all().values_list('code', flat=True):
        m = re.match(r'^SEH-(\d+)$', existing or '')
        if m:
            serials.append(int(m.group(1)))
    nxt = (max(serials) + 1) if serials else 1
    for w in Warehouse.objects.filter(code='').order_by('id'):
        w.code = f"{prefix}{nxt:04d}"
        w.save(update_fields=['code'])
        nxt += 1


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, editable=False, default='', help_text='Auto-generated code for this office, e.g. SEH-0001', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_codes, noop),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code for this office, e.g. SEH-0001', max_length=20, unique=True),
        ),
    ]
