# Generated by Django 4.2.6 on 2026-07-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_warehouse_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code for this office, e.g. SEH-0001', max_length=20, unique=True),
        ),
    ]
