# Generated by Django 4.2.6 on 2026-07-18 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0012_medicinevaccineentry'),
        ('inventory', '0011_stocktransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='batch_no',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='broiler.broilerbatch'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='broiler.broilerfarm'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='from_location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='broiler.broilerfarm'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='to_location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_out', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Running closing stock of the item at the source location after this transfer', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='inventory.warehouse'),
        ),
    ]
