# Generated by Django 4.2.6 on 2026-07-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0012_medicinevaccineentry'),
        ('inventory', '0012_remove_stocktransfer_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='to_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers_in', to='broiler.broilerbatch'),
        ),
    ]
