# Generated by Django 4.2.6 on 2026-07-18 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_backfill_expense_ledger_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0012_medicinevaccineentry'),
        ('inventory', '0013_stocktransfer_to_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnum', models.CharField(blank=True, editable=False, help_text='Auto-generated transfer number, e.g. MT-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('dc_no', models.CharField(blank=True, max_length=100)),
                ('from_location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10)),
                ('to_location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_out', to='broiler.broilerfarm')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_out', to='inventory.warehouse')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_transfers_paid', to='account.chartofaccount')),
                ('to_farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_in', to='broiler.broilerfarm')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_in', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicineTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Running closing stock of the item at the transfer's source location after this line", max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfer_items', to='inventory.item')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.medicinetransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
