# Generated by Django 4.2.6 on 2026-07-18 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_backfill_expense_ledger_roles'),
        ('inventory', '0014_medicinetransfer_medicinetransferitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnum', models.CharField(blank=True, editable=False, help_text='Auto-generated invoice number, e.g. IA-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='account.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('Add', 'Add'), ('Deduct', 'Deduct')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('stock', models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Running closing stock of the item at the adjustment's warehouse after this line", max_digits=12)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryadjustment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustment_items', to='inventory.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
