# Generated by Django 4.2.6 on 2026-07-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_backfill_expense_ledger_roles'),
        ('broiler', '0012_medicinevaccineentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0016_stockissue_stockissueitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trnum', models.CharField(blank=True, editable=False, help_text='Auto-generated invoice number, e.g. SR-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chart_of_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receives', to='account.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_receives_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receive_items', to='broiler.broilerbatch')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receive_items', to='broiler.broilerfarm')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receive_items', to='inventory.item')),
                ('receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceive')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_receive_items', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
