# Generated by Django 4.2.6 on 2026-07-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0012_medicinevaccineentry'),
        ('inventory', '0017_stockreceive_stockreceiveitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetransfer',
            name='from_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_out', to='broiler.broilerbatch'),
        ),
        migrations.AddField(
            model_name='medicinetransfer',
            name='to_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicine_transfers_in', to='broiler.broilerbatch'),
        ),
    ]
