# Generated by Django 4.2.6 on 2026-07-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broiler', '0012_medicinevaccineentry'),
        ('inventory', '0018_medicinetransfer_from_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='broiler.broilerbatch'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='broiler.broilerfarm'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('farm', 'Farm')], default='warehouse', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentitem',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Running closing stock of the item at the adjustment's location after this line", max_digits=12),
        ),
    ]
