# Generated by Django 4.2.6 on 2026-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inventoryadjustment_batch_inventoryadjustment_farm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kilogram, Piece, Litre', max_length=100, unique=True)),
                ('symbol', models.CharField(blank=True, help_text='Short form, e.g. Kg, Pcs, Ltr', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
