# Generated by Django 4.2.6 on 2026-07-18 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_item_warehouse_to_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_entries', to='inventory.item')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
                'unique_together': {('item', 'effective_date')},
            },
        ),
    ]
