# Generated by Django 4.2.6 on 2026-07-19 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0005_hatchery_warehouse'),
        ('inventory', '0024_itemcategory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='source_hatchery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_sourced', to='hatchery_master.hatchery'),
        ),
    ]
