# Generated by Django 4.2.6 on 2026-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_stocktransfer_source_hatchery'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='chicks_ordered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='culls',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='shortage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='transit_mortality',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
