# Generated by Django 4.2.6 on 2026-07-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_stocktransfer_chicks_ordered_stocktransfer_culls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated code for this item, e.g. ITM-0001', max_length=100, unique=True),
        ),
    ]
