# Generated by Django 4.2.6 on 2026-07-20 05:58

from django.db import migrations, models


def backfill_sector_branch_mappings(apps, schema_editor):
    Warehouse = apps.get_model("inventory", "Warehouse")
    Mapping = apps.get_model("inventory", "Mapping")
    Mapping.objects.bulk_create([
        Mapping(type="sector_branch", from_id=warehouse_id, to_id=branch_id)
        for warehouse_id, branch_id in Warehouse.objects.filter(
            branch__isnull=False
        ).values_list("id", "branch_id")
    ])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_item_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sector_branch', 'Sector → Branch'), ('hatchery_office', 'Hatchery → Office')], max_length=30)),
                ('from_id', models.PositiveIntegerField()),
                ('to_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mapping',
            constraint=models.UniqueConstraint(fields=('type', 'from_id'), name='unique_mapping_per_type_from'),
        ),
        migrations.RunPython(backfill_sector_branch_mappings, noop),
        migrations.RemoveField(
            model_name='warehouse',
            name='branch',
        ),
    ]
