# Generated by Django 4.2.6 on 2026-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_mapping_remove_warehouse_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping',
            name='type',
            field=models.CharField(choices=[('sector_branch', 'Sector → Branch'), ('hatchery_office', 'Hatchery → Office'), ('office_cost_center', 'Office → Cost Center')], max_length=30),
        ),
    ]
