# Generated by Django 4.2.6 on 2026-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_organization_centre_type_sectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valuation_method',
            field=models.CharField(choices=[('Weighted Average', 'Weighted Average'), ('Standard Costing', 'Standard Costing'), ('FIFO', 'FIFO (First In, First Out)'), ('LIFO', 'LIFO (Last In, First Out)'), ('FEFO', 'FEFO (First Expiry, First Out)')], max_length=50),
        ),
    ]
