# Generated by Django 4.2.6 on 2026-07-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_chicks_purchase_single_free_percent'),
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='source_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_sourced', to='purchase.supplier'),
        ),
    ]
