# Generated by Django 4.2.6 on 2026-09-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0035_stocktransfer_source_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceListAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_entry_ref', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('item_ref', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('item_label', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_effective_date', models.DateField(blank=True, null=True)),
                ('new_effective_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user_label', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
