# Generated by Django 4.2.6 on 2026-09-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_item_price_list_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
