# Generated by Django 4.2.6 on 2026-10-01 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_pettyexpense_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('broiler', '0079_broilerfarmshed_space_per_bird'),
        ('inventory', '0038_item_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('capitalize_ledger', models.ForeignKey(blank=True, help_text='Debited when a charge of this type is posted as Add to Inventory Cost', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charge_types_capitalize', to='account.chartofaccount')),
                ('expense_ledger', models.ForeignKey(blank=True, help_text='Debited when a charge of this type is posted as Expense Only', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charge_types_expense', to='account.chartofaccount')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransferChargeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_no', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated, e.g. TC-2026-00001', max_length=30)),
                ('charge_date', models.DateField(default=django.utils.timezone.now)),
                ('dc_no', models.CharField(help_text='DC / trip reference shared by the linked Stock Transfer rows', max_length=100)),
                ('treatment', models.CharField(choices=[('Expense Only', 'Expense Only'), ('Add to Inventory Cost', 'Add to Inventory Cost')], default='Expense Only', max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('total_transport', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loading', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_other', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('narration', models.TextField(blank=True)),
                ('header_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charges_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_charges', to='account.companyprofile')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charges', to='account.organizationcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charges_created', to=settings.AUTH_USER_MODEL)),
                ('paid_from', models.ForeignKey(blank=True, help_text='The cash/bank account the money left, where paid directly', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charges', to='account.bankcashmaster')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charges_posted', to=settings.AUTH_USER_MODEL)),
                ('stock_transfers', models.ManyToManyField(blank=True, related_name='transfer_charges', to='inventory.stocktransfer')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charge_source', to='account.voucher')),
            ],
            options={
                'ordering': ['-charge_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferChargeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('charge_scope', models.CharField(choices=[('Common', 'Common / Fixed'), ('Farm-wise', 'Farm-wise')], default='Common', max_length=20)),
                ('basis', models.CharField(blank=True, default='Fixed', help_text='How the Total Amount was arrived at, e.g. Fixed, Fixed / Trip', max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Common/Fixed only — ignored for Farm-wise lines', max_digits=14)),
                ('allocation_method', models.CharField(choices=[('Equal', 'Equal'), ('By Quantity', 'By Quantity'), ('By Stock Value', 'By Stock Value'), ('By Distance', 'By Distance'), ('Manual', 'Manual')], default='Equal', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charge_lines', to='inventory.chargetype')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.transferchargeheader')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransferChargeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transfer_charges/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.transferchargeheader')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_charge_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransferChargeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_value_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('distance_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('destination_farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charge_allocations', to='broiler.broilerfarm')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.transferchargeline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='transferchargeheader',
            constraint=models.UniqueConstraint(fields=('company', 'charge_no'), name='uniq_transfer_charge_no'),
        ),
        migrations.AddConstraint(
            model_name='transferchargeallocation',
            constraint=models.UniqueConstraint(fields=('line', 'destination_farm'), name='uniq_allocation_per_farm_per_line'),
        ),
    ]
