# Generated by Django 4.2.6 on 2026-10-02 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_pettyexpense_batch'),
        ('inventory', '0040_seed_charge_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferchargeheader',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='Pay Later only — the payable/liability ledger credited', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charges_payable', to='account.chartofaccount'),
        ),
        migrations.AddField(
            model_name='transferchargeheader',
            name='payee_name',
            field=models.CharField(blank=True, help_text='Pay Later only — who this is owed to, as it should read on the voucher', max_length=150),
        ),
        migrations.AddField(
            model_name='transferchargeheader',
            name='payment_mode',
            field=models.CharField(choices=[('Paid Now', 'Paid Now'), ('Pay Later', 'Pay Later')], default='Paid Now', help_text='Paid Now credits a Cash/Bank account; Pay Later credits a payable ledger', max_length=20),
        ),
        migrations.AlterField(
            model_name='transferchargeheader',
            name='paid_from',
            field=models.ForeignKey(blank=True, help_text='Paid Now only — the cash/bank account the money left', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_charges', to='account.bankcashmaster'),
        ),
    ]
