# Generated by Django 4.2.6 on 2026-07-08 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_no', models.CharField(help_text='Batch id for this hatch setting (e.g. 44)', max_length=50, unique=True)),
                ('batch_flock_no', models.CharField(blank=True, help_text='Batch / Flock number (e.g. 0806/01)', max_length=50)),
                ('supplier_name', models.CharField(help_text='Supplier of the eggs for this setting', max_length=150)),
                ('primary_machine_nos', models.CharField(blank=True, help_text='Primary setter machine numbers (e.g. 39,40,41,42)', max_length=100)),
                ('received_date', models.DateField(help_text='Date eggs were received')),
                ('received_time', models.TimeField(blank=True, help_text='Time eggs were received', null=True)),
                ('setting_date', models.DateField(help_text='Date eggs were set')),
                ('transfer_date', models.DateField(blank=True, help_text='Date of hatcher transfer', null=True)),
                ('hatch_date', models.DateField(blank=True, help_text='Date of hatch', null=True)),
                ('push_time', models.TimeField(blank=True, help_text='Chick pull/push time', null=True)),
                ('setter_temperature', models.CharField(blank=True, help_text='e.g. 99F', max_length=20)),
                ('setter_humidity', models.CharField(blank=True, help_text='e.g. 60%', max_length=20)),
                ('hatcher_temperature', models.CharField(blank=True, help_text='e.g. 98.5F', max_length=20)),
                ('hatcher_humidity', models.CharField(blank=True, help_text='e.g. 70%', max_length=20)),
                ('avg_chick_weight', models.CharField(blank=True, help_text='e.g. CHICKS WT 38-40 GM', max_length=50)),
                ('medicine_vaccine', models.CharField(blank=True, max_length=150)),
                ('packing_boxes_used', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, help_text='Operator name', max_length=100)),
                ('verified_by', models.CharField(blank=True, help_text='Hatchery Manager name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hatch Setting',
                'verbose_name_plural': 'Hatch Settings',
                'ordering': ['-setting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HatchSalesLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trader_customer_name', models.CharField(max_length=150)),
                ('chicks_sold', models.PositiveIntegerField(default=0)),
                ('free_chicks', models.PositiveIntegerField(default=0)),
                ('billed_chicks', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('delivery_notes', models.CharField(blank=True, max_length=200)),
                ('hatch_setting', models.ForeignKey(help_text='Hatch setting this sale row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sales_lines', to='hatchery.hatchsetting')),
            ],
            options={
                'verbose_name': 'Hatch Sales Line',
                'verbose_name_plural': 'Hatch Sales Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HatchHatcherOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatcher_no', models.CharField(max_length=50)),
                ('infertile_qty', models.PositiveIntegerField(default=0)),
                ('early_dead_qty', models.PositiveIntegerField(default=0)),
                ('blasting_qty', models.PositiveIntegerField(default=0)),
                ('transfer_qty', models.PositiveIntegerField(default=0)),
                ('dead_in_shell_qty', models.PositiveIntegerField(default=0)),
                ('culls_malf_qty', models.PositiveIntegerField(default=0)),
                ('saleable_chicks', models.PositiveIntegerField(default=0)),
                ('hatch_setting', models.ForeignKey(help_text='Hatch setting this hatcher output row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='hatcher_outputs', to='hatchery.hatchsetting')),
            ],
            options={
                'verbose_name': 'Hatcher Output Row',
                'verbose_name_plural': 'Hatcher Output Rows',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HatchEggIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_lot_flock', models.CharField(blank=True, max_length=50)),
                ('setter_no', models.CharField(max_length=50)),
                ('received_qty', models.PositiveIntegerField(default=0)),
                ('breakage_qty', models.PositiveIntegerField(default=0)),
                ('crack_qty', models.PositiveIntegerField(default=0)),
                ('setting_qty', models.PositiveIntegerField(default=0)),
                ('no_trays', models.PositiveIntegerField(blank=True, null=True)),
                ('tray_size', models.PositiveIntegerField(blank=True, null=True)),
                ('total_eggs', models.PositiveIntegerField(blank=True, null=True)),
                ('hatch_setting', models.ForeignKey(help_text='Hatch setting this egg intake row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='egg_intakes', to='hatchery.hatchsetting')),
            ],
            options={
                'verbose_name': 'Egg Intake Row',
                'verbose_name_plural': 'Egg Intake Rows',
                'ordering': ['id'],
            },
        ),
    ]
