# Generated by Django 4.2.6 on 2026-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatcheggintake',
            name='breakage_qty',
        ),
        migrations.RemoveField(
            model_name='hatcheggintake',
            name='crack_qty',
        ),
        migrations.RemoveField(
            model_name='hatcheggintake',
            name='received_qty',
        ),
        migrations.RemoveField(
            model_name='hatcheggintake',
            name='setting_qty',
        ),
        migrations.AddField(
            model_name='hatchsetting',
            name='breakage_qty',
            field=models.PositiveIntegerField(default=0, help_text='Total broken eggs for this lot'),
        ),
        migrations.AddField(
            model_name='hatchsetting',
            name='crack_qty',
            field=models.PositiveIntegerField(default=0, help_text='Total cracked eggs for this lot'),
        ),
        migrations.AddField(
            model_name='hatchsetting',
            name='received_qty',
            field=models.PositiveIntegerField(default=0, help_text='Total eggs received for this lot'),
        ),
        migrations.AddField(
            model_name='hatchsetting',
            name='setting_qty',
            field=models.PositiveIntegerField(default=0, help_text='Net eggs actually set (received minus breakage/crack)'),
        ),
    ]
