# Generated by Django 4.2.6 on 2026-07-11 11:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('purchase', '0004_remove_purchaseorderlineitem_category_and_more'),
        ('account', '0003_coacategory'),
        ('hatchery', '0002_remove_hatcheggintake_breakage_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number for this egg purchase', max_length=30, unique=True)),
                ('date', models.DateField(help_text='Date of purchase')),
                ('dc_no', models.CharField(blank=True, help_text='Delivery challan number', max_length=50)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('freight_type', models.CharField(choices=[('Include', 'Include'), ('Exclude', 'Exclude')], default='Exclude', max_length=10)),
                ('payment_mode', models.CharField(choices=[('pay_later', 'Pay Later'), ('pay_in_bill', 'Pay In Bill')], default='pay_later', max_length=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tcs_applicable', models.BooleanField(default=False, help_text='Whether TCS applies to this purchase')),
                ('tcs_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freight_account', models.ForeignKey(blank=True, help_text='Account freight is booked against', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchase_freight_accounts', to='account.chartofaccount')),
                ('pay_account', models.ForeignKey(help_text='Account this purchase is paid from', on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchase_pay_accounts', to='account.chartofaccount')),
                ('supplier', models.ForeignKey(help_text='Supplier the eggs were purchased from', on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchases', to='purchase.supplier')),
                ('warehouse', models.ForeignKey(help_text='Farm/Warehouse the eggs were received at', on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchases', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Egg Purchase',
                'verbose_name_plural': 'Egg Purchases',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rcv_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_of_boxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('egg_purchase', models.ForeignKey(help_text='Egg purchase this item row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hatchery.eggpurchase')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchase_items', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Egg Purchase Item',
                'verbose_name_plural': 'Egg Purchase Items',
                'ordering': ['id'],
            },
        ),
    ]
