# Generated by Django 4.2.6 on 2026-07-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchaseorderlineitem_category_and_more'),
        ('inventory', '0002_rename_category_itemcategory'),
        ('hatchery', '0003_eggpurchase_eggpurchaseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number for this egg grading', max_length=30, unique=True)),
                ('date', models.DateField(help_text='Date of grading/receiving')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity taken for grading', max_digits=10)),
                ('broken_eggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_eggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misshapped_eggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dirty_eggs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(help_text='Item being graded', on_delete=django.db.models.deletion.PROTECT, related_name='egg_gradings', to='inventory.item')),
                ('purchase_invoice', models.ForeignKey(help_text='Egg purchase invoice these eggs are being graded from', on_delete=django.db.models.deletion.PROTECT, related_name='gradings', to='hatchery.eggpurchase')),
                ('storage_location', models.ForeignKey(help_text='Storage location the graded eggs are received into', on_delete=django.db.models.deletion.PROTECT, related_name='egg_gradings', to='inventory.warehouse')),
                ('supplier', models.ForeignKey(help_text='Supplier of the eggs being graded', on_delete=django.db.models.deletion.PROTECT, related_name='egg_gradings', to='purchase.supplier')),
            ],
            options={
                'verbose_name': 'Egg Grading',
                'verbose_name_plural': 'Egg Gradings',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggGradingHatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egg_grading', models.ForeignKey(help_text='Egg grading this hatch item row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='hatch_items', to='hatchery.egggrading')),
                ('hatch_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_grading_hatch_items', to='inventory.item')),
            ],
            options={
                'verbose_name': 'Egg Grading Hatch Item',
                'verbose_name_plural': 'Egg Grading Hatch Items',
                'ordering': ['id'],
            },
        ),
    ]
