# Generated by Django 4.2.6 on 2026-07-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0004_egggrading_egggradinghatchitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatchsetting',
            name='batch_flock_no',
            field=models.CharField(blank=True, editable=False, help_text="Auto-generated batch/flock number: DDMM of today, plus today's sequence (e.g. 0806/01)", max_length=50),
        ),
    ]
