# Generated by Django 4.2.6 on 2026-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0005_alter_hatchsetting_batch_flock_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchsetting',
            name='avg_egg_weight',
            field=models.CharField(blank=True, help_text='e.g. EGG WT 55-58 GM', max_length=50),
        ),
        migrations.AlterField(
            model_name='hatchsetting',
            name='avg_chick_weight',
            field=models.CharField(blank=True, help_text='Avg Chicks Weight, e.g. CHICKS WT 38-40 GM', max_length=50),
        ),
    ]
