# Generated by Django 4.2.6 on 2026-07-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0006_hatchsetting_avg_egg_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchsalesline',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Free-chick bonus % baked into Chicks Sold', max_digits=5),
        ),
        migrations.AlterField(
            model_name='hatchsalesline',
            name='chicks_sold',
            field=models.PositiveIntegerField(default=0, help_text='Total chicks dispatched, inclusive of the free-chick bonus (e.g. 102 = 100 + 2%)'),
        ),
    ]
