# Generated by Django 4.2.6 on 2026-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0008_deliverychallan_deliverychallanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='billed_distance',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='overall_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
    ]
