# Generated by Django 4.2.6 on 2026-07-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0009_deliverychallan_billed_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallan',
            name='billed_distance',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='reverse_charge',
        ),
    ]
