# Generated by Django 4.2.6 on 2026-07-15 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery_master', '0004_expensetype_hatcheryexpense'),
        ('inventory', '0002_rename_category_itemcategory'),
        ('purchase', '0005_delete_termsconditions'),
        ('hr', '0025_delete_sector'),
        ('hatchery', '0010_remove_deliverychallan_billed_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_no', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('setting_date', models.DateField()),
                ('hatch_date', models.DateField(help_text='Expected hatch date, typically setting date + 21 days')),
                ('setting_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tray_settings', to='hatchery.egggrading')),
                ('hatchery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tray_settings', to='hatchery_master.hatchery')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tray_settings', to='hr.employee')),
            ],
            options={
                'ordering': ['-setting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TraySettingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eggs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('broken', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damaged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eggs_set', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_weight', models.DecimalField(decimal_places=2, default=0, help_text='Average egg weight', max_digits=10)),
                ('expected_chicks', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tray_setting_lines', to='inventory.item')),
                ('setter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tray_setting_lines', to='hatchery_master.setter')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tray_setting_lines', to='purchase.supplier')),
                ('tray_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hatchery.traysetting')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
