# Generated by Django 4.2.6 on 2026-07-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('hatchery', '0011_traysetting_traysettingline'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('eggs_total', models.DecimalField(decimal_places=2, default=0, help_text='No. of eggs set (snapshot from tray setting)', max_digits=12)),
                ('egg_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eggs_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('chicks_total', models.DecimalField(decimal_places=2, default=0, help_text='Saleable chicks hatched', max_digits=12)),
                ('chick_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chicks_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_rate', models.DecimalField(decimal_places=2, default=0, help_text='Net cost per chick', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Eggs amount + vaccine consumption', max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tray_setting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hatch_entry', to='hatchery.traysetting')),
            ],
            options={
                'verbose_name_plural': 'Hatch entries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HatchEntryVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('hatch_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='hatchery.hatchentry')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hatch_entry_vaccines', to='inventory.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
