# Generated by Django 4.2.6 on 2026-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0012_hatchentry_hatchentryvaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='traysetting',
            name='transfer_date',
            field=models.DateField(blank=True, help_text='Hatcher transfer date, typically setting date + 18 days', null=True),
        ),
    ]
