# Generated by Django 4.2.6 on 2026-07-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0013_traysetting_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traysetting',
            name='loaded_by',
            field=models.CharField(blank=True, default='', help_text='Who loaded the trays; pick an employee or type any name', max_length=100),
        ),
    ]
