# Generated by Django 4.2.6 on 2026-07-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_category_itemcategory'),
        ('sales', '0005_customer_aadhar_customer_account_no_and_more'),
        ('account', '0005_termsconditions'),
        ('hatchery', '0014_alter_traysetting_loaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('date', models.DateField()),
                ('shipping_address', models.TextField(blank=True)),
                ('vehicle', models.CharField(blank=True, max_length=50)),
                ('driver', models.CharField(blank=True, max_length=100)),
                ('freight_type', models.CharField(choices=[('Paid by Customer', 'Paid by Customer'), ('Include in Bill', 'Include in Bill')], default='Paid by Customer', max_length=20)),
                ('payment_mode', models.CharField(choices=[('pay_later', 'Pay Later'), ('pay_in_bill', 'Pay In Bill')], default='pay_later', max_length=15)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_amount', models.DecimalField(decimal_places=2, default=0, help_text='Average realised rate per bird', max_digits=12)),
                ('profit_amount', models.DecimalField(decimal_places=2, default=0, help_text='Sale value minus chick cost (latest hatch entry net rate)', max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chick_sales', to='sales.customer')),
                ('delivery_challan', models.ForeignKey(blank=True, help_text='Delivery challan this sale was converted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chick_sales', to='hatchery.deliverychallan')),
                ('freight_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chick_sale_freight_accounts', to='account.chartofaccount')),
                ('pay_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chick_sale_pay_accounts', to='account.chartofaccount')),
                ('warehouse', models.ForeignKey(help_text='Stock point / feed mill the chicks are sold from', on_delete=django.db.models.deletion.PROTECT, related_name='chick_sales', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ChickSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.CharField(blank=True, max_length=150)),
                ('total_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mortality', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('culls', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chick_sale_items', to='inventory.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hatchery.chicksale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
