# Generated by Django 4.2.6 on 2026-07-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0015_chicksale_chicksaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicksaleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chicksaleitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chicksaleitem',
            name='sale_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chicksaleitem',
            name='net_qty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Billed quantity', max_digits=12),
        ),
    ]
