# Generated by Django 4.2.6 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0016_chicksaleitem_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatchentry',
            name='hatch_date',
            field=models.DateField(blank=True, help_text="Actual hatch date; may differ from the tray setting's expected date", null=True),
        ),
    ]
