# Generated by Django 4.2.6 on 2026-07-15 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hatchery', '0017_hatchentry_hatch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='Handler key, e.g. delivery_challan', max_length=40)),
                ('object_id', models.PositiveIntegerField()),
                ('object_label', models.CharField(blank=True, help_text='Human label, e.g. the transaction number', max_length=100)),
                ('action', models.CharField(choices=[('edit', 'Modification'), ('delete', 'Deletion')], max_length=10)),
                ('payload', models.JSONField(blank=True, help_text='Proposed new values (edit requests)', null=True)),
                ('note', models.TextField(blank=True, help_text="Requester's reason/remarks")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
