# Generated by Django 4.2.6 on 2026-07-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0018_changerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicksale',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
