# Generated by Django 4.2.6 on 2026-07-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0019_chicksale_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='traysettingline',
            name='no_trays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traysettingline',
            name='tray_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traysettingline',
            name='broken',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy field — broken/damaged eggs are tracked in Egg Grading, not re-entered per tray-set line', max_digits=12),
        ),
    ]
