# Generated by Django 4.2.6 on 2026-07-21 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0020_traysettingline_no_trays_traysettingline_tray_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatchEntryHatcherOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatcher_no', models.CharField(max_length=50)),
                ('infertile_qty', models.PositiveIntegerField(default=0)),
                ('early_dead_qty', models.PositiveIntegerField(default=0)),
                ('blasting_qty', models.PositiveIntegerField(default=0)),
                ('transfer_qty', models.PositiveIntegerField(default=0)),
                ('dead_in_shell_qty', models.PositiveIntegerField(default=0)),
                ('culls_malf_qty', models.PositiveIntegerField(default=0)),
                ('saleable_chicks', models.PositiveIntegerField(default=0)),
                ('hatch_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatcher_outputs', to='hatchery.hatchentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
