# Generated by Django 4.2.6 on 2026-07-21 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0023_hatcheroutput_hatcher_fk_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggpurchaseitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eggpurchaseitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate per unit (Rcv Qty, or Sent Qty if none received) — Amount is derived from this', max_digits=10),
        ),
    ]
