# Generated by Django 4.2.6 on 2026-08-10 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
        ('hatchery', '0025_chicksalereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggpurchase',
            name='pay_account',
            field=models.ForeignKey(blank=True, help_text='Account this purchase is paid from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_purchase_pay_accounts', to='account.chartofaccount'),
        ),
    ]
