# Generated by Django 4.2.6 on 2026-08-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0026_alter_eggpurchase_pay_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicksale',
            name='payment_mode',
            field=models.CharField(choices=[('pay_later', 'Credit / Pay Later'), ('pay_in_bill', 'Paid')], default='pay_later', max_length=15),
        ),
        migrations.AlterField(
            model_name='eggpurchase',
            name='payment_mode',
            field=models.CharField(choices=[('pay_later', 'Credit / Pay Later'), ('pay_in_bill', 'Paid')], default='pay_later', max_length=15),
        ),
    ]
