# Generated by Django 4.2.6 on 2026-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0028_hatchsetting_unique_hatch_setting_batch_flock_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicksalereceipt',
            name='mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
