# Generated by Django 4.2.6 on 2026-07-19 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_create', 'Bulk Create'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('status_change', 'Status Change'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('file_upload', 'File Upload'), ('file_delete', 'File Delete'), ('custom', 'Custom Business Event')], db_index=True, max_length=32)),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_display', models.CharField(blank=True, max_length=255)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['model_name', 'object_id', '-created_at'], name='alerts_audi_model_n_b7a88b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('bulk_create', 'Bulk Create'), ('bulk_update', 'Bulk Update'), ('bulk_delete', 'Bulk Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('status_change', 'Status Change'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('file_upload', 'File Upload'), ('file_delete', 'File Delete'), ('custom', 'Custom Business Event')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_display', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=64)),
                ('device', models.CharField(blank=True, max_length=64)),
                ('os', models.CharField(blank=True, max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='alerts_aler_model_n_adc304_idx'), models.Index(fields=['performed_by', '-created_at'], name='alerts_aler_perform_7be337_idx'), models.Index(fields=['is_read', '-created_at'], name='alerts_aler_is_read_be931c_idx')],
            },
        ),
    ]
