# Generated by Django 4.2.6 on 2026-07-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable identifier used by field bindings', unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'Party Category'", max_length=150)),
                ('source_type', models.CharField(choices=[('STATIC', 'Static List'), ('MODEL', 'From Another Master')], default='STATIC', max_length=10)),
                ('source_model_key', models.CharField(blank=True, help_text='Key into PICKLIST_SOURCE_MODELS; required when source_type=MODEL', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PicklistValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Stored value', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Display label; defaults to value', max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='picklist.picklist')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldPicklistBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('FREE_TEXT', 'Free Text'), ('PICKLIST', 'Picklist')], default='FREE_TEXT', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bindings', to='picklist.picklist')),
            ],
            options={
                'ordering': ['app_label', 'model_name', 'field_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='picklistvalue',
            constraint=models.UniqueConstraint(fields=('picklist', 'value'), name='uniq_picklist_value'),
        ),
        migrations.AddConstraint(
            model_name='fieldpicklistbinding',
            constraint=models.UniqueConstraint(fields=('app_label', 'model_name', 'field_name'), name='uniq_field_binding'),
        ),
    ]
