# Generated by Django 4.2.6 on 2026-07-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='model_scope',
            field=models.CharField(choices=[('ALL', 'All'), ('LIMITED', 'Limited to Selected')], default='ALL', help_text='Only meaningful when source_type=MODEL: use every source row, or a hand-picked subset', max_length=10),
        ),
        migrations.CreateModel(
            name='PicklistSourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_value', models.CharField(max_length=100)),
                ('picklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_items', to='picklist.picklist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='picklistsourceitem',
            constraint=models.UniqueConstraint(fields=('picklist', 'source_value'), name='uniq_picklist_source_item'),
        ),
    ]
