# Generated by Django 4.2.6 on 2026-07-13 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hatchery_master', '0004_expensetype_hatcheryexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Label, e.g. 'Setter Room 1'", max_length=100)),
                ('alias', models.CharField(blank=True, help_text='Alias reported by the device', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='Current LAN IP address')),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('device_id', models.CharField(help_text='Stable Tapo device id (survives IP changes from DHCP)', max_length=64, unique=True)),
                ('model', models.CharField(default='H100', max_length=30)),
                ('firmware_version', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('signal_strength', models.IntegerField(blank=True, help_text='RSSI', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive hubs are skipped by polling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hub',
                'verbose_name_plural': 'Hubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PollLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('is_running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Poll lock',
                'verbose_name_plural': 'Poll lock',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('t310', 'T310 Temperature & Humidity')], default='t310', max_length=20)),
                ('device_id', models.CharField(help_text='Tapo child device id', max_length=64, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(default='T310', max_length=30)),
                ('alias', models.CharField(blank=True, help_text='User-facing label', max_length=100)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, help_text='RSSI', null=True)),
                ('last_update', models.DateTimeField(blank=True, help_text='Last successful read from the device', null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('calibration_offset_temp', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('calibration_offset_humidity', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_low_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='environmental_monitoring.hub')),
                ('setter', models.ForeignKey(blank=True, help_text='Setter this sensor is physically placed in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='hatchery_master.setter')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensors',
                'ordering': ['hub__name', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temp_high', 'Temperature High'), ('temp_low', 'Temperature Low'), ('humidity_high', 'Humidity High'), ('humidity_low', 'Humidity Low'), ('battery_low', 'Battery Low'), ('sensor_offline', 'Sensor Offline'), ('hub_offline', 'Hub Offline')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='environmental_monitoring.hub')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='environmental_monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('temperature_c', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('humidity_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('battery_pct', models.PositiveSmallIntegerField(null=True)),
                ('signal_strength', models.IntegerField(null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='environmental_monitoring.hub')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='environmental_monitoring.sensor')),
            ],
            options={
                'verbose_name': 'Sensor reading',
                'verbose_name_plural': 'Sensor readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='environment_sensor__6ae15e_idx')],
            },
        ),
    ]
