# Generated by Django 4.2.6 on 2026-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TapoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Tapo account email', max_length=254)),
                ('password', models.CharField(blank=True, help_text='Tapo account password', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tapo Account',
                'verbose_name_plural': 'Tapo Account',
            },
        ),
    ]
