# Generated by Django 4.2.6 on 2026-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitoring', '0002_tapoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='api_token',
            field=models.CharField(blank=True, editable=False, help_text='Secret token an on-site collector script uses to push readings for this hub', max_length=64, unique=True),
        ),
    ]
