# Generated by Django 4.2.6 on 2026-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitoring', '0003_hub_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_alarm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_alarm_event',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
