# Generated by Django 4.2.6 on 2026-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental_monitoring', '0004_sensor_last_alarm_at_sensor_last_alarm_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertThresholdDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.DecimalField(decimal_places=2, default=35, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=2, default=38, max_digits=5)),
                ('humidity_min', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('humidity_max', models.DecimalField(decimal_places=2, default=65, max_digits=5)),
                ('battery_low_pct', models.PositiveSmallIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default Alert Thresholds',
                'verbose_name_plural': 'Default Alert Thresholds',
            },
        ),
    ]
