# Generated by Django 4.2.6 on 2026-07-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchaseorderlineitem_category_and_more'),
        ('sales', '0005_customer_aadhar_customer_account_no_and_more'),
        ('inventory', '0002_rename_category_itemcategory'),
        ('broiler', '0008_alter_farmer_farmer_group'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('admin', 'Admin'), ('sub_admin', 'Sub-Admin')], default='sub_admin', max_length=10)),
                ('login_type', models.CharField(choices=[('password', 'Password'), ('otp', 'OTP')], default='password', max_length=10)),
                ('sale_multiple_edit', models.BooleanField(default=False)),
                ('sale_multiple_delete', models.BooleanField(default=False)),
                ('dashboard', models.BooleanField(default=True)),
                ('all_branches', models.BooleanField(default=True)),
                ('all_lines', models.BooleanField(default=True)),
                ('all_farms', models.BooleanField(default=True)),
                ('all_sectors', models.BooleanField(default=True)),
                ('all_customer_groups', models.BooleanField(default=True)),
                ('all_supplier_groups', models.BooleanField(default=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='access_profiles', to='broiler.branch')),
                ('customer_groups', models.ManyToManyField(blank=True, related_name='access_profiles', to='sales.customergroup')),
                ('farms', models.ManyToManyField(blank=True, related_name='access_profiles', to='broiler.broilerfarm')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to='auth.group')),
                ('lines', models.ManyToManyField(blank=True, related_name='access_profiles', to='broiler.broilerline')),
                ('sectors', models.ManyToManyField(blank=True, related_name='access_profiles', to='inventory.warehouse')),
                ('supplier_groups', models.ManyToManyField(blank=True, related_name='access_profiles', to='purchase.vendorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTabPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_code', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_favorite', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group tab permission',
                'unique_together': {('group', 'tab_code')},
            },
        ),
    ]
