# Generated by Django 4.2.6 on 2026-07-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groupaccessprofile_grouptabpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptabpermission',
            name='can_save',
            field=models.BooleanField(default=False),
        ),
    ]
