# Generated by Django 4.2.6 on 2026-07-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_grouptabpermission_can_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupaccessprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
