# Generated by Django 4.2.6 on 2026-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_cost_center_tab_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('verdict', models.CharField(choices=[('unmapped', 'Unmapped'), ('denied', 'Denied')], db_index=True, max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('view', models.CharField(blank=True, help_text='Dotted path of the view that served it', max_length=200)),
                ('tab_code', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('hits', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Web access audit',
                'verbose_name_plural': 'Web access audit',
                'ordering': ['url_name', 'username'],
                'unique_together': {('url_name', 'method', 'verdict', 'username')},
            },
        ),
    ]
