# Generated by Django 4.2.6 on 2026-08-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0007_groupdashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMobileAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(help_text='Key from user.services.mobile_access.MOBILE_MODULES', max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_modules', to='auth.group')),
            ],
            options={
                'verbose_name': 'Mobile module access',
                'verbose_name_plural': 'Mobile module access',
                'ordering': ['position', 'module_key'],
                'unique_together': {('group', 'module_key')},
            },
        ),
    ]
