# Generated by Django 4.2.6 on 2026-08-02 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0008_groupmobileaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('web', 'Web Access'), ('mobile', 'Mobile screen access'), ('mobile_module', 'Mobile module access'), ('dashboard', 'Dashboard Access')], db_index=True, max_length=20)),
                ('changed_by', models.CharField(max_length=150)),
                ('summary', models.CharField(help_text='Human-readable description of the change', max_length=300)),
                ('detail', models.JSONField(blank=True, default=dict, help_text="{'before': …, 'after': …} for the keys that moved")),
                ('source', models.CharField(default='web', help_text='web or mobile — where the edit was made', max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_changes', to='auth.group')),
            ],
            options={
                'verbose_name': 'Access change',
                'verbose_name_plural': 'Access changes',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMobileTabPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_code', models.CharField(help_text='Tab code from user.services.mobile_access.PHONE_SCREENS', max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tab_permissions', to='auth.group')),
            ],
            options={
                'verbose_name': 'Mobile screen permission',
                'verbose_name_plural': 'Mobile screen permissions',
                'ordering': ['tab_code'],
                'unique_together': {('group', 'tab_code')},
            },
        ),
    ]
