# Generated by Django 4.2.6 on 2026-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_accesschangelog_groupmobiletabpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschangelog',
            name='surface',
            field=models.CharField(choices=[('web', 'Web Access'), ('mobile', 'Mobile screen access'), ('mobile_module', 'Mobile module access'), ('dashboard', 'Dashboard Access'), ('membership', 'Group membership')], db_index=True, max_length=20),
        ),
    ]
