# Generated by Django 4.2.6 on 2026-08-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_accesschangelog_surface'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessChangeLog',
        ),
    ]
