# Generated by Django 4.2.6 on 2026-08-06 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
        ('hr', '0030_employeevehicle_supervisortrip_supervisortripvisit_and_more'),
        ('inventory', '0035_stocktransfer_source_supplier'),
        ('broiler', '0054_alter_birdsale_amount_alter_birdsale_round_off'),
        ('user', '0011_delete_accesschangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_companies', models.BooleanField(default=True)),
                ('all_branches', models.BooleanField(default=True)),
                ('all_warehouses', models.BooleanField(default=True)),
                ('all_farms', models.BooleanField(default=True)),
                ('all_sheds', models.BooleanField(default=True)),
                ('all_cost_centres', models.BooleanField(default=True)),
                ('batch_visibility', models.CharField(choices=[('all', 'All Batches'), ('active', 'Active Batches Only'), ('selected', 'Selected Batches')], default='all', help_text='Active Batches Only hides settled flocks without naming any.', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batches', models.ManyToManyField(blank=True, help_text="Only read when batch visibility is 'Selected Batches'.", related_name='employee_profiles', to='broiler.broilerbatch')),
                ('branches', models.ManyToManyField(blank=True, related_name='employee_profiles', to='broiler.branch')),
                ('companies', models.ManyToManyField(blank=True, related_name='employee_profiles', to='account.companyprofile')),
                ('cost_centres', models.ManyToManyField(blank=True, related_name='employee_profiles', to='account.organizationcentre')),
                ('employee', models.OneToOneField(help_text="Whose scope this is. The login is reached through the employee's user link.", on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to='hr.employee')),
                ('farms', models.ManyToManyField(blank=True, related_name='employee_profiles', to='broiler.broilerfarm')),
                ('sheds', models.ManyToManyField(blank=True, related_name='employee_profiles', to='broiler.broilerfarmshed')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_access_profiles_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouses', models.ManyToManyField(blank=True, related_name='employee_profiles', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Employee Organization Access',
                'verbose_name_plural': 'Employee Organization Access',
                'ordering': ['employee__full_name'],
            },
        ),
    ]
