# Generated by Django 4.2.6 on 2026-08-06 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0012_employeeaccessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='individual_permissions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTabPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_code', models.CharField(max_length=100)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('can_save', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User tab permission',
                'unique_together': {('user', 'tab_code')},
            },
        ),
    ]
