# Generated by Django 4.2.6 on 2026-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_split_balances_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 0.2.1', max_length=20)),
                ('version_code', models.PositiveIntegerField(help_text='Android versionCode — must increase with every release', unique=True)),
                ('apk_file', models.FileField(upload_to='app-releases/')),
                ('force_update', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_code'],
            },
        ),
    ]
