# Generated by Django 4.2.6 on 2026-09-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_apprelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nav_layout',
            field=models.CharField(choices=[('top', 'Top navigation bar'), ('side', 'Left sidebar')], default='top', help_text='Where the module menu lives for this user.', max_length=8),
        ),
    ]
