# Generated by Django 4.2.6 on 2026-09-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_userprofile_nav_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_code', models.CharField(db_index=True, max_length=80)),
                ('record_ids', models.CharField(max_length=1000)),
                ('check_title', models.CharField(blank=True, max_length=200)),
                ('module', models.CharField(blank=True, max_length=60)),
                ('numbers', models.CharField(blank=True, max_length=500)),
                ('matched', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_dismissals', to=settings.AUTH_USER_MODEL)),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_dismissals_undone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dismissed_at', '-id'],
                'indexes': [models.Index(fields=['check_code', 'undone_at'], name='user_duplic_check_c_79d096_idx')],
            },
        ),
    ]
