# Generated by Django 4.2.6 on 2026-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_duplicates_widget_for_configured_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Light or dark, for this user on every device they sign in on.', max_length=8),
        ),
    ]
