# Generated by Django 4.2.6 on 2026-07-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_aadhar_customer_account_no_and_more'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('is_running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync lock',
                'verbose_name_plural': 'Sync lock',
                'db_table': 'employee_tracking_sync_lock',
            },
        ),
        migrations.AddField(
            model_name='employeecustomervisit',
            name='external_customer_name',
            field=models.CharField(blank=True, help_text='Customer name as reported by the provider, kept for matching/repair when no CRM customer was found.', max_length=255),
        ),
        migrations.AlterField(
            model_name='employeecustomervisit',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Matched CRM customer; empty when the vendor-side customer has no CRM counterpart yet (see external_customer_name).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracking_visits', to='sales.customer'),
        ),
    ]
