# Generated by Django 4.2.6 on 2026-07-16 19:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0025_delete_sector'),
        ('tracking', '0002_synclock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsettings',
            name='attendance_auto_approve',
            field=models.BooleanField(default=False, help_text='Mirror GPS attendance into HR immediately, without manual approval.'),
        ),
        migrations.AddField(
            model_name='trackingsettings',
            name='attendance_sync_enabled',
            field=models.BooleanField(default=True, help_text='Build GPS attendance records from provider check-in/out events.'),
        ),
        migrations.CreateModel(
            name='EmployeeGpsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('check_in_address', models.TextField(blank=True)),
                ('check_out_address', models.TextField(blank=True)),
                ('check_in_photo_url', models.URLField(blank=True, max_length=500)),
                ('check_out_photo_url', models.URLField(blank=True, max_length=500)),
                ('check_in_inside_fence', models.BooleanField(blank=True, help_text='Null when no active fence was available to verify against.', null=True)),
                ('check_out_inside_fence', models.BooleanField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_by', models.DurationField(blank=True, null=True)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('early_by', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(blank=True, help_text='The mirrored HR attendance row, once approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_records', to='hr.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_attendance', to='hr.employee')),
                ('geofence', models.ForeignKey(blank=True, help_text='Office/work fence the check-in was verified against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.employeegeofence')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tracking.trackingprovider')),
            ],
            options={
                'verbose_name': 'GPS Attendance',
                'verbose_name_plural': 'GPS Attendance',
                'db_table': 'employee_attendance_gps',
                'ordering': ('-date',),
            },
        ),
        migrations.AddConstraint(
            model_name='employeegpsattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='uq_gps_attendance_employee_date'),
        ),
    ]
