# Generated by Django 4.2.6 on 2026-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_trackingsettings_attendance_auto_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglog',
            name='event',
            field=models.CharField(choices=[('sync_started', 'Sync Started'), ('sync_completed', 'Sync Completed'), ('sync_failed', 'Sync Failed'), ('webhook_received', 'Webhook Received'), ('webhook_rejected', 'Webhook Rejected'), ('employee_offline', 'Employee Offline'), ('gps_disabled', 'GPS Disabled'), ('no_internet', 'No Internet'), ('geofence_entry', 'Geofence Entered'), ('geofence_exit', 'Geofence Exited'), ('outside_working_area', 'Outside Working Area'), ('late_check_in', 'Late Check-In'), ('early_check_out', 'Early Check-Out'), ('missed_visit', 'Missed Customer Visit'), ('provider_changed', 'Provider Configuration Changed'), ('settings_changed', 'Tracking Settings Changed'), ('mapping_changed', 'Employee Mapping Changed'), ('geofence_changed', 'Geofence Changed'), ('attendance_approval', 'Attendance Approval Decision')], max_length=30),
        ),
    ]
