# Generated by Django 4.2.6 on 2026-07-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_trackinglog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecustomervisit',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Vendor-hosted visit photo, when the provider supplies one.', max_length=500),
        ),
        migrations.AlterField(
            model_name='employeecustomervisit',
            name='photo',
            field=models.ImageField(blank=True, help_text='Locally uploaded photo (manual entry).', null=True, upload_to='visit_photos/'),
        ),
    ]
