# Generated by Django 4.2.6 on 2026-07-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_employeecustomervisit_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelivelocation',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last device heartbeat. Vendors refresh the GPS fix only on movement, so online/offline is judged by the freshest of fix and heartbeat.', null=True),
        ),
        migrations.AlterField(
            model_name='employeelivelocation',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, help_text='Device-side timestamp of this position (GPS fix).'),
        ),
    ]
