"""Per-page icons for the sidebar, lifted from the hand-written navs.

The top navbar and the sub-nav strips each carry an icon beside every link,
chosen page by page over the life of the app. The sidebar is generated from
MODULE_REGISTRY, which holds structure and not looks, so without this map its
links would either be bare or wear icons freshly invented for them -- and the
same page would then be a different picture depending on which layout you were
in. These are those same icons, keyed by tab code.

Generated once from templates/main_top_navbar.html, templates/_subnav.html and
the _*_subnavbar.html strips; maintained by hand from here on. A tab with no
entry falls back to a neutral dot, so a new page is never a crash.
"""

#: tab code -> Font Awesome classes.
TAB_ICONS = {
    "alert_catalog": "fas fa-book",
    "alert_rule_list": "fas fa-sliders",
    "assign_groups": "fas fa-users-cog",
    "balance_sheet_report": "fas fa-scale-balanced",
    "bank_cash": "fas fa-university",
    "batch_wise_feed_scheduling_report": "fas fa-calendar-check",
    "bird_category": "fa-solid fa-crow",
    "bird_sale_list": "fas fa-truck-loading",
    "bird_sale_receipt_list": "fas fa-receipt",
    "branch_farm": "fas fa-tractor",
    "branch_summary_report": "fas fa-code-branch",
    "branch_template": "fas fa-code-branch",
    "breed": "fa-solid fa-dna",
    "breed_standard": "fa-solid fa-chart-line",
    "broiler_batch": "fas fa-layer-group",
    "broiler_batch_report": "fas fa-file-alt",
    "broiler_disease": "fas fa-virus",
    "broiler_farm_shed": "fas fa-warehouse",
    "broiler_line": "fas fa-map-marker-alt",
    "change_requests": "fa-solid fa-clipboard-check",
    "chick_sale_list": "fas fa-cash-register",
    "chick_sale_receipt_list": "fas fa-receipt",
    "chick_sale_report": "fas fa-cash-register",
    "chicks_placement_list": "fa-solid fa-kiwi-bird",
    "chicks_placement_report": "fa-solid fa-kiwi-bird",
    "chicks_purchase_list": "fa-solid fa-kiwi-bird",
    "coa": "fas fa-sitemap",
    "company_profile": "fas fa-building",
    "cost_center_report": "fas fa-chart-pie",
    "create_user": "fa-solid fa-users-gear",
    "credit_note_list": "fas fa-file-invoice-dollar",
    "customer": "fas fa-user",
    "customer_balance": "fas fa-scale-balanced",
    "customer_credit_note_list": "fas fa-file-invoice-dollar",
    "customer_debit_note_list": "fas fa-file-invoice",
    "customer_groups": "fas fa-layer-group",
    "customer_ledger": "fas fa-book",
    "customer_list_report": "fas fa-address-book",
    "customer_receipt_report": "fas fa-receipt",
    "daily_attendance": "fas fa-calendar-check",
    "daily_entry_list": "fas fa-calendar-day",
    "daily_entry_single_list": "fas fa-layer-group",
    "dashboard_access": "fas fa-gauge-high",
    "day_record_report": "fas fa-calendar-day",
    "debit_note_list": "fas fa-file-invoice",
    "delivery_challan_list": "fas fa-truck",
    "delivery_challan_report": "fas fa-truck",
    "designation": "fas fa-id-badge",
    "egg_grading_list": "fas fa-layer-group",
    "egg_purchase_list": "fas fa-shopping-basket",
    "egg_purchase_report": "fas fa-shopping-basket",
    "employee_access": "fas fa-user-shield",
    "employee_attendance": "fas fa-user-check",
    "employee_group": "fas fa-user-group",
    "employee_leave_details": "fas fa-list-alt",
    "employee_list": "fas fa-users",
    "env_alert_list": "fas fa-bell",
    "env_dashboard": "fas fa-gauge-high",
    "env_default_thresholds": "fas fa-sliders-h",
    "env_hub_list": "fas fa-tower-broadcast",
    "env_sensor_list": "fas fa-microchip",
    "env_tapo_account": "fas fa-key",
    "expense_type_list": "fas fa-tags",
    "farm_detailed_daily_entry_report": "fas fa-table-list",
    "farm_location_capture_list": "fas fa-location-dot",
    "farm_map_planner": "fas fa-map-location-dot",
    "farmer_farm_report": "fas fa-users",
    "farmer_farm_setup_request_list": "fas fa-user-plus",
    "farmer_gc_payment": "fas fa-money-check-dollar",
    "farmer_group": "fas fa-users",
    "farmer_ledger_report": "fas fa-book",
    "farmer_reconciliation_report": "fas fa-scale-balanced",
    "feed_dispatch_stock_report": "fas fa-seedling",
    "feed_phase_master_list": "fas fa-seedling",
    "field_bindings": "fas fa-link",
    "fin_year": "fas fa-calendar-alt",
    "gc_realization_report": "fas fa-scale-balanced",
    "gc_settlement": "fas fa-file-invoice-dollar",
    "general_purchase_list": "fas fa-file-invoice",
    "growing_charge": "fas fa-hand-holding-dollar",
    "hatch_entry_list": "fas fa-dove",
    "hatcher_list": "fas fa-temperature-high",
    "hatchery_expense_list": "fas fa-file-invoice-dollar",
    "hatchery_list": "fa-solid fa-egg",
    "hatchery_master_list": "fa-solid fa-kiwi-bird",
    "hatchery_report": "fas fa-chart-bar",
    "incubation_report": "fas fa-egg",
    "inventory_adjustment_list": "fas fa-sliders-h",
    "inventory_adjustment_report": "fas fa-sliders",
    "inventory_issued_report": "fas fa-arrow-up",
    "inventory_received_report": "fas fa-arrow-down",
    "item_category": "fas fa-folder",
    "item_ledger_report": "fas fa-book-open",
    "item_price_list": "fas fa-tags",
    "item_summary_report": "fas fa-list-check",
    "items": "fas fa-box",
    "journal_voucher_report": "fas fa-book",
    "leave_employee": "fas fa-user-times",
    "ledger_report": "fas fa-book-open",
    "lifting_report": "fas fa-truck-loading",
    "linked_tree": "fas fa-sitemap",
    "live_flock_summary_report": "fas fa-kiwi-bird",
    "mark_attendance": "fas fa-pen",
    "medicine_entry_list": "fas fa-syringe",
    "medicine_transfer_list": "fas fa-syringe",
    "mobile_access": "fas fa-mobile-screen-button",
    "negative_stock_report": "fas fa-triangle-exclamation",
    "offline_sync_monitor": "fas fa-cloud-arrow-up",
    "organization_centre": "fas fa-sitemap",
    "organization_centre_mapping": "fas fa-diagram-project",
    "payment_list": "fas fa-money-bill-wave",
    "payment_mode": "fas fa-money-check-dollar",
    "payroll": "fas fa-money-bill-wave",
    "picklists": "fas fa-list-check",
    "production_cost_report": "fas fa-indian-rupee-sign",
    "production_pl_report": "fas fa-chart-line",
    "profit_loss_report": "fas fa-chart-line",
    "purchase_report": "fas fa-file-invoice",
    "region": "fas fa-map-marked-alt",
    "route_history": "fas fa-clock-rotate-left",
    "route_reports": "fas fa-clipboard-list",
    "sales_invoice_list": "fas fa-file-invoice-dollar",
    "sales_price_master": "fas fa-tag",
    "sales_receipt_list": "fas fa-receipt",
    "sector": "fas fa-map-marker-alt",
    "send_notification": "fas fa-paper-plane",
    "setter_list": "fas fa-layer-group",
    "sms_history": "fas fa-clock-rotate-left",
    "sms_settings": "fas fa-gear",
    "sms_templates": "fas fa-comment-sms",
    "sms_transaction": "fas fa-paper-plane",
    "stock_issue_list": "fas fa-arrow-up-from-bracket",
    "stock_receive_list": "fas fa-inbox",
    "stock_report": "fas fa-boxes-stacked",
    "stock_transfer_list": "fas fa-right-left",
    "stock_transfer_report": "fas fa-right-left",
    "supervisor_template": "fas fa-user-tie",
    "supervisor_trip_report": "fas fa-car-side",
    "supplier": "fas fa-truck",
    "supplier_balance": "fas fa-scale-balanced",
    "supplier_ledger": "fas fa-book",
    "supplier_list_report": "fas fa-address-book",
    "tax_master": "fas fa-percentage",
    "terms": "fas fa-file-contract",
    "tracking_alerts": "fas fa-bell",
    "tracking_attendance": "fas fa-user-check",
    "tracking_dashboard": "fas fa-map-location-dot",
    "tracking_geofences": "fas fa-draw-polygon",
    "tracking_reports": "fas fa-chart-column",
    "tracking_routes": "fas fa-route",
    "tracking_settings": "fas fa-gear",
    "tracking_visits": "fas fa-handshake",
    "tray_set_list": "fas fa-table-cells",
    "unit_of_measurement": "fas fa-ruler",
    "user_analytics": "fas fa-chart-line",
    "user_groups": "fas fa-layer-group",
    "vendor_groups": "fas fa-users",
    "vouchers": "fas fa-book",
    "warehouse": "fas fa-building",
    "warehouse_mapping": "fas fa-diagram-project",
}

DEFAULT_TAB_ICON = "fa-regular fa-circle-dot"
