# Generated by Django 4.2.6 on 2025-01-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("purchase", "0003_purchaseorderlineitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "control_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "advance_account",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the contact", max_length=255
                    ),
                ),
                ("address", models.TextField(help_text="Address of the contact")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Place information",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone number", max_length=15, unique=True
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        help_text="Mobile number", max_length=15, unique=True
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("Supplier", "Supplier"),
                            ("Customer", "Customer"),
                            ("Supplier & Customer", "Supplier & Customer"),
                        ],
                        default="Supplier & Customer",
                        help_text="Type of contact",
                        max_length=20,
                    ),
                ),
                (
                    "pan_tin",
                    models.CharField(
                        blank=True, help_text="PAN/TIN number", max_length=50, null=True
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Credit limit in currency",
                        max_digits=10,
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True, help_text="GSTIN number", max_length=15, null=True
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, help_text="State", max_length=50, null=True
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Additional notes", null=True
                    ),
                ),
                (
                    "supplier_address",
                    models.TextField(
                        blank=True, help_text="Supplier address", null=True
                    ),
                ),
                (
                    "credit_term",
                    models.ForeignKey(
                        blank=True,
                        help_text="Credit term",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchase.creditterm",
                    ),
                ),
                (
                    "customer_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer group",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.customergroup",
                    ),
                ),
                (
                    "supplier_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier group",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchase.vendorgroup",
                    ),
                ),
            ],
        ),
    ]
