# Generated by Django 4.2.6 on 2025-01-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_rename_category_itemcategory"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPriceMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sales price of the item",
                        max_digits=10,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, help_text="Date of price entry"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.item",
                    ),
                ),
                (
                    "item_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.itemcategory",
                    ),
                ),
            ],
        ),
    ]
