# Generated by Django 4.2.6 on 2025-01-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_remove_purchaseorderlineitem_category_and_more"),
        ("sales", "0002_salespricemaster"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Customer",
        ),
    ]
