# Generated by Django 4.2.6 on 2026-07-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_customershippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar',
            field=models.CharField(blank=True, help_text='Aadhar number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_no',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/agreements/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='as_on_date',
            field=models.DateField(blank=True, help_text='Opening balance as-on date', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, help_text='Short customer code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_period',
            field=models.PositiveIntegerField(blank=True, help_text='Credit period in days', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_2',
            field=models.CharField(blank=True, help_text='Secondary mobile number', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Opening balance', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/other/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='party_category',
            field=models.CharField(blank=True, choices=[('Retailer', 'Retailer'), ('Wholesaler', 'Wholesaler'), ('Distributor', 'Distributor'), ('Farmer', 'Farmer'), ('Other', 'Other')], help_text='Party category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='to_pay_to_receive',
            field=models.CharField(blank=True, choices=[('To Pay', 'To Pay'), ('To Receive', 'To Receive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='Billing address of the contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_type',
            field=models.CharField(choices=[('Supplier', 'Supplier'), ('Customer', 'Customer'), ('Supplier & Customer', 'Supplier & Customer')], default='Supplier & Customer', help_text='Party type', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(help_text='SMS/WhatsApp number', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, help_text='Remarks', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, help_text='State of supply', max_length=50, null=True),
        ),
    ]
