# Generated by Django 4.2.6 on 2026-07-24 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
        ('sales', '0006_alter_customergroup_advance_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. INV-2627-0001', max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('Sales Invoice', 'Sales Invoice'), ('Delivery Challan', 'Delivery Challan'), ('Quotation', 'Quotation')], default='Sales Invoice', max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('billing_address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('transportation', models.CharField(blank=True, max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('eway_bill_no', models.CharField(blank=True, max_length=50)),
                ('sales_person', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='inventory.warehouse')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='sales.customer')),
                ('organization_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='account.organizationcentre')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('hsn_sac', models.CharField(blank=True, max_length=20)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesinvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_items', to='inventory.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
