# Generated by Django 4.2.6 on 2026-07-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesinvoice_salesinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='free_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
