# Generated by Django 4.2.6 on 2026-07-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
        ('sales', '0008_salesinvoiceitem_free_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='account.bankcashmaster'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='account.termsconditions'),
        ),
    ]
