# Generated by Django 4.2.6 on 2026-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesinvoice_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
