# Generated by Django 4.2.6 on 2026-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salesinvoice_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='print_bank_details',
            field=models.BooleanField(default=True, help_text='Print the company bank details on the invoice'),
        ),
    ]
