# Generated by Django 4.2.6 on 2026-07-25 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0023_alter_organizationcentre_allow_children_only_and_more'),
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('sales', '0011_salesinvoice_print_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, editable=False, help_text='Auto-generated transaction number, e.g. SR-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Card', 'Card')], default='Cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_no', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_receipts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='sales.customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='inventory.warehouse')),
                ('receipt_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_receipts', to='account.chartofaccount')),
            ],
            options={
                'verbose_name': 'Sales Receipt',
                'verbose_name_plural': 'Sales Receipts',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
