# Generated by Django 4.2.6 on 2026-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_type',
            field=models.CharField(default='Supplier & Customer', help_text='Party type', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='party_category',
            field=models.CharField(blank=True, help_text='Party category', max_length=50, null=True),
        ),
    ]
