# Generated by Django 4.2.6 on 2026-07-30 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_chartofaccount_uniq_coa_company_code_and_more'),
        ('sales', '0013_alter_customer_contact_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. CDN-2627-0001 / CCN-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('against_bill', models.CharField(blank=True, help_text='Related sales invoice/bill no.', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.chartofaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.customer')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_no', models.CharField(blank=True, editable=False, help_text='Auto-generated, e.g. CDN-2627-0001 / CCN-2627-0001', max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('against_bill', models.CharField(blank=True, help_text='Related sales invoice/bill no.', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.chartofaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='sales.customer')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
    ]
