# Generated by Django 4.2.6 on 2026-07-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_item_valuation_methods_fifo_lifo_fefo'),
        ('sales', '0014_customerdebitnote_customercreditnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercreditnote',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='customerdebitnote',
            name='reason',
        ),
        migrations.AddField(
            model_name='customercreditnote',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Office / branch this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='customerdebitnote',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Office / branch this note belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='customercreditnote',
            name='against_bill',
            field=models.CharField(blank=True, help_text='Related sales invoice / DC no.', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerdebitnote',
            name='against_bill',
            field=models.CharField(blank=True, help_text='Related sales invoice / DC no.', max_length=50),
        ),
    ]
