# Generated by Django 4.2.6 on 2026-08-01 20:09

import Hitech_BIMS.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_customercreditnote_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='customer_documents/agreements/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='other_documents',
            field=models.FileField(blank=True, null=True, storage=Hitech_BIMS.storage_backends.private_media_storage, upload_to='customer_documents/other/'),
        ),
    ]
