# Generated by Django 4.2.6 on 2026-09-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_customer_agreement_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=15, null=True),
        ),
    ]
