# Generated by Django 4.2.6 on 2026-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_customer_unique_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreceipt',
            name='mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
    ]
